90 91 93 login register profile
AjobK/Athena pull request #177
Opened 2019-07-19 17:42 UTC by ryankroon00

Closes #90 #91 #93 

 **What is it supposed to do**
Explain in short what your component is supposed to do

 **How can we test your branch**
Explain how can test your branch Ex. width, height etc...

 **What browser have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [ ] Internet Explorer
- [x] Edge
- [ ] Safari

2019-07-19 18:12 UTC, MiguelFieira requested changes
Some linting ;)

2019-07-19 18:12 UTC, MiguelFieira commented on passport/app/Rules/Captcha.php
> +}
Endline

2019-07-19 18:12 UTC, MiguelFieira commented on passport/app/Rules/Lowercase.php
> +        //
empty comment

2019-07-19 18:12 UTC, MiguelFieira commented on passport/app/Rules/NumberOrSpecial.php
> +        //
empty comment

2019-07-19 18:12 UTC, MiguelFieira commented on passport/app/Rules/Uppercase.php
> +        //
empty comment

2019-07-19 18:12 UTC, MiguelFieira commented on passport/routes/api.php
> +// ], function ($router) {
Remove this section if your not gonna use it

2019-07-19 18:12 UTC, MiguelFieira commented on passport/routes/api.php
> +//      Route::post('register', 'PassportController@register');
Remove this section if your not gonna use it

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/button/button.scss
> +	background-color: gray !important;
Use color variables if posible

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/loginPrompt/index.js
> +export default withRouter(LoginPrompt)
endline

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/index.js
> +export default withRouter(RegisterPrompt)
endline

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +	font-family: Poppins;
use the variable $mainfont instead.

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/registerPrompt/index.js
> +export default withRouter(RegisterPrompt)
endline

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
> +		color: black;
use a $variable if posible

2019-07-19 18:12 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  	font-family: Poppins;
use the variable $mainfont instead.

2019-07-19 18:15 UTC, AjobK commented on passport/routes/api.php
> +// ], function ($router) {
you're*

2019-07-19 18:23 UTC, MiguelFieira commented
![image](https://user-images.githubusercontent.com/23557268/61556811-07272180-aa63-11e9-89c6-34f68eec43fa.png)
Don't forget to update the description!!!

2019-07-19 18:36 UTC, MiguelFieira requested changes
Sorry 📦 # $color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on passport/app/Http/Kernel.php
> +        // 'cors' => \App\Http\Middleware\Cors::class,
Why is this commented out?

2019-07-19 18:36 UTC, MiguelFieira commented on passport/app/Http/Kernel.php
> +        // \App\Http\Middleware\Cors::class,
Why is this commented out?

2019-07-19 18:36 UTC, MiguelFieira commented on passport/app/Rules/Captcha.php
> +        return 'Are you a robot?';
Are you a Seaqull ?*

![image](https://user-images.githubusercontent.com/23557268/61557146-c67bd800-aa63-11e9-962e-fcd0c1eccc95.png)

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/formInput/formInput.scss
> +	font-family: Poppins;
Use the $variable instead, incase we ever have to change the font everywhere we could do it in one go

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/formInput/formInput.scss
> +	color: #7f7f7f;
Color could be a variable :)

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/formInput/formInput.scss
> +		border-bottom: 1px solid gray;
solid $gray (make a color variable)

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/formInput/formInput.scss
> +	color: gray;
gray again this could be a color variable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/loginPrompt/loginPrompt.scss
>  	background-color: white;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/loginPrompt/loginPrompt.scss
>  	border: 1px solid whitesmoke;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/loginPrompt/loginPrompt.scss
> +	color: gray;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/loginPrompt/loginPrompt.scss
>  		color: #fff;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/loginPrompt/loginPrompt.scss
> +		color: black;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +	background-color: white;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +	border: 1px solid whitesmoke;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +		color: black;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +		color: #9b9b9b;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +	color: #7f7f7f;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/postBanner/registerPrompt/registerprompt.scss
> +	color: gray;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  		color: #9b9b9b;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  			color: #9b9b9b;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  	border-bottom: 1px solid gray;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  	color: #7f7f7f;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
>  	color: gray;
$color vriable

2019-07-19 18:36 UTC, MiguelFieira commented on src/components/registerPrompt/registerprompt.scss
> +	background-color: white;
$color vriable

2019-07-19 19:00 UTC, AjobK commented on passport/app/Rules/Captcha.php
> +        return 'Are you a robot?';
No one is gonna understand this...

2019-07-27 17:48 UTC, ghost commented on passport/app/Http/Controllers/PassportController.php
> +      if ($targetUser && now() < $targetUser->locked_to) {
Ik denk dat de code leesbaarder wordt op het moment dat je deze check: `now() < $targetUser->locked_to` als methode in het Account model toevoegt. voorbeeld: $targetUser->isLocked()

2019-07-27 17:49 UTC, ghost commented on passport/app/Http/Controllers/PassportController.php
> +        if ($targetUser->login_attempts_count > 2 && $targetUser->login_attempts_count % 3 == 0) {
Move hardcoded value for the number of attempts to a property so it can easily be changed later.

2019-07-27 17:51 UTC, ghost commented on passport/app/Http/Controllers/PassportController.php
> +          $targetUser->locked_to = date('Y-m-d H:i:s', time() + 30);
Move hardcoded value for the amount of time an account is locked to a property.

2019-07-27 18:51 UTC, Samvdg commented
Zodra ik probeer te registreren krijg ik een unproccesable entity error.
Ik heb XAMPP en heb geprobeerd de wiki te volgen maar het zou daar aan kunnen liggen
(ik heb dit ook bij inloggen, no matter wat ik in typ)

2019-08-23 17:50 UTC, merged