192 like posts
AjobK/Athena pull request #195
Opened 2021-03-13 14:13 UTC by jerohero

closes #192

 **What is it supposed to do**
Like posts (or undo likes)

 **How can we test your branch**
Try it out I suppose

 **What broweser have been checked**
- [X] Chrome
- [X] Firefox
- [ ] Opera
- [X] Internet Explorer (The whole thing won't even load 😃)
- [X] Edge
- [ ] Safari

2021-03-13 14:14 UTC, AjobK requested changes
Some things were wrong 😞

2021-03-13 14:14 UTC, AjobK commented on backend/app/controllers/postController.ts
> +        this.router.delete(this.post + '/like/:path', isAuth, this.postService.unlikePost)
This is a dummy, I dislike this :-(

2021-03-13 14:14 UTC, AjobK commented on backend/app/entity/post_like.ts
> +
Not nice (Test) 👎

2021-03-13 14:20 UTC, jerohero commented on backend/app/entity/post_like.ts
> +
mean 😡

2021-03-19 19:10 UTC, AjobK commented
@jerohero Has conflicts that need to be resolved. Most likely due to usage of 'user' which has been renamed to 'profile'

2021-03-20 10:38 UTC, AjobK requested changes
FEATURE MISSING?: Please redirect to login when user tries to like when logged out

Infinite request when removing like twice

2021-03-20 10:38 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +                console.log(res.data.message)
Console.log

2021-03-20 10:38 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +                console.log(res.data.message)
Console.log

2021-03-20 10:38 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +                console.log(err)
Console.log

2021-03-20 10:38 UTC, AjobK commented on frontend/src/pages/post/index.js
> +            console.log('Error occurred while fetching post')
Console.log

2021-03-20 10:38 UTC, AjobK commented on frontend/src/pages/post/index.js
> +        console.log('LIKE TOGGLED')
Console.log

2021-03-20 10:38 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +                    alert('Not signed in!')
Replace with redirect to login screen

2021-03-20 10:38 UTC, AjobK commented on frontend/src/pages/post/index.js
> +                    user_liked: res.data.likes.user_liked
Camelcase if possible please...

2021-03-20 10:38 UTC, AjobK commented on frontend/src/pages/post/index.js
> +                user_liked: false
If possible camelcase

2021-03-20 12:49 UTC, jerohero commented on frontend/src/pages/post/index.js
> +                    }
What is all this for? (from merge with develop)

2021-03-20 13:41 UTC, AjobK requested changes
Semi colons

2021-03-20 13:41 UTC, AjobK commented on backend/app/entity/post_like.ts
> +    id: number;
semicolon

2021-03-20 13:41 UTC, AjobK commented on backend/app/service/postService.ts
> +import Profile from '../entity/profile';
Semi

2021-03-20 14:11 UTC, merged