186 adding comments
AjobK/Athena pull request #197
Opened 2021-03-19 20:15 UTC by MrGooss

closes #186 

LEAVE AS IS, some necessary fixes have to be made before pulling

 **What is it supposed to do**
Add comments to posts

 **How can we test your branch**
Pull branch and add comment

 **What browser have been checked**
- [x] Chrome
- [ ] Firefox
- [ ] Opera
- [ ] Internet Explorer
- [x] Edge
- [ ] Safari

2021-03-20 10:23 UTC, AjobK requested changes
Mainly semi-colons, console.logs and newlines among other things

---

COMMENT: User can see comment field when loggedout. Please redirect to login page when user clicks on 'save' and he/she gets error

BUG: Also getting error when adding comment and going back to post.
![image](https://user-images.githubusercontent.com/35965716/111866632-26c8c880-896f-11eb-81a9-3a68497bd4a8.png)

MISSING FEATURE?: Comment is not directly added when pressing 'save' succesfully

2021-03-20 10:23 UTC, AjobK commented on backend/app/service/commentService.ts
> +        console.log('made it here')
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentEditor/index.js
> +        console.log(convertToRaw(editorState.getCurrentContent()))
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentForm/index.js
> +        console.log('saving')
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentForm/index.js
> +            console.log(response.data)
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentForm/index.js
> +            console.log(err)
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +            console.log(response.data)
Please remove console logs

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/comment/index.js
> +    //TODO: move to util
TODO?

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentEditor/index.js
> +import "draft-js/dist/Draft.css";
Please use single quotes

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                return ""
Please use single quotes

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentEditor/index.js
> +        this.setState({editorState});
Please remove semi-colons

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +        let path = window.location.pathname.split('/').filter(i => i != '').pop();
Please remove semi-colons

2021-03-20 10:23 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +const isAuth = require('../middleware/isAuth');
Semi-colon

2021-03-20 10:23 UTC, AjobK commented on backend/app/service/commentService.ts
> +            return res.status(404).json({ 'message': 'No comments found on that path' });
Semi-colons

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/comment/index.js
> +        switch (true) {
Switch true...?

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                return Math.round(diff / year) + ' years ago'
If possible please make a time utility class or something similar. This is a bit extensive.

Multiple WET lines too

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentEditor/index.js
> +import "draft-js/dist/Draft.css";
And semi-colon

2021-03-20 10:23 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +export default CommentController
Newline

2021-03-20 10:23 UTC, AjobK commented on backend/app/dao/commentDao.ts
> +export default CommentDAO
Newline

2021-03-20 10:23 UTC, AjobK commented on backend/app/service/commentService.ts
> +export default CommentService
Newline

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/comment/index.js
> +export default Comment
Newline

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentEditor/index.js
> +export default CommentEditor
Newline

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentForm/index.js
> +export default CommentForm;
Newline

2021-03-20 10:23 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +export default CommentSection
Newline

2021-03-27 10:04 UTC, MrGooss commented on frontend/src/components/commentEditor/index.js
> +        console.log(convertToRaw(editorState.getCurrentContent()))
Fixed

2021-04-03 08:38 UTC, MrGooss commented
Implemented changes, please review @AjobK

2021-04-10 08:14 UTC, closed without merging