203 view liked posts & 198 view liked posts on profile
AjobK/Athena pull request #209
Opened 2021-03-27 14:47 UTC by jerohero

closes #203
closed #198

 **What is it supposed to do**
Everyone can see who liked a post and can see what posts a user liked on their profile (yes I put two different use cases in one branch)

 **How can we test your branch**
- Go to a post and click on the amount of a like to open the list (shouldn't be possible if there are no likes)
- Click on a profile in the list, test whether it's sorting properly or whatever
- Go to a profile and look at the liked posts. See if this updates properly and is sorted.

 **What broweser have been checked**
- [x] Chrome
- [x] Firefox
- [ ] Opera
- [ ] Edge
- [ ] Safari

2021-03-27 14:58 UTC, AjobK requested changes
Change to fontawesome icons, see screenshot for style reference too:
![image](https://user-images.githubusercontent.com/35965716/112724774-37e87b00-8f15-11eb-8785-b676a2a09bbe.png)

Rename feathers to likes

Make overlay fixed, not absolute

2021-03-27 16:48 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/112727835-9ec16080-8f24-11eb-8d52-87a942a95136.png)

When hallway testing it appeared that spamming the like button results in multiple likes by a single person.

2021-04-02 16:44 UTC, jerohero commented
> ![image](https://user-images.githubusercontent.com/35965716/112727835-9ec16080-8f24-11eb-8d52-87a942a95136.png)
> 
> When hallway testing it appeared that spamming the like button results in multiple likes by a single person.

I was unable to recreate this issue by spamming the like button, and forcing a like request from DevTools while the post is liked wouldn't succeed either.

![chrome_Ajk6rjYwMi](https://user-images.githubusercontent.com/14930277/113435512-40442880-93e3-11eb-9085-e9a49766bad2.png)

2021-04-02 18:05 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/113441353-68855480-93ee-11eb-8b26-dd916fb79a59.png)
Unable to scroll in this window

Please make the profile_id and post_id combination unique in the post_like table, so there will never be a duplicate like (In other words, one person liking twice).

Also turn the 'X' on the right into an icon.
![image](https://user-images.githubusercontent.com/35965716/113441403-8ce13100-93ee-11eb-96f8-08344908abcd.png)
I suggest this one: https://fontawesome.com/icons/times-circle?style=solid

Change the view into the example previously shown in discord, except for the 'Feathers' part which should be 'Likes' and obviously the icons:
![image](https://user-images.githubusercontent.com/35965716/113441557-c6b23780-93ee-11eb-92f0-5a703ffb110c.png)

2021-04-02 18:13 UTC, AjobK requested changes
A few other minor things

2021-04-02 18:13 UTC, AjobK commented on backend/app/dao/postDao.ts
> +            return null
Newline under return

2021-04-02 18:13 UTC, AjobK commented on backend/app/dao/postDao.ts
> +        const likes = await repository.find({ where: {profile: profileId}, relations: ['post', 'profile'], take: limit})
newline under declaration

2021-04-02 18:13 UTC, AjobK commented on backend/app/dao/postDao.ts
> +        if (!likes || likes.length <= 0) return
newline under

2021-04-02 18:13 UTC, AjobK commented on backend/app/dao/postDao.ts
> +        return likes.sort((a, b) => {
a and b is cryptic. Please use understandable variable names

2021-04-02 18:13 UTC, AjobK commented on backend/app/service/postService.ts
> +        else
Please use either shorthand or the extended version. Don't combine if () {} with a normal else without curly braces. In this case use curly braces for the else

2021-04-02 18:13 UTC, AjobK commented on backend/app/service/postService.ts
> +            const likes = []
newline under

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +import Like from '../../static/icons/heart-solid.svg';
Please use icons differently. Use navigation for reference. There is a seperate component for icons

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +                {this.state.showLikes && (
Space before 'this.state.showLikes' to make it more readable and clean. Same for cases above such as '{likesAmount' which should be '{ likesAmount'

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +        const path = window.location.pathname.split('/').filter(i => i != '').pop()
Newline under

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +                const likes = []
Newline under

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +                    likes.push(userLike)
newline above

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +                        {this.state.likes.map((like, index) => {
space between { and this resulting in '{ this.state.likes.....'

2021-04-02 18:13 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +        })
Remove comment

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +import Like from '../../static/icons/heart-solid.svg';
Also remove semicolon

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +import { Link } from "react-router-dom";
Please use single quotes and remove semicolon

2021-04-02 18:13 UTC, AjobK commented on frontend/src/components/postLikesList/index.js
> +import Axios from "axios"
Single quotes

2021-04-03 12:36 UTC, jerohero commented
@AjobK

2021-04-03 13:18 UTC, AjobK requested changes
minor changes and show like for owner of post

2021-04-03 13:18 UTC, AjobK commented on backend/app/service/postService.ts
> +        }
else on this line

2021-04-03 13:18 UTC, AjobK commented on frontend/src/components/postBanner/index.js
>  import { Icon } from '..';
semicolon

2021-04-03 14:37 UTC, AjobK approved these changes
Looks good! :-)

2021-04-03 14:37 UTC, ryankroon00 approved these changes

2021-04-03 14:38 UTC, merged