194 profile info
AjobK/Athena pull request #210
Opened 2021-03-28 16:28 UTC by ryankroon00

closes #194

 **What is it supposed to do**
This component is supposed to display a profile description and you should be able to edit this as well. 

 **How can we test your branch**
- login
- you should see your profile description
- click edit
- edit the description
- save the description
- if you refresh the profile page the description should be updated

 **What browser have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [ ] Edge
- [ ] Safari

2021-03-28 21:45 UTC, AjobK requested changes
Please consistently use 4 spaces as indentation instead of 2. Also don't forget newlines, import order, spaces in front of ifs other reserved keywords and consistent use of shorthand or non-shorthand.

Goodluck, waiting for the next review request!

2021-03-28 21:45 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +const auth = require('../middleware/isAuth.ts')
Please add newline to seperate from ES6 imports

2021-03-28 21:45 UTC, AjobK commented on backend/app/controllers/profileController.ts
>  import * as express from 'express'
Please order imports as following:

1. Imports from base modules (Such as react itself)
2. Imports from 3rd party modules (Such ass express)
3. ES6 imports from filesystem (Such as controller)
4. ES5 and under imports (Const require)

2021-03-28 21:45 UTC, AjobK commented on backend/app/dao/postDao.ts
> +        return await repository.find({ where: { post: id }, relations: ['post', 'profile'] })
Newline above return

2021-03-28 21:45 UTC, AjobK commented on backend/app/dao/postDao.ts
>              return null
Please put on same line as if (!id) since this is very short, or add newline under return null

2021-03-28 21:45 UTC, AjobK commented on backend/app/dao/postDao.ts
>          const repository = await DatabaseConnector.getRepository('PostLike')
Newline above and under variable declaration

2021-03-28 21:45 UTC, AjobK commented on backend/app/factories/profileFactory.ts
>      return profileFake
Newline above return

2021-03-28 21:45 UTC, AjobK commented on backend/app/factories/profileFactory.ts
> +    profileFake.description = '{"blocks":[{"key":"dvnp","text":"i`m a wild seaqull","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}'
... DraftJS logic in the backend, stringified? Please use regular strings and make it work in the front-end. Never change the backend to work for the front-end, always change the front-end to work with the back-end.

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/authorizationService.ts
>          }
Why is this not shorthand like other parts of your code?

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/authorizationService.ts
> +
Random newline?

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/authorizationService.ts
> +            }
Why not use shorthand consistently with other code?

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/authorizationService.ts
>              const validation = this.validateAccountRequest(account,username,password)
Newline under declaration

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/postService.ts
>  const jwt = require('jsonwebtoken')
newline above const import

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/postService.ts
> +        const { token } = req.cookies
Newline under

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
>  const { SECURE } = process.env
Add newlines and order imports correctly as stated in a previous comment

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        const profile = await this.dao.getProfileByUsername(req.body.username)
newline under

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        if(req.decoded.username != req.body.username)
Please add space next to if for every if and for

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        if(profile == null)
space in front of if

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
>          const isUsernamNotValid = await this.checkValidUsername(userRequested.username)
newline under

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        }
Why not use shorthand consistently

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        // remove old cookie
Remove comment. Code is already self-describing

2021-03-28 21:45 UTC, AjobK commented on backend/app/service/profileService.ts
> +        newProfile.description = '{"blocks":[{"key":"dvnp","text":"i`m a wild seaqull","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}'
As stated earlier, make front-end work back-end, not other way around

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    const user = this.state.user
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    user.description = convertToRaw(editorState.getCurrentContent())
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    let state = EditorState.createWithContent(ContentState.createFromText(this.getDescription()))
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    console.log(this.state.user)
BEGONE THOTTTTTTT

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    for(let blockIndex = 0; blockIndex < textBlockArray.blocks.length; blockIndex++) {
Space in front of for

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    let text = ''
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    if(this.state.changedContent){
space in front of if

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    if (!this.props.startEditing) this.saveNewDescription()
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +          />
Indentation wrong, please backspace once

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +  onChange = (editorState) => {
Please make indentation for this whole file 4 spaces

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +
Please order imports correctly

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +    Axios.defaults.baseURL = this.props.store.defaultData.backendUrl
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +    if(this.state.user.isOwner){
space in front of if

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +    let icon
newline under

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +      />
one indent back

2021-03-28 21:45 UTC, AjobK commented on frontend/src/pages/profile/profile.scss
> +	right: 50%;
Absolute?? Is this actually necessary? Haven't tested the branch itself yet

2021-03-28 21:45 UTC, AjobK commented on frontend/src/components/profileInfo/profileInfo.scss
> +@import '../../styles/index.scss';
You already know. Tried to fish out all the semi-colons did you? Nope

2021-03-29 07:02 UTC, ryankroon00 commented on frontend/src/components/profileInfo/profileInfo.scss
> +@import '../../styles/index.scss';
bro dit is de scss file die vol staat met ; 

daarnaast is de eerste lijn bij elke scss file het zelfde 
@import '../../styles/index.scss';

2021-03-29 07:13 UTC, ryankroon00 commented on frontend/src/pages/profile/profile.scss
> +	right: 50%;
no

2021-03-29 08:50 UTC, AjobK commented on frontend/src/components/profileInfo/profileInfo.scss
> +@import '../../styles/index.scss';
Fair, fout gezien

2021-04-02 18:19 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/113442541-805dd800-93f0-11eb-91b1-50458d6b61b2.png)
Massive error when checking out my profile? It refers to draftjs content

Some js files have 2 spaces, some have 1 tab. Inconsistent indentation, please make 4 spaces

Generally the code looks good but I can't test the branch brecause of error

2021-04-02 18:19 UTC, AjobK commented on backend/app/service/profileService.ts
> +        return res.status(200).json({ 'message': 'Succes' })
newline above

2021-04-02 18:19 UTC, AjobK commented on backend/app/service/profileService.ts
> +        await this.dao.saveProfile(profile)
newline above since it's an assignment

2021-04-02 18:19 UTC, AjobK commented on backend/app/service/profileService.ts
> +        return res.status(200).json({ 'profile': payload })
newline above

2021-04-02 18:19 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +				let text = ''
Why is this indented?

2021-04-02 18:19 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +			return text
newline above

2021-04-02 18:19 UTC, AjobK commented on backend/app/service/profileService.ts
> +        //newProfile.description = '{"blocks":[{"key":"dvnp","text":"i`m a wild seaqull","type":"unstyled","depth":0,"inlineStyleRanges":[],"entityRanges":[],"data":{}}],"entityMap":{}}'
Remove this comment

2021-04-02 18:19 UTC, AjobK commented on frontend/src/pages/profile/profile.scss
> +.iconContainer {
Newline above

2021-04-03 09:40 UTC, AjobK requested changes

2021-04-03 09:40 UTC, AjobK commented on backend/app/service/authorizationService.ts
> +            if(validation != null) return res.status(400).send(validation)
space in front of if

2021-04-03 09:40 UTC, AjobK commented on backend/app/dao/postDao.ts
>              return false
Please add newline under? uwu

2021-04-03 09:40 UTC, AjobK commented on backend/app/service/postService.ts
> +import ProfileDAO from '../dao/profileDao'
Please use ProfileDAO and import '../dao/profileDAO' instead of '../dao/profileDao'

2021-04-03 14:15 UTC, AjobK approved these changes
Looks good :-) Goodjob

2021-04-03 14:15 UTC, merged