190 comment section
AjobK/Athena pull request #221
Opened 2021-05-01 11:46 UTC by MrGooss

closes #190 

 **What is it supposed to do**
You should now be able to add comments and recursive comments to posts and delete them.

 **How can we test your branch**
Open a post, add a comment, add replies and delete it with the delete button.

 **What browser have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [x] Edge
- [ ] Safari

2021-05-02 06:13 UTC, ryankroon00 requested changes
Looking good, I think it can be merged after these small changes <3

2021-05-02 06:13 UTC, ryankroon00 commented on backend/app/controllers/commentController.ts
> +        const comment = await this.dao.getComment(req.params.id)
Enter after defining variable

2021-05-02 06:13 UTC, ryankroon00 commented on backend/app/dao/commentDao.ts
> +
If you define more than one variable you can group these together, you only have to put an enter after the group of variabels

2021-05-02 06:13 UTC, ryankroon00 commented on backend/app/dao/commentDao.ts
> +
unnecessary enter

2021-05-02 06:13 UTC, ryankroon00 commented on frontend/src/components/commentEditor/index.js
> +
unnecessary enter

2021-05-02 06:13 UTC, ryankroon00 commented on frontend/src/components/commentSection/index.js
> +        let path = window.location.pathname.split('/').filter(i => i != '').pop()
Path is not reassigned so use constant instead of let

2021-05-02 06:13 UTC, ryankroon00 commented on frontend/src/components/commentSection/index.js
> +        let filteredComments = commentList.filter(comment => {
let -> contant

2021-05-02 06:13 UTC, ryankroon00 commented on frontend/src/components/commentSection/index.js
> +        let commentMap = {}
let -> contst

2021-05-02 06:13 UTC, ryankroon00 commented on frontend/src/pages/post/index.js
> +                <CommentSection />
space after CommentSection

2021-05-08 07:44 UTC, ryankroon00 approved these changes

2021-05-08 08:27 UTC, jerohero commented on backend/app/controllers/authorizationController.ts
> +
Too many newlines

2021-05-08 08:27 UTC, jerohero commented on backend/app/controllers/authorizationController.ts
> +            const validation = this.validateAccountRequest(account,username,password)
Space between parameters

2021-05-08 08:27 UTC, jerohero commented on frontend/src/components/comment/comment.scss
> +.comment {
Newline

2021-05-08 08:27 UTC, jerohero commented on frontend/src/components/commentEditor/index.js
> +        if (!this.maxLength) return false
return on newline

2021-05-08 08:27 UTC, jerohero commented on frontend/src/components/dialog/dialog.scss
> +		//animation: fade-in 0.2s;
Remove code if it's not used

2021-05-08 08:27 UTC, jerohero commented
- Replying to a comment while not logged in doesn't give any errors (just in console), is this fine for now? 
- The comment folding again after replying to a comment might not be fun either. Is this intended?

2021-05-08 08:30 UTC, jerohero commented
I can't find the right button to request changes so I'll just say it here 😅

2021-05-12 09:33 UTC, merged