206 follow system
AjobK/Athena pull request #222
Opened 2021-05-01 12:41 UTC by AjobK

closes #206 

**What is it supposed to do**
Users should be able to follow other users to see activity in the future

**How can we test your branch**
1. Go to a profile
2. Click the follow button
3. Check if the follow is still active when moving around in the app
4. Unfollow
5. Check if the unfollow is still active when moving around in the app
6. Check responsiveness
7. Etc.

**What broweser have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [x] Edge
- [ ] Safari

2021-05-01 13:23 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
>          <div className={styles.innerWrapper}>
spaces between curly braces (entire file)

2021-05-01 13:25 UTC, MrGooss requested changes

2021-05-01 13:25 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +    Axios.post(`${this.props.store.defaultData.backendUrl}/profile/follow/${username}`, {}, {withCredentials: true})
Spaces between curly braces

2021-05-02 06:23 UTC, ryankroon00 requested changes
Working great, just a few small fixes and it can be merged <3

2021-05-02 06:23 UTC, ryankroon00 commented on frontend/src/components/userBanner/index.js
> +      console.log(res.data.following)
Remove console.log

2021-05-02 06:23 UTC, ryankroon00 commented on backend/app/dao/profileDAO.ts
> +import { profile } from 'console'
Declared but never used

2021-05-02 06:23 UTC, ryankroon00 commented on backend/app/service/profileService.ts
> +        let profileFollowedBy: ProfileFollowedBy = new ProfileFollowedBy()
Is never reassigned so use const instead of let

2021-05-02 06:23 UTC, ryankroon00 commented on backend/app/service/profileService.ts
> +            let profileFollowedBy: ProfileFollowedBy = new ProfileFollowedBy()
Never reassigned please use const instead of let

2021-05-02 06:23 UTC, ryankroon00 commented on backend/app/service/profileService.ts
> +
Trailing spaces not allowed

2021-05-02 06:23 UTC, ryankroon00 commented on backend/app/service/profileService.ts
> +
Trailing spaces not allowed

2021-05-15 09:12 UTC, MrGooss requested changes

2021-05-15 09:12 UTC, MrGooss commented on backend/app/controllers/authorizationController.ts
> +export default AuthorizationController
New line at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/controllers/postController.ts
> +export default PostController
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/controllers/profileController.ts
> +export default ProfileController
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/dao/commentDAO.ts
> +export default CommentDAO
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/entity/comment.ts
> +export default Comment
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/authorizationRoutes.ts
> +export default AuthorizationRoutes
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/authorizationRoutes.ts
> +}
Newline

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/commentRoutes.ts
> +export default CommentRoutes
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/postRoutes.ts
> +}
Newline

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/postRoutes.ts
> +export default PostRoutes
Newline at end of file

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/profileRoutes.ts
> +}
Newline

2021-05-15 09:12 UTC, MrGooss commented on backend/app/routes/profileRoutes.ts
> +export default ProfileRoutes
Newline at end of file

2021-05-15 09:24 UTC, merged