207 storing images
AjobK/Athena pull request #223
Opened 2021-05-01 13:42 UTC by ryankroon00

closes #223, #215 #211 

 **What is it supposed to do**
You should be able to upload an image
You should be able to crop an image
You should be able to update an image
You shouldn't be able to upload any other file then  a .png, .jpg

 **How can we test your branch**
- reset the database
- register a user
- a default image should be displayed on the profile
- click the image
- crop the image
- click save
- now the profile picture should change
- logout
- refresh
- profile picture should be the same
- register a new user, and it should have the default picture

 **What browser have been checked**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [ ] Edge
- [ ] Safari

2021-05-01 15:06 UTC, AjobK commented
Please add labels etc. to PR.

Also change the way you use 'closes'. You should reference an issue to close as follows:

`closes #1 `

2021-05-15 12:44 UTC, MrGooss requested changes

2021-05-15 12:44 UTC, MrGooss commented on backend/app/controller/authorizationController.ts
> +export default AuthorizationController
Newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/controller/authorizationController.ts
> +            const validation = this.validateAccountRequest(account,username,password)
spaces after comma

2021-05-15 12:44 UTC, MrGooss commented on backend/app/controller/profileController.ts
> +            const profile = await this.dao.getProfileByUsername( req.decoded.username )
remove spaces between parentheses

2021-05-15 12:44 UTC, MrGooss commented on backend/app/controller/profileController.ts
> +        if ( attachment )
remove spaces between parentheses

2021-05-15 12:44 UTC, MrGooss commented on backend/app/controller/profileController.ts
>          newProfile.experience = 0
Newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/dao/attachmentDAO.ts
> +    public async saveAttachment(attatchment: Attachment): Promise<Attachment> {
Attatchment should be attachment

2021-05-15 12:44 UTC, MrGooss commented on backend/app/dao/attachmentDAO.ts
> +        const repository = await DatabaseConnector.getRepository('Attachment')
Attatchment should be attachment

2021-05-15 12:44 UTC, MrGooss commented on backend/app/dao/attachmentDAO.ts
> +        const createdAttachment = await repository.save(attatchment)
Attatchment should be attachment

2021-05-15 12:44 UTC, MrGooss commented on backend/app/dao/attachmentDAO.ts
> +    public async getAttachment(id: number): Promise<Attachment> {
Attatchment should be attachment

2021-05-15 12:44 UTC, MrGooss commented on backend/app/dao/profileDAO.ts
> +
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/entity/attachment.ts
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/interfaces/RoutesBase.ts
> +export default RoutesBase
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/routes/postController.ts
> +export default PostController
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/routes/postRoutes.ts
>  export default PostRoutes
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/routes/profileRoutes.ts
>  export default ProfileRoutes
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on backend/app/seeds/attachmentSeeder.ts
> +}
newline end of file

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +                {withCredentials: true, 'content-type': 'multipart/form-data'})
Spaces between curly braces

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +            <div className={styles.avatarUpload}>
Spaces between curly braces, entire file

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +        const fd = new FormData()
bundle variable declarations

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +            })
return between if

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +        const ctx = canvas.getContext('2d');
move ctx to variable declarations

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +            this.setState({ croppedAvatar });
semicolons, entire file

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +            );
enter underneath const

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +        <div className={styles.innerWrapper}>
spaces between curly braces

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +        <div className={styles.background} style={{ backgroundImage: `url(${user.banner})` }} />
spaces between curly braces

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/pages/profile/index.js
> +          <UserBanner user={user} owner={isOwner && profile.loggedIn} />
spaces between curly braces

2021-05-15 12:44 UTC, MrGooss commented on frontend/src/pages/profile/index.js
>            <ProfileInfo user={user} loggedIn={profile.loggedIn}/>
spaces between curly braces

2021-05-15 12:56 UTC, AjobK requested changes
Please see review 😄

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +                profileAttachment.path = location
enter above and under

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +                const storedAttachment = await this.attachmentDAO.saveAttachment(profileAttachment)
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +                await this.dao.saveProfile(profile)
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if ( !profile ) return res.status(404).json({ 'message': 'User not found' })
why spaces inside if

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if ( attachment )
why spaces inside if

2021-05-15 12:56 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if (isUsernamNotValid || isEmailNotValid || isPasswordNotStrong ) {
Space at end of if out of place (After isPasswordNotStrong)

2021-05-15 12:56 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +    }
enter below

2021-05-15 12:56 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +        return createdAttachment
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +export default attachmentDAO
newline

2021-05-15 12:56 UTC, AjobK commented on backend/app/dao/profileDAO.ts
> +import Attachment from '../entity/attachment';
semicolons

2021-05-15 12:56 UTC, AjobK commented on backend/app/dao/profileDAO.ts
> +        return !profile.avatar_attachment ? null : profile.avatar_attachment
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/interfaces/RoutesBase.ts
> +export default RoutesBase
newline

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +            if (posts.length == 0 ) {
enter above. Please use posts.length <= 0 instead of == 0 for ensurance

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +                return res.status(200).json({ 'message': 'You`ve reached the last post' })
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +        return res.status(200).json(message)
enter above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +        }
enter below

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +            await this.dao.createPost(newPost)
newline above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +            return res.status(200).json({ 'message': 'Post liked!' })
newline above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +    // TODO Move to another file?
Is this still required?

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +                return await this.profileDAO.getProfileByUsername(decodedToken.username)
newline above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/postController.ts
> +        return null
newline above

2021-05-15 12:56 UTC, AjobK commented on backend/app/routes/profileRoutes.ts
> +    constructor(){
space between () and { of constructor

2021-05-15 12:56 UTC, AjobK commented on backend/app/seeds/attachmentSeeder.ts
> +}
newline

2021-05-15 12:56 UTC, AjobK commented on backend/app/serverConstructor.ts
> +        this.app.use(express.static(__dirname + '/public'));
semicolon

2021-05-15 12:56 UTC, AjobK commented on backend/app/util/fileService.ts
> +
??? why this space

2021-05-15 12:56 UTC, AjobK commented on backend/app/util/fileService.ts
> +        return upload
Why not just return the multerfunc

2021-05-15 12:56 UTC, AjobK commented on backend/app/util/fileService.ts
> +        return upload
Using memory for no reason. Not even more readable really 😞

2021-05-15 12:56 UTC, AjobK commented on backend/app/util/fileService.ts
> +        return !(ext !== '.png' && ext !== '.jpg' && ext !== '.gif' && ext !== '.jpeg')
Why not use

`ext = ['.png', '.jpg', '.gif', '.jpeg']`

`extensions.indexOf(ext) != -1`

 instead of this

2021-05-15 12:56 UTC, AjobK commented on backend/app/util/fileService.ts
> +        await pipeline(file.stream, fs.createWriteStream(newPath))
newline above and under

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/avatarUpload/index.js
> +        const fileType = img.match(/[^:/]\w+(?=;|,)/)[0];
Remove all semicolons

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/avatarUpload/index.js
> +        const ctx = canvas.getContext('2d');
move ctx up to line 55

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/avatarUpload/index.js
> +            })
strange indentation

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/avatarUpload/index.js
> +        fd.append('file', avatar)
Move fd one line up and add newline under fd before append

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +            <span className={styles.levelMobile}>{ user.level || ''}</span>
space after '' in { user.level || ''}

2021-05-15 12:56 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +
remove whiteline

2021-05-15 12:56 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +          <UserBanner user={user} owner={isOwner && profile.loggedIn} />
strange indentation?

2021-05-22 08:50 UTC, MrGooss requested changes

2021-05-22 08:50 UTC, MrGooss commented on backend/app/controller/authorizationController.ts
> +
Remove return

2021-05-22 08:50 UTC, MrGooss commented on backend/app/controller/postController.ts
> +        const userLiked = !!(await this.dao.findLikeByPostAndProfile(foundPost, profile || null))
Maybe store the data that gets returned with findLikeByPostAndProfile() in a variable, it might be used later.

2021-05-22 08:50 UTC, MrGooss commented on frontend/src/components/avatarUpload/index.js
> +                resolve(new File([blob], "avatar",{ type: "image/png" }))
Space after comma

2021-05-22 08:50 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +                  <Icon iconName={'Pen'} />
Spaces between curly braces

2021-05-22 08:50 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +                <span className={`${styles.pictureEdit} ${this.state.draggingOver ? styles.pictureDraggingOver : ''}`}>
Spaces between curly braces

2021-05-22 08:50 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +                      style={{ backgroundImage: `url(${user.picture})` }}
Spaces between curly braces

2021-05-22 09:16 UTC, MrGooss submitted a review, later dismissed
LGTM

2021-05-22 09:21 UTC, AjobK requested changes
fix pls

2021-05-22 09:21 UTC, AjobK commented on backend/app/controller/postController.ts
> +                return res.status(200).json({ 'message': 'You`ve reached the last post' })
newline above

2021-05-22 09:21 UTC, AjobK commented on backend/app/controller/postController.ts
> +            posts = await this.dao.getPosts(String(req.query.page), amount)
newline under

2021-05-22 09:21 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +        return attachment
newline above

2021-05-22 09:25 UTC, AjobK approved these changes
heel mooi ja ja

2021-05-22 09:26 UTC, MrGooss approved these changes
LGTM

2021-05-22 09:27 UTC, merged