220 profile banner attachment
AjobK/Athena pull request #232
Opened 2021-06-04 11:38 UTC by jerohero

closes #220 

 **What is it supposed to do**
Allows users to update their banners by cropping a given image to the required format.

 **How can we test your branch**
Navigate to your profile while logged in. Click on the banner (a floating action button should pop up as well). Try out some images. Maybe try out some images with odd sizes (such as very wide or tall images) as well if you have those. Try to crop it and save it. It should be updated immediately, and this banner should be shown again when you refresh te page.

Merging develop with this branch caused a lot of merge conflicts (hence the rather long delay), so it may be possible I destroyed some other functionalities that I did not notice. The functionalities that caused trouble in the merge conflicts are updating profile avatars and following users. So maybe try to see if it still works (works for me though).

 **What broweser have been checked**
- [x] Chrome
- [X] Firefox
- [x] Opera
- [X] Edge
- [ ] Safari

2021-06-12 08:38 UTC, AjobK requested changes
Changes based on viewed code

2021-06-12 08:38 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if ( attachments.banner )
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if (type === AVATAR) {
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        // Create type dependent variables
remove

2021-06-12 08:38 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        if (type === AVATAR)
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +        return await repository.findOne({where: {id: 1}})
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/dao/attachmentDAO.ts
> +        return await repository.findOne({where: {id: 2}})
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/dao/profileDAO.ts
> +        return {
newline above

2021-06-12 08:38 UTC, AjobK commented on backend/app/util/fileService.ts
> +        return 'profile/' + type + '/' + year + '/' + month + '/' + day + '/' + name
newline above

2021-06-12 08:38 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +        }
Why not

```
let crop = {
    unit: '%',
    width: 100,
    aspect: 1
}

if (props.inputType === this.BANNER) {
    crop.aspect = 16/9
}
```

2021-06-12 08:38 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +        }
Option 1 (Better)
```suggestion
        const { inputType } = this.props
        let address = this.props.store.defaultData.backendUrl + '/profile/'
        
        if (inputType === this.BANNER) {
            address += 'banner'
        } else if (inputType === this.AVATAR) {
            address += 'picture'
        }
```

Would probably have been better to just use this.BANNER of this.AVATAR which would result in the following:

Option 2 (I think this is even better)
```suggestion
        const { inputType } = this.props
        let address = this.props.store.defaultData.backendUrl + '/profile/' + inputType
```

2021-06-12 08:38 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +                if (err.response.status === 401) {
newline above

2021-06-12 08:38 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +            {withCredentials: true, 'content-type': 'multipart/form-data'})
```suggestion
            {
                'withCredentials': true,
                'content-type': 'multipart/form-data'
            }
        )
```

2021-06-12 08:38 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +  onBannerDragLeave = () => {
newline above

2021-06-19 09:22 UTC, AjobK requested changes
Automatically create folder on saving banner or avatar. Avatar doesnt work either...

2021-06-19 09:26 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/122637868-3207cd80-d0f1-11eb-814e-f98cf820e1ce.png)

Close popup when clicking outside of it. Scrolls when holding inside the white bars on mobile?

2021-07-09 16:57 UTC, jerohero commented
Can't get updating avatars and banners to work anymore. Even in develop it suddenly seems to be broken and I have no idea why. The frontend is properly sending the file formdata, yet the backend doesn't recognize it.
![image](https://user-images.githubusercontent.com/14930277/125112459-77635d80-e0e7-11eb-9c73-14b627ceb090.png)
Req.file is null and the middleware causes a crash:
![image](https://user-images.githubusercontent.com/14930277/125112103-0623aa80-e0e7-11eb-8f70-7922284c0a9f.png)
This isn't my code, so maybe @ryankroon00 can take a look at it?

2021-07-09 20:16 UTC, AjobK commented
@jerohero We will discuss this at tomorrows meeting since we're working until atleast 15:00 anyway

2021-07-10 11:48 UTC, AjobK requested changes

2021-07-10 11:48 UTC, AjobK commented on backend/app/controller/profileController.ts
> +        console.log(attachments)
```suggestion
```

2021-07-10 11:56 UTC, AjobK commented
@jerohero 

Check merge conflicts

2021-07-17 13:06 UTC, AjobK requested changes
Minor things and then merge!

2021-07-17 13:06 UTC, AjobK commented on .gitignore
> +!backend/app/public/profile/avatar/.gitkeep
newline

2021-07-17 13:06 UTC, AjobK commented on backend/app/public/profile/avatar/.gitkeep
> +this file exists so the empty avatar folder gets pushed
newline

2021-07-17 13:06 UTC, AjobK commented on backend/app/public/profile/banner/.gitkeep
> +this file exists so the empty banner folder gets pushed
newline

2021-07-17 13:06 UTC, AjobK commented on backend/app/public/profile/avatar/.gitkeep
> +this file exists so the empty avatar folder gets pushed
```suggestion
This file exists so the empty avatar folder gets pushed.
```

2021-07-17 13:06 UTC, AjobK commented on backend/app/public/profile/banner/.gitkeep
> +this file exists so the empty banner folder gets pushed
```suggestion
This file exists so the empty banner folder gets pushed.
```

2021-07-17 13:06 UTC, AjobK commented on backend/app/utils/fileService.ts
> +    // Types: banner & avatar
More of a question;

Is this comment necessary?

2021-07-17 13:12 UTC, AjobK requested changes

2021-07-17 13:12 UTC, AjobK commented on .gitignore
> +!backend/app/public/profile/avatar/.gitkeep
```suggestion
!backend/app/public/profile/avatar/.gitkeep

```

2021-07-17 13:12 UTC, AjobK commented on backend/app/utils/fileService.ts
> +    // Types: banner & avatar
```suggestion
```

2021-07-17 13:13 UTC, AjobK approved these changes

2021-07-17 13:14 UTC, ryankroon00 approved these changes

2021-07-17 13:14 UTC, merged