217 admin role
AjobK/Athena pull request #236
Opened 2021-07-04 10:57 UTC by ryankroon00

closes #217 

 **What is it supposed to do**
I've refactored the seeder and added seeders for the permissions and roles and created a middleware for the backend.

 **How can we test your branch**
You can test the branch by running npm run reset, it should create 4 accounts with 4 different roles, 1 default attachment, all the defined permissions and roles and a profile for each account.

 **What browser have been checked**
- [x] Chrome
- [ ] Firefox
- [ ] Opera
- [ ] Internet Explorer
- [ ] Edge
- [ ] Safari

2021-07-09 12:54 UTC, MrGooss requested changes

2021-07-09 12:54 UTC, MrGooss commented on backend/app/controllers/roleController.ts
> +//import Role from '../entity/role'
remove comment?

2021-07-09 12:54 UTC, MrGooss commented on backend/app/daos/permissionDAO.ts
> +export default PermissionDAO
Newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/daos/rolePermissionDAO.ts
> +export default RolePermissionDAO
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/entities/rolePermission.ts
> +export default RolePermission
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/factories/permissionFactory.ts
> +})
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/middlewares/hasPermission.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/mainSeeder.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/seeders/accountSeeder.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/seeders/attachmentSeeder.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/seeders/permissionSeeder.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/seeders/rolePermissionSeeder.ts
> +}
newline end of file

2021-07-09 12:54 UTC, MrGooss commented on backend/app/seeder/seeders/roleSeeder.ts
> +}
newline end of file

2021-07-09 20:26 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/125132473-a5a36600-e104-11eb-82cf-4f2271e9a7fb.png)

`npm run reset` does not seem to do it for me..? No new accounts created

2021-07-10 09:48 UTC, AjobK requested changes
Please see comments

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/hasPermission.ts
> +            if(permission.permission.name == requiredPermissionName) {
```suggestion
            if (permission.permission.name == requiredPermissionName) {
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/hasPermission.ts
> +        }
```suggestion
        
        if (!hasPermission) {
            return res.status(401).json({ 'error': 'You don\'t have the right permisions' })
        }
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/isAuth.ts
> +    try{
```suggestion
    try {
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/seeder/seeders/permissionSeeder.ts
> +        permissions.push(userPermission)
```suggestion
        const userPermission = await factory(Permission)({ name: permissionsArray[i] }).create()
        
        permissions.push(userPermission)
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        return roles
```suggestion
        
        return roles
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        return role
```suggestion
        
        return role
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        return await this.getRoleById(role.role_id)
```suggestion
        
        return await this.getRoleById(role.role_id)
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/rolePermissionDAO.ts
> +        return rolePermissions
```suggestion
        
        return rolePermissions
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/factories/permissionFactory.ts
> +    return permission
```suggestion
    
    return permission
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/factories/rolePermissionFactory.ts
> +    return rolePermissionFake
```suggestion
    
    return rolePermissionFake
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/hasPermission.ts
> +        permissionList.forEach(permission => {
```suggestion
        const permissionList = await rolePermissionDAO.getRolePermissionsByRole(req.decoded.role)
        let hasPermission = false
      
        permissionList.forEach(permission => {
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/hasPermission.ts
> +        if (!hasPermission) {
```suggestion
       
        if (!hasPermission) {
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/seeder/seeders/rolePermissionSeeder.ts
> +        await factory(RolePermission)({ role: role, permission: permissionsArray[i] }).create()
```suggestion
        await factory(RolePermission)({
            role: role,
            permission: permissionsArray[i]
        }).create()
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/seeder/mainSeeder.ts
> +        const modPermisionsObjects = (await permissionSeeder(this.permissionsModerators, factory)).concat(userPermissionsObjects)
```suggestion
        const modPermisionsObjects = (await permissionSeeder(
            this.permissionsModerators,
            factory
        )).concat(userPermissionsObjects)
```

Do this for all of them please. That way we won't have to purchase a monitor of 1080 x 8000000

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/attachmentDAO.ts
> +import Attachment from '../entities/attachment';
```suggestion
import Attachment from '../entities/attachment'
```

Remove semicolons

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        const repository = await DatabaseConnector.getRepository('Role');
```suggestion
        const repository = await DatabaseConnector.getRepository('Role')
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        const repository = await DatabaseConnector.getRepository('Role');
```suggestion
        const repository = await DatabaseConnector.getRepository('Role')
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/daos/roleDAO.ts
> +        const repository = await DatabaseConnector.getRepository('Account');
```suggestion
        const repository = await DatabaseConnector.getRepository('Account')
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/factories/accountFactory.ts
> +import Profile from '../entities/profile';
```suggestion
import Profile from '../entities/profile'
```

2021-07-10 09:48 UTC, AjobK commented on backend/app/middlewares/isAuth.ts
> +    const { token } = req.cookies;
```suggestion
    const { token } = req.cookies
```

2021-07-10 11:46 UTC, AjobK requested changes

2021-07-10 11:46 UTC, AjobK commented on backend/app/daos/permissionDAO.ts
> +        return await repository.find({ where: { id: id } })
```suggestion
        const repository = await DatabaseConnector.getRepository('Permission')
        
        return await repository.find({ where: { id: id } })
```

2021-07-10 11:46 UTC, AjobK commented on backend/app/daos/permissionDAO.ts
> +        return permissionList
```suggestion
        const permissionList = repository.find()
        
        return permissionList
```

2021-07-10 11:46 UTC, AjobK commented on backend/ormconfig.example.json
> +}
newline

2021-07-10 11:55 UTC, merged