213 admin ban user
AjobK/Athena pull request #260
Opened 2021-07-23 14:24 UTC by ryankroon00

closes #213 

<br />

 **What is it supposed to do**  
Make admins able to ban an account until a certain time (banned_by which stores admin id and banned_until which stores a datetime)

In addition to its original requirements, I also added a filter to the getProfile function so that it only returns users that aren't banned, and when a user is banned his current posts are hidden, and he can't log in.

<br />

 **How can we test your branch**  
Explain how can test your branch as specifically as possible. Mention the page, button, etc. (For back-end route, function, etc.)
You can test the branch by following these steps:
- reset your database
- run the backend and frontend
- login as admin/ moderator or head-admin
- go to the user profile 
- when you hover over the users banner, a ban icon should be displayed
- if you click on the banner, a popup should be displayed 
- fill in the amount of days a user should be banned and the reason
- click save
- if you refresh the page, the user's account shouldn't be displayed
- try to login as the user you (you shouldn't be able to)
- check if there are any posts made by that user

<br />

**General checklist**
- [x] Tested happy flow.
- [x] Tested unhappy flow.
- [x] No unexpected exceptions.
- [x] No code with high complexity. (Big O)
- [x] EOF newline.
- [x] No floating comma's and spaces.
- [x] No unexpected/unhandled errors.
- [x] Lines no longer than 'guideline' in IDE.
- [x] Correct indentation.
- [x] No usage of legacy functionalities.
- [x] (JS) Curly braces on the sameline as reserved keywords *(`if () {` instead of `{` on line below)*
- [x] (JS) No double quotes.
- [x] (JS) Single newline above unique code structures and reserved keywords.
- [x] (JS) Variables bundled where possible.
- [x] (JS) No semi-colons except where they have a functional necessity, such as for-loops.

<br />

**If relevant, front-end checklist**
- [x] Responsive. (Desktop all the way to mobile 320px)
- [x] Using SCSS variables where relevant.
- [x] Relevant class names
- [x] No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**If relevant, back-end checklist**
- [x] No unhandled promise rejections.
- [x] Seeders still functional.
- [x] No primary-key violations.
- [x] Normalization, atleast [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] Used guards (middleware) where necessary and tested if route is guarded.

<br />

**If relevant, test these browsers**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [ ] Edge
- [ ] Safari
 
---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select atleast two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

2021-07-28 08:23 UTC, MrGooss requested changes
Well done, some changes requested

2021-07-28 08:23 UTC, MrGooss commented on backend/app/controllers/adminController.ts
> +        const admin = await this.accountDao.getAccountByUsername(req.decoded.username)
Do you check whether the user or admin are found? Might come in handy to avoid nullpointers

2021-07-28 08:23 UTC, MrGooss commented on backend/app/controllers/authorizationController.ts
> +            const role = await this.roleDAO.getRoleByUser(profile.display_name)
Might want to null check role

2021-07-28 08:23 UTC, MrGooss commented on backend/app/controllers/profileController.ts
> +                            bannedDateobject.getMinutes()
Duplicate code found in AuthorizationController, extract to service or utility

2021-07-28 08:23 UTC, MrGooss commented on frontend/src/components/banUser/index.js
> +    saveBan (e) {
e is not a descriptive name, please make the argument readable

2021-08-01 08:04 UTC, MrGooss requested changes

2021-08-01 08:04 UTC, MrGooss commented on backend/app/utils/banService.ts
> +export default BanService;
newline end of file

2021-08-01 08:53 UTC, AjobK requested changes
Some minor things, code visually

2021-08-01 08:53 UTC, AjobK commented on backend/app/controllers/adminController.ts
> +        if (existingBan) return res.status(400).json({ 'error': ['The user is already banned'] })
`(JS) Single newline above unique code structures and reserved keywords.`

2021-08-01 08:53 UTC, AjobK commented on backend/app/controllers/adminController.ts
> +        if (isNaN(banTime)) return res.status(400).json({ 'error': ['Invalid data'] })
`(JS) Single newline above unique code structures and reserved keywords.`

2021-08-01 08:53 UTC, AjobK commented on backend/app/controllers/adminController.ts
> +        this.hidePosts(posts)
```suggestion
        const createdBan = await this.banService.banUser(user, admin, reason, req.connection.remoteAddress, banTime)
        const userProfile = await this.profileDAO.getProfileByUsername(user.user_name)
        const posts = await this.postDAO.getOwnedPosts(userProfile)
        
        this.hidePosts(posts)
```

2021-08-01 08:53 UTC, AjobK commented on backend/app/controllers/adminController.ts
> +        this.hidePosts(posts)
`(JS) Variables bundled where possible.`

2021-08-01 08:53 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +        }
```suggestion
        if (ban) return res.status(403).json(ban)
```

2021-08-01 08:53 UTC, AjobK commented on backend/app/routes/adminRoutes.ts
> +        this.initRoutes()
```suggestion
        this.adminController = new AdminController()
        
        this.initRoutes()
```

2021-08-01 08:53 UTC, AjobK commented on backend/app/utils/banService.ts
> +                            bannedDateobject.getMinutes()
```suggestion
            const date = `
                ${ bannedDateobject.getDate() }-
                ${ bannedDateobject.getMonth() }-
                ${ bannedDateobject.getFullYear() } 
                ${ bannedDateobject.getHours() }:
                ${ bannedDateobject.getMinutes()}
```

Something like this works too I think. Don't just merge, please test first.

2021-08-01 08:53 UTC, AjobK commented on frontend/src/components/banUser/index.js
> +            this.setState({ error: error })
```suggestion
            const { error } = err.response.data
            
            this.setState({ error: error })
```

2021-08-01 09:17 UTC, ryankroon00 commented on backend/app/utils/banService.ts
> +                            bannedDateobject.getMinutes()
Het werkte niet op deze manier en heb het een soortvan toegepast maar ik denk niet dat het beter is

2021-08-01 09:28 UTC, AjobK commented
PREVIEW BUTTON  MISSING ON LOGIN FORM

2021-08-01 09:39 UTC, AjobK requested changes
These comments

2021-08-01 09:39 UTC, AjobK commented on backend/app/controllers/adminController.ts
> +        if( !username || !days || !reason ) return res.status(400).json({ 'error': ['Invalid data'] })
```suggestion
        const { username, days, reason } = req.body
        
        if (!username || !days || !reason) return res.status(400).json({ 'error': ['Invalid data'] })
```

2021-08-01 09:39 UTC, AjobK commented on backend/app/controllers/authorizationController.ts
> +                })
Please remove those extra added spaces

2021-08-01 09:39 UTC, AjobK commented on backend/app/utils/banService.ts
> +            return { error: ['Account banned up to: ' + date] }
```suggestion
            return { errors: [`Account banned until ${date}.`] }
```

2021-08-01 09:39 UTC, AjobK commented on backend/app/utils/banService.ts
> +        ban.staff_account = admin
```suggestion
        ban.user = user
        ban.staff = admin
```

2021-08-01 09:39 UTC, AjobK commented on frontend/src/components/formInput/index.js
> +          isPassword = type == "password"
Please check the form. Clearly states usage of single-quotes

```suggestion
          isPassword = type == 'password'
```

2021-08-01 09:39 UTC, AjobK commented on frontend/src/components/formInput/index.js
> +          <input id={id} className={styles.input} type={type} data-tip data-for={toolTipId} data-event='focus' data-event-off='blur' autoComplete={''} />
```suggestion
          <input id={id} className={ styles.input } type={ type } data-tip data-for={ toolTipId } data-event='focus' data-event-off='blur' />
```

2021-08-01 09:39 UTC, AjobK commented on frontend/src/components/banUser/index.js
> +                                <FormInput errors={this.state.error} name={"Reason"} callBack={this.callBack} className={[styles.formGroup]} type="text"></FormInput>
```suggestion
                                <FormInput errors={ this.state.error } name={ 'Days' } callBack={ this.callBack } className={[ styles.formGroup ]} type='number'></FormInput>
                                <FormInput errors={ this.state.error } name={ 'Reason' } callBack={ this.callBack } className={[ styles.formGroup ]} type='text'></FormInput>
```

2021-08-01 09:42 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/127766478-58b7f732-2f0b-4943-8c57-5f63497be32e.png)

Able to get ban popup as new user by clicking on banner

2021-08-01 09:42 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/127766498-c1227933-c048-4cf9-9862-35845ec5a843.png)

Please limit so only 0 days or more is possible

2021-08-01 09:43 UTC, AjobK commented
Able to actually ban users, even without priviliges

2021-08-01 09:51 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/127766734-735ba9e0-587c-4af7-bdc1-119b66c821b2.png)

Please make consistent use of date(s). Here you see a date string and unix timestamp, which should be interchangable but isn't

2021-08-01 10:21 UTC, AjobK commented
Please remove hidden_at flag for posts to prevent update anomalies (3NF). To only display posts that are not made by a banner user, make use of joins and check if 'banned_at' unix is in the past or null.

However, the whole concept of NOT displaying posts of banner users will be moved to another issue.

2021-08-08 12:42 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/128632326-92b67858-0de1-41b1-872d-f3e4b9b1797d.png)

Lol?

2021-08-08 12:43 UTC, AjobK commented
When I login I instantly get a 400 bad requests, but green checkmarks are shown above fields? Always getting 400 bad request whatever I do.

2021-08-08 12:44 UTC, AjobK commented
Also, when you say login with admin please tell us the password and username

2021-08-08 12:46 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/128632423-a6374318-d8fd-45ad-94bc-68bcc4b38939.png)

Can't click the 'view' icon

2021-08-08 13:43 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/128634024-5e91d693-3aa2-4849-8e6b-6bac4d9ef5a4.png)

Still doesnt work for users that already exist even though I entered the wrong password

2021-08-08 13:43 UTC, AjobK requested changes
Check comment

2021-08-15 15:12 UTC, AjobK approved these changes
Looks good. Great work! 👍

2021-08-15 15:12 UTC, merged