261 post views
AjobK/Athena pull request #263
Opened 2021-07-25 10:48 UTC by MrGooss

closes #261 

<br />

 **What is it supposed to do**  
Add a view to the database when a post is visited (IP restricted) and display the amount of views on the post's page.

<br />

 **How can we test your branch**  
You can test the branch by opening a post, because the view is IP restricted you'll only be able to add one view unless you use a VPN or change your IP. You could also change the ip address of the existing records in the database.

<br />

**General checklist**
- [x] Tested happy flow.
- [x] Tested unhappy flow.
- [x] No unexpected exceptions.
- [x] No code with high complexity. (Big O)
- [x] EOF newline.
- [x] No floating comma's and spaces.
- [x] No unexpected/unhandled errors.
- [x] Lines no longer than 'guideline' in IDE.
- [x] Correct indentation.
- [x] No usage of legacy functionalities.
- [x] (JS) Curly braces on the sameline as reserved keywords *(`if () {` instead of `{` on line below)*
- [x] (JS) No double quotes.
- [x] (JS) Single newline above unique code structures and reserved keywords.
- [x] (JS) Variables bundled where possible.
- [x] (JS) No semi-colons except where they have a functional necessity, such as for-loops.

<br />

**If relevant, front-end checklist**
- [x] Responsive. (Desktop all the way to mobile 320px)
- [x] Using SCSS variables where relevant.
- [x] Relevant class names
- [x] No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**If relevant, back-end checklist**
- [x] No unhandled promise rejections.
- [x] Seeders still functional.
- [x] No primary-key violations.
- [x] Normalization, atleast [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] Used guards (middleware) where necessary and tested if route is guarded.

<br />

**If relevant, test these browsers**
- [x] Chrome
- [x] Firefox
- [x] Opera
- [x] Edge
- [ ] Safari

2021-08-01 08:25 UTC, AjobK commented
New entries in post views are listed with IP ':1', which is localhost. This happens on a port-forwarded version too, concluding that the PR is not ready for development yet.

Please fill in the PR form.

2021-08-25 19:38 UTC, MrGooss commented
Issue is active again, tested on port forward, all seems fine

2021-08-29 11:05 UTC, AjobK requested changes
See comments

2021-08-29 11:05 UTC, AjobK commented on backend/app/utils/networkService.ts
> +        const ip = req.ip || req.socket.remoteAddress;
```suggestion
        const ip = req.ip || req.socket.remoteAddress

```

2021-08-29 11:05 UTC, AjobK commented on frontend/src/pages/post/index.js
> +        if(!this.state.isOwner) {
```suggestion
        if (!this.state.isOwner) {
```

2021-08-29 11:05 UTC, AjobK commented on frontend/src/pages/post/index.js
> +            Axios.post(`api/post/view`, payload)
```suggestion

            Axios.post(`api/post/view`, payload)
```

2021-08-29 11:05 UTC, AjobK commented on backend/app/controllers/postController.ts
>          const profile = await this.fetchProfile(req)
```suggestion
        const foundLikes = await this.dao.getPostLikesById(foundPost.id)
        const postLikesAmount = foundLikes ? foundLikes.length : 0
        const profile = await this.fetchProfile(req)
```

2021-08-29 11:05 UTC, AjobK commented on backend/app/controllers/postController.ts
> +        }
```suggestion
        if (!foundPost) {
            return res.status(404).json({ 'message': 'Post not found' })
        }
```

2021-08-29 11:05 UTC, AjobK commented on backend/app/controllers/postController.ts
> +        }
```suggestion
        if (!foundPost) {
            return res.status(404).json({ 'message': 'Post not found' })
        }
```

2021-08-29 11:05 UTC, AjobK commented on backend/app/daos/postDAO.ts
> +        const viewCount = await repository.count({ where: { post: post } })
```suggestion
        const repository = await DatabaseConnector.getRepository(this.postViewRepository)
        const viewCount = await repository.count({ where: { post: post } })
```

2021-08-29 11:05 UTC, AjobK commented on frontend/src/components/postViews/index.js
> +        const path = window.location.pathname.split('/').filter(i => i != '').pop()
Not necessarily something you NEED to do now, but since we a similar piece of code in multiple places we might want to add a util function for this.

2021-08-29 11:05 UTC, AjobK commented on frontend/src/components/postViews/index.js
> +                    { unitFormatterUtil.getNumberSuffix(this.state.views)  } { this.state.views === 1 ? 'view' : 'views' }
```suggestion
                    { `${ unitFormatterUtil.getNumberSuffix(this.state.views) } view${ this.state.views > 1 ? 's' : '' }` }
```

2021-08-29 11:05 UTC, AjobK commented on frontend/src/components/postViews/index.js
> +                    { unitFormatterUtil.getNumberSuffix(this.state.views)  } { this.state.views === 1 ? 'view' : 'views' }
Test this before implementing

2021-08-29 11:05 UTC, AjobK commented on frontend/src/pages/post/index.js
> +
Are these useless tabs? Not sure if just a newline or useless spacing.

2021-08-29 11:05 UTC, AjobK commented on backend/app/app.ts
> +require('dotenv').config()
Is this necessary? Genuine question, since I thought we could access the .env without this line of code.

2021-08-29 11:09 UTC, AjobK commented on frontend/src/pages/post/index.js
> +            Axios.post(`api/post/view`, payload)
Newline

2021-08-29 12:20 UTC, MrGooss commented on backend/app/app.ts
> +require('dotenv').config()
This is necessary

2021-08-29 12:22 UTC, AjobK requested changes
minor newline thing

2021-08-29 12:22 UTC, AjobK commented on frontend/src/util/urlUtil.js
> +        return path
```suggestion
        const path = window.location.pathname.split('/')
        
        return path
```

2021-08-29 12:22 UTC, AjobK commented on frontend/src/util/urlUtil.js
> +        return path
```suggestion
        const path = this.getPathArguments().filter(i => i != '').pop()
        
        return path
```

2021-08-29 12:25 UTC, AjobK approved these changes
proud 👍

2021-08-29 12:26 UTC, merged