212 delete post
AjobK/Athena pull request #278
Opened 2021-08-22 13:26 UTC by ryankroon00

closes #212 

<br />

 **What is it supposed to do**  
This pull request makes sure a mod, admin and head admin are able to archive posts and if a post is archived it isn't displayed.

<br />

 **How can we test your branch**  
- go to the backend folder
- run "npm run reset"
- login as admin 
- go to a post
- click on the postbanner
- click confirm
- the post shouldn't be displayed on the homepage, profile page

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No floating comma's and spaces.
- [x] g. No unexpected/unhandled errors.
- [ ] h. Lines no longer than 'guideline' in IDE.
- [x] i. Correct indentation.
- [x] j. No usage of legacy functionalities.
- [x] k. (JS) Curly braces on the sameline as reserved keywords *(`if () {` instead of `{` on line below)*
- [x] l. (JS) No double quotes.
- [x] m. (JS) Single newline above unique code structures and reserved keywords.
- [x] n. (JS) Variables bundled where possible.
- [x] o. (JS) No semi-colons except where they have a functional necessity, such as for-loops.
- [x] p. (JS) No code that is meant exclusively for development, such as console.logs for data preview.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, atleast [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select atleast two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2021-08-29 08:28 UTC, MrGooss commented
Fix conflicts please bro, it's been a week....

2021-08-29 10:07 UTC, MrGooss requested changes
Found some issues regarding spacing, also some issues belonging to another branch

2021-08-29 10:07 UTC, MrGooss commented on backend/app/controllers/profileController.ts
> +            error = error + 'atleast 8 characters'
space between "atleast" it's "at least"

2021-08-29 10:07 UTC, MrGooss commented on backend/app/controllers/profileController.ts
> +            const warningNumber = 'use a number'
"use at least one number"

2021-08-29 10:07 UTC, MrGooss commented on backend/app/controllers/profileController.ts
>      private checkPasswordStrength(password: string): string {
Validator is not showing on user registration, this should be fixed in another branch

2021-08-29 10:07 UTC, MrGooss commented on frontend/src/components/postBanner/index.js
> +                    <h3 className={styles.role}>{ author.title || ''}</h3>
Spaces between curly braces on classnames

2021-08-29 10:07 UTC, MrGooss commented on frontend/src/pages/post/index.js
> +                <PostBanner archivePost={this.archivePost.bind(this)} author={author} isOwner={isOwner} />
Spaces between curly braces

2021-08-29 12:08 UTC, AjobK commented
Please capitalize button words. ('Confirm' instead of 'confirm')

![image](https://user-images.githubusercontent.com/35965716/131249813-848fe23e-ecc6-480b-89ca-1ab6ab7e1bfc.png)

2021-08-29 12:10 UTC, AjobK commented
Able to click on delete post when logged out? When logged in on an account that shouldn't be able to delete posts I can't see it though which is good.

![image](https://user-images.githubusercontent.com/35965716/131249860-d5c0a0da-23ba-46d7-ae64-b689fca2ddba.png)

2021-08-29 12:13 UTC, AjobK commented
Post removal should be stored in a post remove database table. Store staff_id, post_id and archived_at

2021-08-29 12:14 UTC, AjobK requested changes
Check previous comments and this minor thing

2021-08-29 12:14 UTC, AjobK commented on backend/app/controllers/postController.ts
> +        if (!newPost) return res.status(500).json({ error: 'Could not archive post' })
```suggestion
        
        if (!newPost) return res.status(500).json({ error: 'Could not archive post' })
```

Newline

2021-09-05 09:42 UTC, AjobK approved these changes
Looks good. We will fix the 'Not loaded' to '404' in a different branch.

2021-09-05 09:42 UTC, merged