269 followers to friends
AjobK/Athena pull request #314
Opened 2021-09-19 11:33 UTC by jerohero

closes #269 

<br />

 **What is it supposed to do**  
The follow/unfollow button changes to follow back/unfriend if that user follows the logged in user. A _followsYou_ field was added to the return value of the GET profile route.
![image](https://user-images.githubusercontent.com/14930277/133925917-258e0c0e-eed4-46e0-a728-eb42aed2748e.png)

<br />

 **How can we test your branch**  
Log in with two different accounts and let them follow each other to see if the text in the follow button changes properly.

<br />

 **Additional notes**  
n/a

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

2021-09-26 10:49 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/134804640-85230d11-cd0b-4eb0-81c9-4d7712ded21b.png)

When a user follows me and I go to their profile it doesn't show me 'Follow Back' instead of 'Follow'

After refresh it seems to work though? Strange...

**Reproduce**
1. Register a new user
2. Follow another user
3. Logout and login on another user without refreshing
4. Go to followers by clicking on '1 followers' text and go to their profile
5. It says 'Follow' instead of 'Follow back'
6. Refresh, now it should say the correct thing

2021-09-26 10:52 UTC, AjobK requested changes
Check comment above

2021-10-03 09:36 UTC, AjobK requested changes
## Issue 1

![image](https://user-images.githubusercontent.com/35965716/135748081-ab68d009-68f1-4473-b2c8-820d98b4782b.png)

When I click on follow it doesn't update it right away in the button?

Only when I refresh...

## Issue 2

![image](https://user-images.githubusercontent.com/35965716/135748139-3449fa07-c59c-4623-93f0-114beb36ab04.png)

Mobile buttons don't work well. Very unclear in which state of following you are with a person.

2021-10-09 14:04 UTC, jerohero commented
> ## Issue 2
> ![image](https://user-images.githubusercontent.com/35965716/135748139-3449fa07-c59c-4623-93f0-114beb36ab04.png)
> 
> Mobile buttons don't work well. Very unclear in which state of following you are with a person.

I didn't make this. Do you mean it doesn't represent the friend state with another user (follow back, unfriend) or the general state of following (follow, unfollow)?

2021-10-21 18:25 UTC, ryankroon00 submitted a review, later dismissed

2021-10-23 15:50 UTC, jerohero commented
> ## Issue 2 
> Mobile buttons don't work well. Very unclear in which state of following you are with a person.

![image](https://user-images.githubusercontent.com/14930277/138563024-c09c8bbb-2362-47d3-98ee-7475f916a464.png)
![image](https://user-images.githubusercontent.com/14930277/138563028-aeeade28-3b29-4f05-b138-16528e2bdaf5.png)

I replaced them with some icons from Font Awesome. I don't think these icons fit very well (considering the unfollow button when the user is not followed back is a check icon, but is an icon with a slash when the user does follow back), but I was unable to find anything better.

2021-10-24 09:53 UTC, AjobK requested changes

2021-10-24 09:53 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +  getFollowIcon = () => {
```suggestion
  getFollowIconName = () => {
```

2021-10-24 09:53 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +              <Icon iconName={ this.getFollowIcon() } classNames={ styles.replyIcon } />
```suggestion
              <Icon iconName={ this.getFollowIconName() } classNames={ styles.replyIcon } />
```

2021-10-24 09:53 UTC, AjobK commented on frontend/src/components/userBanner/index.js
>    }
banUser is literally nothing more than a state change?

2021-10-24 09:53 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +    }
```suggestion
    const { username, following, followsYou } = this.props
    
    if (username !== username) {
      this.setState({
        following,
        followsYou
      })
    }
```

Deconstruct and if I'm correct, state doesn't have to specify var name if variable is same as state property name

2021-10-24 09:53 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +      const ownProfile: ProfileFollowedBy = new ProfileFollowedBy()
I don't understand this var name..? Maybe something more specific?

2021-10-24 11:18 UTC, jerohero commented on frontend/src/components/userBanner/index.js
>    }
Didn't make this, just felt cute and changed the function into an arrow function. It's replaced now.

2021-10-24 11:31 UTC, jerohero commented on backend/app/controllers/profileController.ts
> +      const ownProfile: ProfileFollowedBy = new ProfileFollowedBy()
It's the profile the user is visiting and the own profile of the user. I changed _visitingprofile_ into _targetProfile_. Maybe that's more specific?

2021-10-24 11:48 UTC, ryankroon00 submitted a review, later dismissed

2021-10-24 11:48 UTC, ryankroon00 approved these changes

2021-10-24 12:23 UTC, AjobK approved these changes

2021-10-24 12:23 UTC, merged