313 post banner attachment
AjobK/Athena pull request #323
Opened 2021-10-02 01:14 UTC by jerohero

closes #313 

<br />

 **What is it supposed to do**  
This branch adds functionality for post thumbnails/banners. This is the image the user sees with the post on places like the homepage, and on the top of the page when the user visits the page of a post. The owner of a post can now change the banner by uploading an image to the server. The user is able to do this through the application by selecting or dropping an image. This image can be cropped.

![image](https://user-images.githubusercontent.com/14930277/135699436-b45c9340-a278-4170-9e0b-735a736df080.png)

<br />

 **How can we test your branch**  
Go to one of your posts or create a new one. Hovering over the background thumbnail should show _edit banner_, which can be clicked. This should not happen when you're not logged in as the owner of the post. Only .png or .jpg files should be allowed. Max file size should be 4000 KB. You should only be able to save an image after cropping it. The new image should appear immediately as the new thumbnail, and this should still be there after refreshing. The new image should also be on the homepage (as a thumbnail for the post). Try changing the thumbnail again. Updating the image should delete the old one (from the file system and Attachment table).

<br />

 **Additional notes**  
**You'll have to add some folders to make this branch work**. In _backend/app/public_, add _post/thumbnail_.

Wasn't sure whether I should completely delete the thumbnail after a post is archived or not, so at the moment the thumbnail attachments don't get removed when the post is archived.

When fetching multiple posts, a separate DAO call is executed after for every single post in order to fetch their banner attachments. Maybe there's a more efficient way to do this?
![image](https://user-images.githubusercontent.com/14930277/135699411-eb2d23ca-6c17-47b1-89bb-d4be4fe380dd.png)

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

2021-10-03 09:20 UTC, AjobK requested changes
## Issue 1
When there is no /post/thumbnail folder you can't add images to that folder. You have to make a .gitkeep file so folders like this always stay. I've made it for you this time, so you can just `git pull`.

## Issue 2
When I'm trying to save a thumbnail on a post without a title or content, it gives me the following error:

![image](https://user-images.githubusercontent.com/35965716/135747473-bf696ea5-4a1a-41cc-80e7-f7c5dddbab3d.png)

## Issue 3
Always create a placeholder banner instead of this grey blob. When you save a post without a banner it gets a default banner, which is good. Why not show this banner on post creation too?

![image](https://user-images.githubusercontent.com/35965716/135747565-47612225-5f11-400b-8ac1-bf04b832f894.png)

2021-10-10 09:59 UTC, AjobK requested changes
Pure code comments. Gonna test now.

2021-10-10 09:59 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +            {UnitFormatterUtil.getNumberSuffix(likesAmount)} {likesAmount === 1 ? 'like' : 'likes'}
```suggestion
            { UnitFormatterUtil.getNumberSuffix(likesAmount)} {likesAmount === 1 ? 'like' : 'likes' }
```

2021-10-10 09:59 UTC, AjobK commented on frontend/src/components/postBanner/index.js
> +          )}
```suggestion
          ) }
```

2021-10-10 09:59 UTC, AjobK commented on frontend/src/components/postBanner/index.js
> +    const reader = new FileReader()
```suggestion
    const reader = new FileReader()
    
```

2021-10-10 09:59 UTC, AjobK commented on frontend/src/components/postViews/index.js
>                      ${this.state.views === 1 ? 'view' : 'views'}`}
Strangely formatted code? Maybe use something like this:

```suggestion
          { `
              ${ UnitFormatterUtil.getNumberSuffix(this.state.views) } 
              ${ this.state.views === 1 ? 'view' : 'views' }
          `}
```

2021-10-10 11:08 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/136693013-b51916ba-05d4-4b8a-980a-1bc63f54315a.png)

Error when creating empty post and then editing it

2021-10-10 11:34 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/136693764-7332330a-4e00-4079-ab83-553fe9e8d631.png)

Able to change post banner of a post that I'm not an author of (through insomnia/postman).

2021-10-21 18:36 UTC, ryankroon00 requested changes

2021-10-21 18:36 UTC, ryankroon00 commented on backend/app/controllers/postController.ts
> +import attachmentDAO from '../daos/attachmentDAO'
2 keer attachment dao, 1tje verwijderen

2021-10-21 18:36 UTC, ryankroon00 commented on frontend/src/components/cropper/index.js
> +  sendImageToDb = async (image) => {
You don't send it directly to the db so I would call this function something different

2021-10-21 18:36 UTC, ryankroon00 commented on frontend/src/components/userBanner/userBanner.scss
>  			width: 100%;
width: 100% twice

2021-10-21 18:36 UTC, ryankroon00 commented on frontend/src/pages/post/index.js
> +      this.updatePostDB()
I would remove db from the name

2021-10-22 18:02 UTC, AjobK commented
Has merge conflicts

2021-10-23 14:53 UTC, jerohero commented
> ![image](https://user-images.githubusercontent.com/35965716/136693764-7332330a-4e00-4079-ab83-553fe9e8d631.png)
> 
> Able to change post banner of a post that I'm not an author of (through insomnia/postman).

@AjobK I assume you were logged in as an administrator with post permissions. Should I disable administrators having access to posts?

2021-10-23 15:45 UTC, AjobK commented
For now, yes. We will make a seperate issue in which this will be implemented in a more specific approach.

Admins shouldnt be able to change a posts banner, but remove it. Changing it would alter a users post intentions.

2021-10-24 10:51 UTC, AjobK requested changes
Check comment above

2021-10-24 13:25 UTC, AjobK approved these changes

2021-10-24 16:48 UTC, ryankroon00 approved these changes

2021-10-24 16:48 UTC, merged