312 pin comment
AjobK/Athena pull request #328
Opened 2021-10-03 12:34 UTC by danielordaan

closes #312 

<br />

 **What is it supposed to do** 
The owner of posts can pin multiple comments. Comments can also be liked (once). Comments are then ordered, first by whether they are pinned, and then on their amount of likes.
![image](https://user-images.githubusercontent.com/57443004/135755511-c24e38c9-0d90-4130-90ce-1da65782ba23.png)

<br />

 **How can we test your branch**  
1. Create comments on one account
2. Like one of them and see them ordered on refresh
3. Create a post and comment on this post
4. Pin some posts and repeat steps 1 and 2

To test unhappy flow, try pinning posts as a non-post-owner, or try liking comments twice

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [ ] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2021-10-03 13:01 UTC, AjobK commented
Gave feedback on styling in call

2021-10-03 13:32 UTC, AjobK commented
https://stackoverflow.com/a/44770035

Good to think about things like this, especially when exposing the front-end to comment IDs such as numbers. We might want to use UUIDs. What do you think?

2021-10-03 13:48 UTC, AjobK requested changes
See comments. Overall good work!

Haven't tested it locally yet.

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    }
This should probably be put before line 32... I expect a null-pointer exception when no post is found yet you're trying to access the profile.id

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    }
This should probably be put before line 51... I expect a null-pointer exception when no post is found yet you're trying to access the profile.id

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    else return res.status(204).json([])
```suggestion
    if (foundCommentLikes)
        return res.status(200).json(foundCommentLikes)
    else
        return res.status(204).json([])
```

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    else return res.status(204).json([])
Also, shouldn't foundCommentLikes already be an empty array if there are no commentlikes? Meaning you can get rid of this entire if statement and just keep `return res.status(200).json(foundCommentLikes)`

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    return res.status(200).json(profileHasLikedComment)
Why not just do something like this?

```suggestion
    foundCommentLikes.forEach((commentLike: any) => {
      if (commentLike.profile.id === profile.id)
          return res.status(200).json(profileHasLikedComment)
    })

    return false
```

This way you don't loop an unnecessary amount of times

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +  public getProfileLikedComment = async (req: Request | any, res: Response): Promise<Response> => {
Shouldn't this function name be changed? I don't think it really reflects what is happening inside here. You're just checking if a profile has a liked comment, right?

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    if (!comment || !profile) return res.status(404).json({ message: 'Invalid profile or comment id given' })
Invalid would result in something like 422. I would change the  message to something like `Unable to find profile or comment`. You may think differently, I don't know.

2021-10-03 13:48 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +    await this.dao.createCommentLike(comment, profile)
What if this fails? You'll still send a 200 I think, or no message at all.

I would use `.then` or atleast catch it in some way.

2021-10-03 13:48 UTC, AjobK commented on backend/app/daos/commentDAO.ts
> +      if ((await repository.find({ profile: profile.id, comment: comment.id })).length > 0) {
I would definitely recommend splitting this into a variable and if statement, or something like that. All your code is very readable, and this is a lot less comfortably readable.

2021-10-03 13:48 UTC, AjobK commented on backend/app/daos/commentDAO.ts
> +      comment.is_pinned = true
```suggestion
      const comment = await repository.findOne(id)
      comment.is_pinned = true
```

These are better bundled together since they are very directly related to one another.

2021-10-03 13:48 UTC, AjobK commented on backend/app/daos/commentDAO.ts
> +      comment.is_pinned = false
```suggestion
      const comment = await repository.findOne(id)
      comment.is_pinned = false
```

These are better bundled together since they are very directly related to one another.

2021-10-03 13:48 UTC, AjobK commented on frontend/src/components/comment/index.js
> +            length: this.state.likes.length - 1
I wouldn't do it this way. If someone were to delete their like at the same time somewhere else (production) you would just do -1 instead of -2. I would check the length again by requesting data from the db.

2021-10-03 13:48 UTC, AjobK commented on frontend/src/components/comment/index.js
> +            length: this.state.likes.length - 1
In other words, this is a bit hardcoded

2021-10-03 13:48 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                          styles.comment__hasNotLikedComment}
Indent this better (if possible) so it's very clear that this is one thing. When I glanced over this it looked like three different classes were used instead of 1.

2021-10-03 13:48 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +    const profileHasLikedCommentUrl = 'http://localhost:8000/api/comment/likes/profileHasLiked/'
Use the defaultData store to get the API route

2021-10-03 13:48 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +    }))
Use better names than `a` and `b`

2021-10-03 13:48 UTC, danielordaan commented
> https://stackoverflow.com/a/44770035
> 
> Good to think about things like this, especially when exposing the front-end to comment IDs such as numbers. We might want to use UUIDs. What do you think?

I think using UUIDs is a good idea. I think it would be best if we used both a UUID (the public id) and a regular number (the private id). With this, we can get the best of both worlds, secure public id's, and no database performance hit

2021-10-04 14:05 UTC, danielordaan commented on frontend/src/components/comment/index.js
> +            length: this.state.likes.length - 1
I don't really agree with this one. The point of the actions here is to give the user an indication that their (dis)like has come through. This is achieved. Getting the comment every time a user (dis)likes a comment is also not very efficient. In the end, I don't think users are interested in getting the new amount of likes when they press the like button. Instagram for instance also does not do this in this fashion.

2021-10-04 14:11 UTC, danielordaan commented
Pushed new changes based on feedback

2021-10-06 18:22 UTC, AjobK commented on frontend/src/components/comment/index.js
> +            length: this.state.likes.length - 1
Fair point. I realize now that when someone removes their like on a post and in the meantime 5 other people liked it, the amount of likes would increase when the user unlikes. Not really the behaviour we want. You have convinced me 😄!

2021-10-06 18:24 UTC, AjobK commented
> > https://stackoverflow.com/a/44770035
> > Good to think about things like this, especially when exposing the front-end to comment IDs such as numbers. We might want to use UUIDs. What do you think?
> 
> I think using UUIDs is a good idea. I think it would be best if we used both a UUID (the public id) and a regular number (the private id). With this, we can get the best of both worlds, secure public id's, and no database performance hit

I wonder if using numeric ID's is even necessary. What is the added value of using them? You have to expose an id to the front-end one way or another. Might as well just use UUIDs, which at the very least can't be used for business statistics and scrapers 🤷 

When I look at [this page](https://www.mysqltutorial.org/mysql-uuid/) it seems like using UUIDs instead of numeric IDs mainly has benefits. So, do you think we should completely go from numeric ID's to UUID's too? Either way we should discuss this at the next meeting.

2021-10-08 20:45 UTC, AjobK requested changes
Still found a few things that should be different. Noted a few of them. Main take-aways:

- Check your code for WET code that could be DRY.
- Make sure that you don't overload the server, so make (if possible) singular requests that give information for a specific case.
- Make code more atomic (functions, components) instead of directly putting things in render.

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/commentSection/index.js
>          })
This is a lot of load for the server to handle. Why not just send most of this information in one request?

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                        ` }
Indentation seems off

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                { profile.loggedIn && this.displayReplyButton() }
Why not put the like and pin buttons in a function/component like here?

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                    { this.state.isPinned && !this.state.isPostOwner || !profile.loggedIn && this.state.isPinned && (
```suggestion
                    { this.state.isPinned && (!this.state.isPostOwner || !profile.loggedIn) && (
```

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                    { this.state.isPinned && !this.state.isPostOwner || !profile.loggedIn && this.state.isPinned && (
Doesn't something like this make a lot more sense to do? ILG1 stuff

2021-10-08 20:45 UTC, AjobK commented on frontend/src/components/comment/index.js
> +                        <>
Useless fragment brackets `<>`

2021-10-08 21:01 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/136624120-224d7dba-552c-4b8d-a7dc-904b027e2ee6.png)

Why can't an author like someones comment?

![image](https://user-images.githubusercontent.com/35965716/136624370-2a8094de-70e1-4ba5-9d44-edde18124f22.png)

EDIT: Seems like people can only like their own comment... That's a little sad 😢

2021-10-08 21:02 UTC, AjobK commented
**Bug display and/or description**
![image](https://user-images.githubusercontent.com/35965716/136623573-df49e335-f5a1-4ed5-b350-79e468baa1f2.png)

Order of comments is messed up?

**Reproduce**
- [ ] Add a comment
- [ ] Add another comment
- [ ] After waiting for 2 minutes (That's what I did) add another comment
- [ ] Comment order is messed up!

2021-10-24 09:36 UTC, danielordaan commented
> **Bug display and/or description** ![image](https://user-images.githubusercontent.com/35965716/136623573-df49e335-f5a1-4ed5-b350-79e468baa1f2.png)
> 
> Order of comments is messed up?
> 
> **Reproduce**
> 
> * [ ]  Add a comment
> * [ ]  Add another comment
> * [ ]  After waiting for 2 minutes (That's what I did) add another comment
> * [ ]  Comment order is messed up!

Fixed :)

2021-10-31 10:12 UTC, AjobK commented
Everything looks great! Just minimize the amount of requests as stated in the comment below. If you do let me know and we'll merge the PR to develop.

> Still found a few things that should be different. Noted a few of them. Main take-aways:
> 
> * Check your code for WET code that could be DRY.
> * Make sure that you don't overload the server, so make (if possible) singular requests that give information for a specific case.
> * Make code more atomic (functions, components) instead of directly putting things in render.

2021-11-07 14:30 UTC, AjobK submitted a review, later dismissed
Minor thing, which I will fix for you

2021-11-07 14:30 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +          console.log(response.data)
???

2021-11-07 14:31 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/140649329-87eb9284-336b-41f7-8444-5051d1bce79b.png)

When I reply to pinned comment I get this..?

EDIT: Seems like replying doesn't work anymore at all. Does still work in develop though.

2021-11-10 22:43 UTC, AjobK requested changes
Generally looks good so I assume this is my last RC (Request Changes)

1. In your branch the comments are ordered from oldest to newest. This is wrong, since the newest comments should be on top. Of course the general order should be 'Pinned > Likes > Recency'

So pinned is above unpinned, more likes is higher on the list and then you sort on recency, with the most recent comments being on top.

A nice to have would be that your own comments on a post are always on top (So if I comment on your post and I view your post I see my comments on top). If this is too much scope-creep please make it so that I see my own comment on top after sending it, but when you refresh it can be somewhere else.

2. I don't think this is your responsibility so this will likely be a separate issue: Authors should be able to delete all comments on their posts. Not just their own comments.

2021-11-11 11:30 UTC, danielordaan commented
> Generally looks good so I assume this is my last RC (Request Changes)
> 
> 1. In your branch the comments are ordered from oldest to newest. This is wrong, since the newest comments should be on top. Of course the general order should be 'Pinned > Likes > Recency'
> 
> So pinned is above unpinned, more likes is higher on the list and then you sort on recency, with the most recent comments being on top.
> 
> A nice to have would be that your own comments on a post are always on top (So if I comment on your post and I view your post I see my comments on top). If this is too much scope-creep please make it so that I see my own comment on top after sending it, but when you refresh it can be somewhere else.
> 
> 2. I don't think this is your responsibility so this will likely be a separate issue: Authors should be able to delete all comments on their posts. Not just their own comments.
> 
> 

Question about the nice to have: what about replies? Should your own reply also always be the first reply?

2021-11-11 16:40 UTC, AjobK commented
> > Generally looks good so I assume this is my last RC (Request Changes)
> > 
> > 1. In your branch the comments are ordered from oldest to newest. This is wrong, since the newest comments should be on top. Of course the general order should be 'Pinned > Likes > Recency'
> > 
> > So pinned is above unpinned, more likes is higher on the list and then you sort on recency, with the most recent comments being on top.
> > A nice to have would be that your own comments on a post are always on top (So if I comment on your post and I view your post I see my comments on top). If this is too much scope-creep please make it so that I see my own comment on top after sending it, but when you refresh it can be somewhere else.
> > 
> > 1. I don't think this is your responsibility so this will likely be a separate issue: Authors should be able to delete all comments on their posts. Not just their own comments.
> 
> Question about the nice to have: what about replies? Should your own reply also always be the first reply?

No, since that would mess up the 'thread' flow. Preferably you would automatically scroll down to your reply after sending your reply, but that might be out of scope. Besides, in #225 you can see that there's a bug with unfolding the replies after sending one.

2021-11-11 20:03 UTC, AjobK requested changes
Check comments

2021-11-11 20:03 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +      })))
Let's be honest. This doesn't look very nice...

I would put this in a separate function.

2021-11-11 20:03 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +      }).concat(pinnedComments.sort((firstComparedPinnedComment, secondComparedPinnedComment) => {
A piece like this could be

```suggestion
      userComments.sort((currComment, nextComment) => (
        new Date(currComment.created_at) - new Date(nextComment.created_at)
      ))
```

No need to do getTime and a ternary and also a curly brace with a return instead of a direct return arrow func.

2021-11-11 20:03 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +      })))
Also, instead of concat I would do something like this

```js
[
  ...sortedArr1,
  ...sortedArr2,
  ...sortedArr3
]
```

2021-11-11 20:03 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +      }).concat(pinnedComments.sort((firstComparedPinnedComment, secondComparedPinnedComment) => {
You can take this and put it in a function called something like `sortByDatetime` which you can used for all comments. Would look like this:

```js
sortArrayByDatetime = (arrToSort, dateProperty='created_at') => (
  arrToSort.sort((currItem, nextItem) => (
    new Date(currItem[dateProperty]) - new Date(nextItem[dateProperty])
  ))
)
```

Just a concept. Then you could just do something like
```js
[
  ...sortArrayByDatetime(userComments),
  ...sortArrayByDatetime(pinnedComments),
  ...sortArrayByDatetime(unpinnedComments)
]
```

A lot cleaner, don't you think?

2021-11-11 20:06 UTC, AjobK commented on frontend/src/components/commentSection/index.js
> +      }).concat(pinnedComments.sort((firstComparedPinnedComment, secondComparedPinnedComment) => {
You might even get away with not doing `new Date()` at all for the sorting

Just `currItem[dateProperty] - nextItem[dateProperty]`. Pretty sure that works too but test it

2021-11-11 23:01 UTC, AjobK commented
1. Pressing pin shouldn't show a pointer or do anything when you're not the author. Now it gives an error in the console and shows a pointer.

![image](https://user-images.githubusercontent.com/35965716/141380771-bb0dfd14-b5db-41ac-bb44-bdeba5c34c1b.png)

![image](https://user-images.githubusercontent.com/35965716/141380825-96cea5ac-3ee2-42f9-b55a-63040ec00726.png)


2. Order is still messed up... Even though I pinned and liked one of my comments (Logged in as 'User', who is also the author) I stilld don't get higher on the list. The priority should be `UserComments` (✔️) > `Pinned` (❌) > `Likes` (❌) > `Recency` (🤷)

Recency seems to work but has higher priority than we discussed in an earlier comment.

![image](https://user-images.githubusercontent.com/35965716/141380916-0488c391-32d0-4147-8e4d-1f126ffd9ccc.png)

---

If this feels like too much work with all these request changes let's discuss it on Sunday. Since we don't want you to get too hung op on a task I can take over, if that helps in any way. That way we can close this PR quickly and make sure that you get the time-off that you need.

2021-11-11 23:03 UTC, AjobK requested changes
See comments...

We might have to talk on Sunday, since for some reason bugs pop up with every new update. This isn't necessarily a big deal, but I'm worried that you may not get the time-off you need early enough at this pace. If it helps I can take over your task.

2021-11-12 08:38 UTC, danielordaan commented
> See comments...
> 
> We might have to talk on Sunday, since for some reason bugs pop up with every new update. This isn't necessarily a big deal, but I'm worried that you may not get the time-off you need early enough at this pace. If it helps I can take over your task.

Fixed

2021-11-12 12:34 UTC, AjobK approved these changes
Looks good, which means:

**MERGING** 😄

2021-11-12 12:35 UTC, merged