[HOTFIX] Post not loaded alternative to text
AjobK/Athena pull request #331
Opened 2021-10-03 14:11 UTC by AjobK

closes #281 

<br />

 **What is it supposed to do**  
Better loading of post instead of 'Not loaded' text. Added a loader icon when a post is loading. Also gives an error when post is not found instead of a permanent text indicating that something is loading.

<br />

 **How can we test your branch**  
Go to an invalid post URL like `/post/blahblah`. You should see a loader for a very short amount of time and then an error page indicating that the post does not exist.
<br />

 **Additional notes**  
None

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [ ] a. Chrome
- [ ] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2021-10-04 14:20 UTC, danielordaan requested changes
Tested, nice work! Some comments below

2021-10-04 14:20 UTC, danielordaan commented on backend/app/controllers/postController.ts
> +
I'd put this just under line 73 (just after you retrieve the potential post from the dao).

2021-10-04 14:20 UTC, danielordaan commented on frontend/src/pages/post/index.js
> +            title: e.response ? e.response.status : name,
I think renaming 'e' to 'error' makes the code more readable overall.

2021-10-04 14:20 UTC, danielordaan commented on frontend/src/pages/post/index.js
> +        { !this.props.new && <CommentSection isPostOwner={ this.state.isOwner } /> }
What is the purpose of adding isPostOwner to the comment section in your issue? I remember doing this in my own issue so I'm wondering what this is doing here

2021-10-04 14:44 UTC, AjobK commented on frontend/src/pages/post/index.js
> +        { !this.props.new && <CommentSection isPostOwner={ this.state.isOwner } /> }
You and me both, lol

2021-10-07 19:27 UTC, danielordaan approved these changes
Good work! Approved

2021-10-10 13:27 UTC, merged