279 unit tests
AjobK/Athena pull request #342
Opened 2021-10-24 08:42 UTC by ryankroon00

closes #279 

<br />

 **What is it supposed to do**  
The pr adds end point tests to the back end 

<br />

 **How can we test your branch**  
- go to the backend folder
- npm i
- npm run reset
- open a new terminal
- npm test

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [ ] a. Responsive. (Desktop all the way to mobile 320px)
- [ ] b. Using SCSS variables where relevant.
- [ ] c. Relevant class names
- [ ] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

2021-10-24 09:11 UTC, AjobK requested changes

2021-10-24 09:11 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Creating a user so we can ban him', (done) => {
it creating? 
![image](https://user-images.githubusercontent.com/35965716/138587535-888dfea1-c323-40b6-8fcd-e1d7f3e228a8.png)

Multiple places

2021-10-24 09:11 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Creating a user so we can ban him', (done) => {
Also, please make tests atomic (Complete test in one test instead of dependency on other tests).

And make the names as tests in a expectation form. Example: 'It should be able to ban a user'

2021-10-24 09:13 UTC, jerohero commented
Looks like mocha wasn't properly added to the package.json. I had to do _npm i mocha_ to be able to run the test.
![image](https://user-images.githubusercontent.com/14930277/138587757-95490e80-5990-47db-93dd-360dab3f0230.png)

2021-10-24 09:22 UTC, jerohero requested changes

2021-10-24 09:22 UTC, jerohero commented on backend/app/utils/banService.ts
>      async banUser(user: Account, admin: Account, reason: string, adress: string, banTime: number): Promise<Ban> {
Not part of this specific PR, but adress should be address

2021-10-24 09:22 UTC, jerohero commented on backend/app/test/banTest.ts
> +        done()
Newline above? Especially since it does have a newline above in some other places.

2021-10-24 09:23 UTC, AjobK requested changes
Check comments

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/commentTest.ts
> +          for (let x = 0; x < res.body.length; x++) {
Better var name than x

2021-10-24 09:23 UTC, AjobK commented on backend/package.json
> +      "testcafe": "^1.16.0",
```suggestion
```

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +        }
```suggestion
        amountOfFollowers = res.status == 200 ? res.body.followers.length : 0
```

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +  let amountOfFollowers = 0
Why are these global across all tests?

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +  const agentUser = chai.request.agent('http://localhost:8000/api')
Shouldn't this be in a more global place for all tests?

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +import assert = require('assert')
why not `import ... from ...`

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +import assert = require('assert')
Isn't this ES6 already so you should be able to do that?

2021-10-24 09:23 UTC, AjobK commented on backend/app/routes/authorizationRoutes.ts
> +      this.authController = new AuthController()
```suggestion
      this.authController = new AuthController()
      
```

Newline under var assignment. Next line is a func call.

2021-10-24 09:23 UTC, AjobK commented on backend/app/daos/commentDAO.ts
> +      if (children) {
I know this works, but I think `children.length < 0` is more readable and less sensitive to other data types. If children is true it would still go in the code block.

2021-10-24 09:23 UTC, AjobK commented on backend/tsconfig.json
> +, "app/tests/likeTest"    ]
Strange formatting

2021-10-24 09:23 UTC, AjobK commented on backend/package.json
> +      "test": "ts-mocha  ./app/test/*.ts --timeout 10000000"
Why is the timeout so massive

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/profileTest.ts
> +  it('Checking if we can update the banner', ((done) => {
Why the extra `(` to the left of 'done' ?? See line 120. You don't do that there

2021-10-24 09:23 UTC, AjobK commented on backend/app/test/postTest.ts
> +        done()
Newline above, do this for all code.

Isn't your linter checking this code? Might be so.

2021-10-25 19:14 UTC, AjobK requested changes

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/userTest.ts
> +  it('Shouldn\'t register user because no capitol are present in the password', (done) => {
```suggestion
  it('Shouldn\'t register user because no uppercase characters are present in the password', (done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/userTest.ts
> +  it('Shouldn\'t register user because the user already exists', (done) => {
```suggestion
  it('Shouldn\'t register user that already exists', (done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/userTest.ts
> +  it('Shouln\'t login because username and password are incorrect', (done) => {
```suggestion
  it('Shouln\'t login with invalid username and password', (done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/userTest.ts
> +  it('Should login', (done) => {
```suggestion
  it('Should login with correct username and password', (done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/userTest.ts
> +describe('Testing the login/register', () => {
You test both so it's not login/register

```suggestion
describe('Testing the login and register', () => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/profileTest.ts
> +  it('Should retrieve role', ((done) => {
```suggestion
  it('Should retrieve user role', ((done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/profileTest.ts
> +  it('Should retrieve the current amount of followers', (done) => {
```suggestion
  it('Should return follower amount of user', (done) => {
```

Why retrieve instead of return?

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/profileTest.ts
> +          })
I wouldn't test these things with admin users, but with other users...

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/postTest.ts
> +      .put('/post/archive/' + post.path)
```suggestion
      .put(`/post/archive/${post.path}`)
```

This is a better string concatenation for these things I think. Should probably use this for the rest too.

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +            days: '35',
Why is days in string format?

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +  const userToLongBan = uuidv4()
```suggestion
  const shortBannedUser = uuidv4()
  const longBannedUser = uuidv4()
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Should long term ban a user as admin', (done) => {
```suggestion
  it('Should long ban a user as admin', (done) => {
```

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Should create a user so we can ban him', (done) => {
As we've discussed, make this seperate. No dependency among tests if this is not necessary. I think that it is not necessary in this case.

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Shouldn\'t long ban users as admin', (done) => {
```suggestion
  it('Shouldn\'t long ban user as moderator', (done) => {
```

Wrong test name

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +            days: '10',
Again, days in string?

2021-10-25 19:14 UTC, AjobK commented on backend/app/test/banTest.ts
> +  it('Souldn\'t ban a user as a user', (done) => {
```suggestion
  it('Souldn\'t ban a user as user', (done) => {
```

Consistency

2021-10-25 19:14 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    console.log(req.body)
begone

2021-10-25 19:14 UTC, AjobK commented on backend/app/daos/commentDAO.ts
> +      if (children) {
Also what is this doing in the tests branch?

2021-10-25 19:14 UTC, AjobK commented on backend/app/controllers/banController.ts
> +    return res.status(200).json({})
???

Why did you empty the return for this. And then you send an empty json. Either don't send json (and test if this doesn't break the front-end) or at least send a message with it.

Besides that, not sure what this is doing in the unit test branch

2021-10-25 19:14 UTC, AjobK commented
Also, fix merge conflicts please :-)

2021-10-31 13:28 UTC, ryankroon00 commented on backend/app/test/profileTest.ts
> +import assert = require('assert')
it errors if you do it that way: https://github.com/microsoft/TypeScript/issues/21535
This is also the way they do it in their examples https://www.npmjs.com/package/chai

2021-11-07 14:42 UTC, AjobK requested changes
As discussed wednesday a few things need to be fixed before this can be merged.

2021-11-14 14:10 UTC, AjobK submitted a review, later dismissed
Change 'test' command to 'tests' and then it's mergeable!

2021-11-16 18:15 UTC, AjobK approved these changes
Very nice. Good work and on to more exciting features as you requested 😄

2021-11-16 18:15 UTC, merged