298 profile card revamp
AjobK/Athena pull request #346
Opened 2021-11-09 13:10 UTC by MrGooss

closes #298 

<br />

 **What is it supposed to do**  
Change the banner and profile card on the profile page to align with the designs on Zeplin.io

<br />

 **How can we test your branch**  
Open the profile page and compare this with the designs on Zeplin. Try updating your avatar/banner by hovering over them and selecting new images. Try following someone/adding a post and see if the values at the profile card update correctly. Edit your bio and see if this saves correctly.

<br />

 **Additional notes**  
Things to keep in mind regarding the PR that don't fit in the previous two headings. 

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2021-11-09 13:18 UTC, MrGooss commented
Issue with the way posts are displayed over different browsers 
![image](https://user-images.githubusercontent.com/45096509/140931145-75370f05-c2a5-4c44-8e44-81fe5071530a.png)

2021-11-09 22:04 UTC, MrGooss commented
> Issue with the way posts are displayed over different browsers ![image](https://user-images.githubusercontent.com/45096509/140931145-75370f05-c2a5-4c44-8e44-81fe5071530a.png)

Fixed issue by giving wrapper a width and giving the profile content a 100% width

2021-11-10 22:44 UTC, AjobK commented
> > Issue with the way posts are displayed over different browsers ![image](https://user-images.githubusercontent.com/45096509/140931145-75370f05-c2a5-4c44-8e44-81fe5071530a.png)
> 
> Fixed issue by giving wrapper a width and giving the profile content a 100% width

TFW you request changes on your own work

![image](https://user-images.githubusercontent.com/35965716/141205853-2b302fbe-8ae5-4370-946e-2de927e8a878.png)

2021-11-10 23:03 UTC, AjobK requested changes
Please don't add random thumbnail png files

Also, check rest of comments

2021-11-10 23:03 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    //TODO: duplicate code, will export to single method once it's working correctly
What do you mean? I assume it works now so why not export it

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/button/index.js
> +          disabled || noPulse ? '' : styles.pulse,
if disabled is true you will get the class 'true' in the browser html. We don't want that.

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/button/index.js
> +          disabled || noPulse ? '' : styles.pulse,
```suggestion
          disabled || !noPulse? styles.pulse : '',
```

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/button/index.js
> +          disabled || noPulse ? '' : styles.pulse,
I vaguely remember this from ILG1

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +    /*eslint-disable */
I would appreciate a comment next to this line justifying this ignore

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +    }
I was gonna tell you that this code seems a bit WET.

... Then I realized I wrote this.

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/cropper/index.js
> +    }
Meaning: Leave it, it's fine

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileBanner/index.js
> +    if (input.target.files && input.target.files.length > 0) {
Might want to use optional chaining here to make sure you don't get an nullpointerexception. Also removes the necessity for the &&.

```suggestion
    if (input?.target?.files?.length > 0) {
```

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileBanner/index.js
> +    if (input.target.files && input.target.files.length > 0) {
Since I see that you use this multiple times I'd even say make something like this under line 27:

`const files = input?.target?.files`

If one of the properties does not exist files will be undefined

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileBanner/index.js
> +          { role != 'User' & !this.props.owner & this.props.store.profile.loggedIn ? (
Binary AND operators? Oof...

Use &&

& is not really the operator for this

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileCard/index.js
> +  }
Wut? Why this. This doesn't look too good.

I see no reason to just use document.body.style. We never do that and we shouldn't do this

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileCard/profileCard.scss
> +	margin-top: calc(-75px - #{$header-spacing}); // Subtract header-spacing due to padding on section wrapper
You could make a local variable for this file for the 75px (And add a - in front of the variable here) instead of the comment

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileCard/profileCard.scss
> +	}
```suggestion
	&Badge {
		vertical-align: middle;
		height: auto;
		margin-right: 5px;
		font-size: 28px;
		color: $primary;
	}
	
	&Username {
		text-align: center;
		color: $secondary;
	}
```

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileCard/profileCard.scss
> +	}
```suggestion
	&NameWrapper {
		display: flex;
		justify-content: center;
		font-size: $nr-md-fontsize;
		color: $primary;
	}
```

Which means you change the name of this class to `.profileInfoNameWrapper`

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/profileInfo/index.js
> +    const posts = this.props.posts
```suggestion
    const { user, posts } = this.props
```

2021-11-10 23:03 UTC, AjobK commented on frontend/src/components/userBanner/index.js
> +      following: this.props.user.following || false,
```suggestion
      following: !!this.props.user.following,
```

2021-11-10 23:03 UTC, AjobK commented on frontend/src/pages/profile/index.js
> +            </Section>
As requestes previously, please remove (preferably comment and add TODO for rework) the statistics since they are non-functional and confusing

2021-11-10 23:03 UTC, AjobK commented on frontend/src/styles/variables.scss
> +$textdark: #000000;
```suggestion
$text-dark: #000000;
```

2021-11-10 23:04 UTC, AjobK commented
Have not really tested your branch locally yet after your most recent updates (FYI)

2021-11-12 09:56 UTC, MrGooss commented on frontend/src/components/button/index.js
> +          disabled || noPulse ? '' : styles.pulse,
Your suggestion won't work as it will add style.pulse when the button is disabled

2021-11-12 10:09 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +      following: this.props.user.following || false,
UserBanner won't be used anymore, left it for reference

2021-11-12 10:09 UTC, MrGooss commented on frontend/src/components/userBanner/index.js
> +      following: this.props.user.following || false,
Will remove after a last check if all functionality has been copied correctly

2021-11-12 10:11 UTC, MrGooss commented on frontend/src/pages/profile/index.js
> +            </Section>
Removed

2021-11-12 10:12 UTC, MrGooss commented on frontend/src/styles/variables.scss
> +$textdark: #000000;
U sure bro? 😂 I'll fix

2021-11-16 19:03 UTC, AjobK requested changes
This minor thing. We will discuss the rest on discord.

2021-11-16 19:03 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    return receivedUsername
```suggestion
    if (!receivedUsername && decodedToken?.username) {
      receivedUsername = decodedToken.username
    }

    return receivedUsername || null
```

2021-11-16 19:03 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    return receivedUsername
Actually no wait. This can be made even simpler.

2021-11-16 19:05 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    return receivedUsername
```suggestion
    return receivedUsername || decodedToken?.username
```

If `receivedUsername` is falsy (Might want to decide whether to use ?? or || here), you go to `decodedToken?.username`. If decodedToken is null, this will also result in null. Meaning that you return null as you intended in your code.

2021-11-16 19:55 UTC, MrGooss commented
Reminder: followerCount is not updating directly after following someone, should be fixed before merge

2021-11-28 10:04 UTC, jerohero requested changes

2021-11-28 10:04 UTC, jerohero commented on backend/app/daos/profileDAO.ts
> +  public async getFollowingByProfileId(profileId: number): Promise<any> {
Promise return type should be ProfileFollowedBy[]

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileBanner/index.js
> +          { role != 'User' && !this.props.owner && this.props.store.profile.loggedIn && (
```suggestion
          { role !== 'User' && !this.props.owner && this.props.store.profile.loggedIn && (
```

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +    Axios.post(`${this.props.store.defaultData.backendUrl}/profile/follow/${username}`, {}, { withCredentials: true })
```suggestion
    Axios.post(`${ this.props.store.defaultData.backendUrl }/profile/follow/${ username }`, {}, { withCredentials: true })
```

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +    Axios.post(`${this.props.store.defaultData.backendUrl}/profile/follow/${username}`, {}, { withCredentials: true })
Exceeds vertical ruler (line is too long)

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +        console.log(err)
Console log

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +  }
I don't understand what this does. What roles do the dates play and what is the 500 for? Maybe use variables with relevant naming to give more context.

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +    const user = this.props.user
Deconstruct

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +                className={ `${styles.followButton} ${this.getFollowButtonClass()}` }
```suggestion
                className={  `${ styles.followButton } ${ this.getFollowButtonClass() }`  }
```

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileCard/index.js
> +                className={ `${styles.editButton} secondary` }
```suggestion
                className={  `${ styles.editButton } secondary`  }
```

2021-11-28 10:04 UTC, jerohero commented on frontend/src/components/profileInfo/index.js
> +          className={ `${styles.profileStatistic} ${followersStatisticClass}` }
```suggestion
      <div className={  `${ styles.profileStatistics }`  }>
        <div
          className={ `${ styles.profileStatistic } ${ followersStatisticClass }`  }
```

2021-11-28 10:09 UTC, jerohero commented
I assume the old UserBanner component can be yeeted now?

2021-12-05 09:57 UTC, MrGooss commented on frontend/src/components/profileCard/index.js
> +                className={ `${styles.editButton} secondary` }
Double spacing seems unnecessary

2021-12-05 11:10 UTC, ryankroon00 submitted a review, later dismissed

2021-12-05 12:20 UTC, sribadal submitted a review, later dismissed
Ziet er goed uit!

2021-12-05 12:23 UTC, jerohero submitted a review, later dismissed

2021-12-05 12:53 UTC, AjobK reviewed
Check comments. Also drag over image doesn't work properly for avatar?

2021-12-05 12:53 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +    })
```suggestion
    followingById.map((entry) => entry.profile)
```

2021-12-05 13:18 UTC, AjobK approved these changes

2021-12-05 13:19 UTC, sribadal approved these changes

2021-12-05 13:19 UTC, ryankroon00 approved these changes

2021-12-05 13:20 UTC, merged

2021-12-05 13:20 UTC, jerohero approved these changes
Look good

Sent from my Windows 10