246 hcaptcha
AjobK/Athena pull request #348
Opened 2021-11-13 19:16 UTC by jerohero

closes #246 

<br />

 **What is it supposed to do**  
Adds hCaptcha to verify humans who register and login. This is done through a puzzle that appears every single time. Users can't continue until they succeed.

![image](https://user-images.githubusercontent.com/14930277/141655348-75010f7f-55ab-4b12-b95f-78199bab96d6.png)

<br />

 **How can we test your branch**  
Unfortunately hCaptcha is a bit of a pain to test, as there are some things you need to do to get it working.

1. Set up the branch as you normally would
2. Modify the backend .env file by adding the following entries:
```
#CURRENT_APP_STATE=dev
CURRENT_APP_STATE=prod
HCAPTCHA_PROD_SECRET_KEY=0xeCC0EA91F78De070a80f3730318055C7e69807B2
HCAPTCHA_DEV_SECRET_KEY=0x0000000000000000000000000000000000000000
```
**NOTE**: When CURRENT_APP_STATE is set to _dev_, hCaptcha is essentially disabled (the captcha will send a valid token without requiring puzzles) so it doesn't hinder development. Set the value to _prod_ to activate it and test its functionality. So make sure it's set to _dev_ when you're not working on captcha!

3. Add a .env file to the frontend folder and add the following entries:
```
#CURRENT_APP_STATE=dev
CURRENT_APP_STATE=prod
HCAPTCHA_PROD_SITE_KEY=031482b3-54e1-4beb-a0d7-dce10eecfdbf
HCAPTCHA_DEV_SITE_KEY=10000000-ffff-ffff-ffff-000000000001
```
**NOTE**: Make sure to restart the React application after making changes to the frontend .env file.

4. Find and open your hosts file; https://docs.rackspace.com/support/how-to/modify-your-hosts-file
4. Add a reference to localhost by adding "_127.0.0.1 seaqull-test.com_" to the hosts file and save it.
5. Visit http://seaqull-test.com:8080/. The application should load and hCaptcha should work on the register and login page.

**FINAL NOTE**: Cookies don't seem to be working on a custom localhost domain. Meaning that functionality like logging out or staying logged in will probably stop working for you.

<br />

 **Additional notes**  
At the moment there's still some doubt about hCaptcha. The puzzle always appearing while logging in is annoying, and the puzzles are irritatingly difficult. At least for now it seems like a good solution until we can get reCAPTCHA working somehow.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

2021-11-14 10:50 UTC, ryankroon00 submitted a review, later dismissed

2021-11-14 13:07 UTC, AjobK requested changes
Check comments

2021-11-14 13:07 UTC, AjobK commented on frontend/src/stores/defaultData.js
> +    backendUrlBase: types.optional(types.string, 'http://localhost:8000'),
Why..?

2021-11-14 13:07 UTC, AjobK commented on backend/app/controllers/authorizationController.ts
> +import captchaService from '../utils/captchaService'
```suggestion
import CaptchaService from '../utils/captchaService'
```

2021-11-14 13:07 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +      errors.captcha = ['We could not confirm you are not a robot']
Why not use push? You already made an array on line 213 and this way you risk losing other pushed error strings.

2021-11-14 13:07 UTC, AjobK commented on frontend/src/components/registerPrompt/index.js
> +        const { username, email, password, captcha } = res.response.data.errors
Maybe use optional chaining, just to be sure

2021-11-14 13:07 UTC, AjobK commented on frontend/src/components/registerPrompt/index.js
> +    const generalError = this.state.generalError
```suggestion
    const { generalError } = this.state
```

2021-11-14 13:07 UTC, AjobK commented
Also cors url

2021-11-14 15:14 UTC, jerohero commented on frontend/src/stores/defaultData.js
> +    backendUrlBase: types.optional(types.string, 'http://localhost:8000'),
I'm glad you asked

I have no idea

2021-11-14 15:18 UTC, jerohero commented on backend/app/controllers/profileController.ts
> +      errors.captcha = ['We could not confirm you are not a robot']
Just did it the way it was for the other errors. I changed this + the other stuff.

2021-11-14 15:20 UTC, jerohero commented on frontend/src/components/registerPrompt/index.js
> +        const { username, email, password, captcha } = res.response.data.errors
Changed it to res.response?.data?.errors

2021-11-14 15:23 UTC, jerohero commented
> Also cors url

I removed it (like it used to be) as a custom localhost domain apparently isn't required yet.

2021-11-16 18:12 UTC, AjobK requested changes

2021-11-16 18:12 UTC, AjobK commented on backend/app/app.ts
> +        'http://seaqull-test.com:8080'],
```suggestion
      origin: [
        FRONTEND_URL,
        'http://localhost:8080',
        'http://localhost:3000',
        'http://localhost',
        'http://seaqull-test.com:8080'
      ],
```

This looks a bit better tbh

2021-11-16 18:12 UTC, AjobK commented on backend/app/utils/captchaService.ts
> +      params.append('secret', process.env.CURRENT_APP_STATE === 'dev'
As discussed last sunday this should use the NODE_ENV env attribute. This is a duplicate attribute. We already track if we're on a dev environment

2021-11-16 18:12 UTC, AjobK commented on backend/app/app.ts
> +        'http://seaqull-test.com:8080'],
Also, you should change the seaqull-test.com to seaqull or just remove it

2021-11-16 18:12 UTC, AjobK commented on frontend/src/stores/defaultData.js
> +    backendUrlBase: types.optional(types.string, 'http://localhost:8000'),
You marked this as resolved but it's not resolve. Please resolve it in code and don't use the 'Resolve convo' button since you might forget certain comments :-) Unless you already made the changes of course.

2021-11-16 18:12 UTC, AjobK commented on backend/app/utils/captchaService.ts
> +      return hCaptcha.data['success']
Why not just do

```suggestion
      return hCaptcha.data.success
```

2021-11-16 18:12 UTC, AjobK commented on backend/app/utils/captchaService.ts
> +export default captchaService
```suggestion
export default CaptchaService
```

2021-11-16 18:12 UTC, AjobK commented on backend/app/utils/captchaService.ts
> +class captchaService {
```suggestion
class CaptchaService {
```

2021-11-20 00:12 UTC, jerohero commented on frontend/src/stores/defaultData.js
> +    backendUrlBase: types.optional(types.string, 'http://localhost:8000'),
Looks like I forgot to push all the changes 🤦‍♂️

2021-11-20 01:23 UTC, jerohero commented
Env files changed

**Frontend**
```
HCAPTCHA_PROD_SITE_KEY=031482b3-54e1-4beb-a0d7-dce10eecfdbf
HCAPTCHA_DEV_SITE_KEY=10000000-ffff-ffff-ffff-000000000001
NODE_ENV=development
secure=false
```

**Backend**
```
JWT_SECRET=KGn]FCx0w~TI
JWT_EXPIRATION_TIME=600000
secure=false
HCAPTCHA_PROD_SECRET_KEY=0xeCC0EA91F78De070a80f3730318055C7e69807B2
HCAPTCHA_DEV_SECRET_KEY=0x0000000000000000000000000000000000000000
HCAPTCHA_TEST_TOKEN=10000000-aaaa-bbbb-cccc-000000000001
NODE_ENV=development
```

2021-11-21 12:56 UTC, AjobK requested changes

2021-11-21 12:56 UTC, AjobK commented on backend/app/utils/captchaService.ts
> +        : process.env.HCAPTCHA_PROD_SECRET_KEY)
Use deconstructor for the keys and extract the ternary to a variable please.

Then append that var.

2021-11-21 12:56 UTC, AjobK commented on frontend/src/components/loginPrompt/index.js
> +    this.props.store.notification.setContent(popUpData.messages.captchaError)
```suggestion
    const { notification } = this.props.store
    const { captchaError } = popUpData.messages

    notification.setContent(captchaError)
```

More readable and less chaining

2021-11-21 12:56 UTC, AjobK commented on frontend/src/components/loginPrompt/index.js
> +                : process.env.HCAPTCHA_PROD_SITE_KEY }
Same as said before in this PR

2021-11-21 12:56 UTC, AjobK commented on backend/app/app.ts
> +        'http://localhost'
Maybe there's a more uniform way of doing this? Might even want to extract the `http://localhost`

2021-11-21 12:56 UTC, AjobK commented on backend/app/controllers/authController.ts
> +          errors: ['We could not confirm you are not a robot']
Is this correct english? I might be wrong lmao

2021-11-21 12:56 UTC, AjobK commented on backend/app/controllers/profileController.ts
> +import captchaService from '../utils/captchaService'
```suggestion
import CaptchaService from '../utils/CaptchaService'
```

PascalCase

2021-11-21 14:22 UTC, jerohero commented on backend/app/app.ts
> +        'http://localhost'
![image](https://user-images.githubusercontent.com/14930277/142765638-db3d181b-e1f2-41cf-a219-db9f7e0cf495.png)
Updated

2021-11-21 14:24 UTC, jerohero commented on backend/app/controllers/authController.ts
> +          errors: ['We could not confirm you are not a robot']
I have gechange to the _We couldn't verify that you're not a robot._

2021-11-28 13:54 UTC, AjobK requested changes
**Captcha**
![image](https://user-images.githubusercontent.com/35965716/143770754-085f604d-8dcb-413a-80ac-052718bd416f.png)

**Result**
![image](https://user-images.githubusercontent.com/35965716/143770757-dc0e3ef3-d94b-483f-b75f-9780d4f44a58.png)

Doesn't seem to work? I have my .env enabled with 'development', which I shouldn't trigger a captcha or it should work.

2021-11-28 14:06 UTC, AjobK approved these changes

2021-11-28 14:07 UTC, merged