259 homepage infinite scrolling v2
AjobK/Athena pull request #352
Opened 2021-11-21 12:21 UTC by jerohero

closes #259 

<br />

 **What is it supposed to do**  
Fixes the issue from the previous infinite scrolling PR ( #275 ) where the previous post blocks wouldn't fill when loading more posts.

Current state: 
![image](https://user-images.githubusercontent.com/14930277/142760059-0d31d647-22c9-41a8-83e6-b3915e3b8047.png)

New state:
![image](https://user-images.githubusercontent.com/14930277/142760085-6fd4108f-41b8-429f-8711-02b87f50d9e2.png)

<br />

 **How can we test your branch**  
Try adding/removing posts and scroll down (home page) to see if post blocks get filled properly, and if there is no unwanted behavior like posts disappearing.

<br />

 **Additional notes**  
Since posts get fetched in pages of 6 posts, the pages won't end 'cleanly' on a fetch when one page doesn't give 6 posts (they will only get filled at the next fetch, when the user scrolls down):
![image](https://user-images.githubusercontent.com/14930277/142759746-17000f34-8a5d-4fba-8255-27dbd733d765.png)
If this is undesired I could fix this by simply fetching again when the fetch results don't contain 6 posts, so the user doesn't get to see it as much. I could also increase the page length to get the same result (which will most likely be done in the future anyway as fetching once every 6 posts can be expensive). Note that this only occurs once the end of the homepage is reached, which I assume won't happen often in production.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

2021-11-21 13:39 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/142764146-5d6403e0-0dfe-47ca-858c-81ada5da6b90.png)

Pagination doesn't seem to work well when changing on back-end to 13 per page.

Check rest of comments too.

2021-11-21 13:39 UTC, AjobK commented on frontend/src/components/posts/index.js
> +	  }
Wrong indentation. Two spaces

2021-11-21 13:39 UTC, AjobK commented on frontend/src/components/posts/index.js
> +    }
```suggestion
    while (currentElement?.props?.children) {
        const { children } = currentElement.props
        currentElement = children || []
    }
    
    return currentElement
```

2021-11-21 13:39 UTC, AjobK commented on frontend/src/components/posts/index.js
>      singleLi.classList.add(styles.post)
Not using this?

2021-11-21 13:39 UTC, AjobK commented on frontend/src/components/posts/index.js
> +    const postsBlocks = this.state.postsBlocks
```suggestion
    const { postsBlocks } = this.state
```

2021-11-21 13:39 UTC, AjobK commented on frontend/src/components/posts/index.js
>          }
Make more dynamic. This would fail if back-end pagination were to set larger portions per page.

2021-11-21 14:28 UTC, jerohero commented on frontend/src/components/posts/index.js
>          this.renderNewPosts(json.posts ? json.posts : [])
json.posts? || []

2021-11-27 14:32 UTC, jerohero commented on frontend/src/components/posts/index.js
>          this.renderNewPosts(json.posts ? json.posts : [])
![image](https://user-images.githubusercontent.com/14930277/143685678-07d224c2-d438-4d05-8796-5523c750034d.png)
No worky

2021-11-27 14:42 UTC, jerohero commented on frontend/src/components/posts/index.js
>          this.renderNewPosts(json.posts ? json.posts : [])
json.posts || [] does

2021-11-27 20:18 UTC, jerohero commented on frontend/src/components/posts/index.js
> +    }
_Return currentElement_ had to be _return currentElement.props.posts_. Unfortunately had to spend 3 hours to see this 😅

2021-11-27 20:38 UTC, jerohero commented
> ![image](https://user-images.githubusercontent.com/35965716/142764146-5d6403e0-0dfe-47ca-858c-81ada5da6b90.png)
> 
> Pagination doesn't seem to work well when changing on back-end to 13 per page.
> 
> Check rest of comments too.

Fixed it with the following code in _renderNewPostsAtLastPostsBlock():_
```
const amountOfPostBlocks = Math.ceil(posts.length / this.MAX_POSTS_IN_BLOCK)

for (let i = 0; i < amountOfPostBlocks; i++) {
  const postsInPostsBlock = posts.slice(
    this.MAX_POSTS_IN_BLOCK * i,
    this.MAX_POSTS_IN_BLOCK * (i + 1)
  )

  postsBlocks.push(this.createPostsBlock(postsInPostsBlock))
}
```

_MAX_POSTS_IN_BLOCK_ will still always be 6 since that's how they're shown in the post blocks, but the logic behind deciding whether the end of the posts has been reached (in _fetchPosts()_) has been changed to:
```
if (json.posts.length < json.per_page) {
  this.setEndReached(true)
}
```

This makes it dynamic; the posts amount per page from the API is used.

One thing I did notice while testing this is that it doesn't work when the posts per page amount is 1. I don't think we'll ever want to set it to that amount, but it might be worth mentioning anyway.

2021-11-28 12:20 UTC, AjobK requested changes
As discussed in call, make it work with refactored pagination

2021-11-28 13:58 UTC, jerohero commented
![image](https://user-images.githubusercontent.com/14930277/143770932-fd06f81e-537d-451a-a23b-64586d37d28d.png)
Tests succeed

2021-12-05 09:39 UTC, jerohero commented
@AjobK I made the changes we discussed last week (fix thumbnails and scroll end reached detection). I fixed an issue that suddenly made scrolling not function at all, so I am not entirely sure this is what you meant.

2021-12-05 10:17 UTC, MrGooss commented
Issue with page infinitely reloading when there aren't enough posts to fill the page. Could be fixed by checking the total count of posts en seeing if loading new posts is necessary or not.

2021-12-05 10:31 UTC, MrGooss requested changes

2021-12-05 10:31 UTC, MrGooss commented on frontend/src/components/posts/index.js
> +    return currentElement.props.posts
Might cause an issue with props/posts being undefined when it gets set to []

2021-12-19 10:53 UTC, AjobK approved these changes

2021-12-19 10:54 UTC, merged