340 login require direct
AjobK/Athena pull request #358
Opened 2021-12-05 13:40 UTC by jerohero

closes #340 

<br />

 **What is it supposed to do**  
When someone tries to use a functionality that requires the user to be logged in, a popup can be shown asking the user to log in. Doing so will redirect the user back to the page from whence those gents hath cometh.
![image](https://user-images.githubusercontent.com/14930277/144748097-966061ff-44a8-4609-b914-ad42a4335d1d.png)

<br />

 **How can we test your branch**  
Currently the only functionality that directly requires users to sign in is liking posts (commenting does as well, but this just shows a button for signing in instead). Try liking posts while logged in and logged out. See if you get redirected properly.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [x] d. Edge
- [ ] e. Safari

---

2021-12-12 09:55 UTC, AjobK requested changes

2021-12-12 09:55 UTC, AjobK commented on frontend/src/util/notificationUtil.js
> +  }
Why make a seperate function for this, instead of a general

showNotification = (message) => {
    ....
}

That way you can call the function as follows: NotificationUtil.showNotification(popUpData.message.networkError)

Is it not possible to inject the store into this class?

2021-12-12 09:55 UTC, AjobK commented on frontend/src/components/loginPrompt/index.js
> +
```suggestion
        const { user } = res.data
        const { profile } = this.props.store

```

2021-12-12 09:55 UTC, AjobK commented on frontend/src/components/loginPrompt/index.js
> +        this.props.store.profile.setProfileData(user)
```suggestion
        profile.setProfileData(user)
```

2021-12-12 09:55 UTC, AjobK commented on frontend/src/components/postBanner/index.js
> +        NotificationUtil.showNetworkError(this.props.store)
As stated in different comment th usage should be different. You shouldn't give the entire store to the class

2021-12-12 09:55 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +    }
```suggestion
    const { profile } = this.props.store
    
    if (!profile.loggedIn) return this.showLoginRedirect()
```

2021-12-12 09:55 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +    NotificationUtil.showLoginRedirect(store, history)
No passing of store

2021-12-12 11:01 UTC, jerohero commented on frontend/src/util/notificationUtil.js
> +  }
I wasn't able to find a way to inject the store into a class that is not a component, since you would need access to the props to use the store.

2021-12-12 11:12 UTC, jerohero commented on frontend/src/components/postBanner/index.js
> +        NotificationUtil.showNetworkError(this.props.store)
Unfortunately I am unable to can

2021-12-12 11:13 UTC, jerohero commented
Add [image](https://www.freepik.com/free-vector/employees-giving-hands-helping-colleagues-walk-upstairs_7732609.htm)

2021-12-12 14:58 UTC, jerohero commented
Implemented [unDraw](https://undraw.co/) images

2021-12-19 12:03 UTC, ryankroon00 submitted a review, later dismissed

2021-12-19 13:49 UTC, AjobK commented on frontend/src/components/postLike/index.js
> +    NotificationUtil.showLoginRedirect(store, history)
I understand the issue, which you mentioned before. It seems that this is possible, but pretty annoying to implement and use down the line. Furthermore it would require quite some testing on mobx stores.

I added a TODO to the function to indicate the problem.

https://stackoverflow.com/questions/49855022/accessing-mobx-store-in-vanilla-es6-javascript-class

2021-12-19 13:51 UTC, AjobK approved these changes

2021-12-19 13:56 UTC, ryankroon00 submitted a review, later dismissed

2021-12-19 14:22 UTC, AjobK commented
navigation.js is verwijderd @jerohero 

Het liefst dit niet met een store doen, maar als het moet graag een store aanmaken weer en daar gebruik van maken.

Dit is echter ECHT NIET gewenst, gezien we van al deze stores af willen. Deze store was in een andere branch namelijk verwijderd. Hierdoor heb je merge conflicts.

2021-12-19 14:23 UTC, AjobK requested changes
merge conflict

2022-01-23 10:51 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/150675100-501843cd-f5eb-4a90-9c29-18e2ca7f9c09.png)

Stays after popup cancel

2022-02-06 10:51 UTC, ryankroon00 commented
If you go to a post, like it, log out then try to dislike it, it doesn't show the popup.

2022-02-06 13:05 UTC, AjobK requested changes
Merge conflicts

2022-02-12 16:12 UTC, jerohero commented
> If you go to a post, like it, log out then try to dislike it, it doesn't show the popup.

This issue does not occur anymore after pulling from develop, since the logout button now redirects the user to the homepage. Should I still try to fix this issue, even though it doesn't occur anymore?

2022-03-06 13:21 UTC, AjobK approved these changes

2022-03-20 09:26 UTC, sribadal approved these changes
LGTM

2022-04-17 08:14 UTC, merged