316 nestjs refactor
AjobK/Athena pull request #362
Opened 2021-12-12 17:20 UTC by danielordaan

closes #316
closes #317
closes #319
closes #320
closes #321  

<br />

 **What is it supposed to do**  
All backend functionality as of commit b677675a6733adcaedfeb44513724176584781d4 has been refactored for it to use the NestJS Framework.

<h2>Structural changes</h2>
The logical backend architecture consisted of the following path:
Routes -> Optional Middlewares -> Controllers -> Daos

In the new backend architecture this has been refactored to the following architecture:
Optional Guards -> Controllers -> Services -> Repositories

The guards allow or disallow access to the routes which are defined in the controllers. Routes are guarded by default but can be anonymized by using the `@AllowAny()` decorator. Request parameters and body attributes are from now on also encapsulated by decorators like `@Param()` and `@Body()`. Larger data structures have been defined in the `dtos` folder.

To use the DIP, NestJS uses a module driven architecture. Each module has one controller but can provide an arbitrary amount of services. Repositories that are used in these services must be declared via the `imports` array which contains the TypeOrm Entity references.

On compilation environment variables are checked for their presence. This is defined in the `config.schema.ts` file. To view complete API documentation of the backend, run the backend with `NODE_ENV=development` and go to `http://localhost:8000/docs`.

<br />

 **How can we test your branch**  
The new backend should seamlessly fit onto the existing frontend. The only changes made to the frontend were some route names. Tests can be ran by running `npm run test`. To get a quick view of all the endpoints, use the swagger documentation.

<br />

**1. General checklist**
- [~] a. Tested happy flow. _I did my best_
- [~] b. Tested unhappy flow. _I did my best_
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [ ] a. Responsive. (Desktop all the way to mobile 320px)
- [ ] b. Using SCSS variables where relevant.
- [ ] c. Relevant class names
- [ ] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [ ] a. Chrome
- [ ] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

2021-12-19 09:45 UTC, ryankroon00 requested changes

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/seeding/seeders/seeder.ts
> +    const thumbnailPic = await attachmentSeeder(factory, 'default/defaultThumbnail.jpg')
Maybe change the values to the variables in /data/seed.data.ts

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/app.module.ts
> +import {JwtAuthGuard} from "./guards/jwt-auth.guard";
```suggestion
import { APP_GUARD, Reflector } from "@nestjs/core"
import { JwtAuthGuard } from "./guards/jwt-auth.guard"
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/modules/auth.module.ts
> +import {CaptchaService} from "../services/captcha.service";
```suggestion
import { CaptchaService } from '../services/captcha.service'
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/modules/post.module.ts
> +import {RoleRepository} from "../repositories/role.repository";
```suggestion
import { RoleRepository } from '../repositories/role.repository'
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/services/profile.service.ts
> +import {Multer} from "multer";
```suggestion
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/test/profileTest.ts
> +import fs = require('fs');
```suggestion
import fs = require('fs')
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/entities/comment_has_attachment.entity.ts
> +import { Attachment } from './attachment.entity';
```suggestion
import { Attachment } from './attachment.entity'
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/controllers/auth.controller.ts
> +  constructor(private readonly authorizationService: AuthService, private readonly captchaService: CaptchaService) {}
```suggestion
  constructor(
  private readonly authorizationService: AuthService, 
  private readonly captchaService: CaptchaService) {
  }
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/controllers/comment.controller.ts
> +import { Body, Controller, Delete, Get, NotFoundException, Param, Patch, Post, UseGuards } from '@nestjs/common'
```suggestion
import { Body, Controller, Delete, Get, NotFoundException, Param, Patch, Post } from '@nestjs/common'
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/controllers/profile.controller.ts
> +      'Set-Cookie', `token=${payload.token};httponly;${this.configService.get('SECURE') == 'true' ? 'secure;' : ''}expires=${+new Date(new Date().getTime() + 86409000).toUTCString()};path=/;`
This line has a length of 191. Maximum allowed is 120.

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/guards/jwt-auth.guard.ts
> +  handleRequest(err: any, user: any, info: any, context: ExecutionContext): any {
are err and info required because they aren't used in the function

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/services/auth.service.ts
> +import { ForbiddenException, forwardRef, Inject, Injectable } from '@nestjs/common'
```suggestion
import { ForbiddenException, Injectable } from '@nestjs/common'
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/services/ban.service.ts
> +  public async banUser(banUserDTO: BanUserDTO, account: Account, remoteAddress): Promise<void> {
Can you give remoteAdress a type?

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/services/file.service.ts
> +const pipeline = promisify(require('stream').pipeline)
```suggestion
```

2021-12-19 09:45 UTC, ryankroon00 commented on nest-backend/src/services/post.service.ts
> +    if (!post || post.profile.display_name !== user.profile.display_name || !(await this.hasRemovePostPermission(user))) {
This line has a length of 122. Maximum allowed is 120.

2021-12-19 09:57 UTC, AjobK requested changes

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/dtos/response/posts.dto.ts
> +  per_page: number
Is this meant to be two different casings?

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/userTest.ts
> +          email: id + '@test.com',
```suggestion
          email: `${ id }'@test.com`,
```

More consistent

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    if (attachments.banner) payload['banner'] = 'http://localhost:8000/' + attachments.banner.path
These routes should be in env or something. Also quite WET

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +      title: title ? title.name : 'Title not found...',
```suggestion
      title: title?.name || 'Title not found...',
```

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +    return 'http://localhost:8000/' + attachment.path
Raw route

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/banTest.ts
> +  const agent = chai.request.agent('http://localhost:3000/api')
Raw route

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/commentTest.ts
> +  const agent = chai.request.agent('http://localhost:3000/api')
Raw route

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/likeTest.ts
> +  const agent = chai.request.agent('http://localhost:3000/api')
Raw route

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/postTest.ts
> +  const agent = chai.request.agent('http://localhost:3000/api')
Raw route

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/profileTest.ts
> +  const agentUser = chai.request.agent('http://localhost:3000/api')
Raw routes

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/test/userTest.ts
> +  const agent = chai.request.agent('http://localhost:3000/api')
Raw route

2021-12-19 09:57 UTC, AjobK commented on backend/app/controllers/postController.ts
> +    const attachmentURL = 'http://localhost:8000/' + foundAttachment.path
Raw route and not the string format we use for these cases

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/controllers/profile.controller.ts
> +      url: 'http://localhost:8000' + avatar.path
Raw route and incorrect string format

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/controllers/profile.controller.ts
> +      url: 'http://localhost:8000' + avatar.path
Raw route and incorrect string format

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/main.ts
> +  const LOCALHOST = 'http://localhost'
This is okay, only if you are 100% sure this will not interfere with proud.

Also, if possible make the var name LOCALHOST_URL

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +    const attachmentURL = 'http://localhost:8000/' + foundAttachment.path
Raw route and incorrect string format

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +    return 'http://localhost:8000/' + banner.path
Raw route and incorrect string format

2021-12-19 09:57 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    if (attachments.banner) payload['banner'] = 'http://localhost:8000/' + attachments.banner.path
Raw route and incorrect string format

2021-12-19 10:01 UTC, jerohero requested changes

2021-12-19 10:01 UTC, jerohero commented on nest-backend/src/test/profileTest.ts
> +              amountOfFollowers = res.status == 200 ? res.body.followers.length : 0
Shouldn't this have an assert statement to confirm the user has been unfollowed?

2021-12-19 10:01 UTC, jerohero commented on nest-backend/src/test/profileTest.ts
> +          done()
Shouldn't there be an assert statement confirming amountOfFollowers was fetched successfully?

2021-12-19 10:04 UTC, jerohero commented on nest-backend/src/test/banTest.ts
> +            .get(`/profile/'${longBannedUser}`)
```suggestion
            .get(`/profile/'${ longBannedUser }`)
```

2021-12-19 10:05 UTC, jerohero commented on frontend/src/pages/profile/index.js
> +    Axios.get(`${this.props.store.defaultData.backendUrl}/post/like/recent/${username}`)
```suggestion
    Axios.get(`${ this.props.store.defaultData.backendUrl }/post/like/recent/${ username }`)
```

2021-12-19 10:05 UTC, jerohero commented on nest-backend/src/controllers/auth.controller.ts
> +      `token=${token}; HttpOnly; ${process.env.SECURE == 'true' ? 'Secure;' : ''} expires=${+new Date(
```suggestion
      `token=${ token }; HttpOnly; ${ process.env.SECURE == 'true' ? 'Secure;' : '' } expires=${ +new Date(
```

2021-12-19 10:06 UTC, ryankroon00 commented on nest-backend/.env.example
> +HCAPTCHA_TEST_TOKEN=
```suggestion
DB_HOST=localhost
DB_PORT=5433
DB_USERNAME=postgres
DB_PASSWORD=root
DB_NAME=seaqull
JWT_SECRET=KGn]FCx0w~TI
JWT_EXPIRATION=600000
SECURE=false
NODE_ENV=development
FRONTEND_URL=http://localhost:8080
HCAPTCHA_DEV_SECRET_KEY=0x0000000000000000000000000000000000000000
HCAPTCHA_PROD_SECRET_KEY=0x0000000000000000000000000000000000000001
HCAPTCHA_TEST_TOKEN=10000000-aaaa-bbbb-cccc-000000000001
```

2021-12-19 10:06 UTC, ryankroon00 commented on nest-backend/src/services/post-like.service.ts
> +    console.log(likes)
```suggestion
```

2021-12-19 10:06 UTC, ryankroon00 commented on nest-backend/src/services/post-like.service.ts
> +    console.log(postLike)
```suggestion
```

2021-12-19 10:06 UTC, ryankroon00 commented on nest-backend/src/services/profile.service.ts
> +    console.log(followedProfile)
```suggestion
```

2021-12-19 10:07 UTC, jerohero commented on nest-backend/src/controllers/profile.controller.ts
> +      'Set-Cookie', `token=${payload.token};httponly;${this.configService.get('SECURE') == 'true' ? 'secure;' : ''}expires=${+new Date(new Date().getTime() + 86409000).toUTCString()};path=/;`
```suggestion
      'Set-Cookie', `token=${ payload.token };httponly;${ this.configService.get('SECURE') == 'true' ? 'secure;' : '' }expires=${ +new Date(new Date().getTime() + 86409000).toUTCString() };path=/;`
```

2021-12-19 10:09 UTC, jerohero commented on nest-backend/src/main.ts
> +    `${LOCALHOST}:3000`
```suggestion
    `${ LOCALHOST }:8080`,
    `${ LOCALHOST }:3000`
```

2021-12-19 10:09 UTC, jerohero commented on nest-backend/src/main.ts
> +  logger.log(`Application listening on port ${port}`)
```suggestion
  logger.log(`Application listening on port ${ port }`)
```

2021-12-19 10:09 UTC, jerohero commented on nest-backend/src/main.ts
> +    logger.log(`Documentation available at /${swaggerEndpointPath}`)
```suggestion
    logger.log(`Documentation available at /${ swaggerEndpointPath }`)
```

2021-12-19 10:10 UTC, jerohero commented on nest-backend/src/modules/auth.module.ts
> +          signOptions: { expiresIn: `${configService.get('JWT_EXPIRATION')}s` }
```suggestion
          signOptions: { expiresIn: `${ configService.get('JWT_EXPIRATION') }s` }
```

2021-12-19 10:10 UTC, jerohero commented on nest-backend/src/repositories/ban.repository.ts
> +      return `Account banned until ${date}`
```suggestion
      return `Account banned until ${ date }`
```

2021-12-19 10:15 UTC, jerohero commented on nest-backend/src/services/comment.service.ts
> +    if (!post) throw new BadRequestException({ error: `No post with path ${postPath} found` })
```suggestion
    if (!post) throw new BadRequestException({ error: `No post with path $ {postPath } found` })
```

2021-12-19 10:16 UTC, jerohero commented on nest-backend/src/services/comment.service.ts
> +    if (!post) throw new NotFoundException(`No post found with path ${path}`)
```suggestion
    if (!post) throw new NotFoundException(`No post found with path ${ path }`)
```

2021-12-19 10:16 UTC, jerohero commented on nest-backend/src/services/comment.service.ts
> +    if (!comment) throw new NotFoundException(`Comment to delete not found with id ${comment_id}`)
```suggestion
    if (!comment) throw new NotFoundException(`Comment to delete not found with id ${ comment_id }`)
```

2021-12-19 10:16 UTC, jerohero commented on nest-backend/src/services/file.service.ts
> +    const name = uuidv4() + `.${extension}`
```suggestion
    const name = uuidv4() + `.${ extension }`
```

2021-12-19 10:16 UTC, jerohero commented on nest-backend/src/services/post.service.ts
> +    if (!post) throw new NotFoundException(`No post found with path ${path}`)
```suggestion
    if (!post) throw new NotFoundException(`No post found with path ${ path }`)
```

2021-12-19 10:18 UTC, jerohero commented on nest-backend/src/test/banTest.ts
> +        email: `${shortBannedUser}@test.com`,
```suggestion
        email: `${ shortBannedUser }@test.com`,
```

2021-12-19 10:18 UTC, jerohero commented on nest-backend/src/test/banTest.ts
> +        email: `${longBannedUser}@test.com`,
```suggestion
        email: `${ longBannedUser }@test.com`,
```

2021-12-19 10:19 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +          username: `test${id}`,
```suggestion
          username: `test${ id }`,
```

2021-12-19 10:20 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +    it('Shouln\'t login with invalid username and password', (done) => {
```suggestion
    it(`Shouln't login with invalid username and password`, (done) => {
```

2021-12-19 10:20 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +          email: id + '@test.com',
```suggestion
          email: `${ id }@test.com`,
```

2021-12-19 10:20 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +          email: id + '@test.com',
```suggestion
          email: `${ id }@test.com`,
```

2021-12-19 10:21 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +          email: id + '@test.com',
```suggestion
          email: `${ id }@test.com`,
```

2021-12-19 10:21 UTC, jerohero commented on nest-backend/src/test/userTest.ts
> +          username: `test${id}`,
```suggestion
          username: `test${ id }`,
```

2021-12-19 10:21 UTC, jerohero commented on nest-backend/src/test/profileTest.ts
> +        .attach('file', fs.readFileSync(`${__dirname}/data/banner.jpeg`), 'banner.jpeg')
```suggestion
        .attach('file', fs.readFileSync(`${ __dirname }/data/banner.jpeg`), 'banner.jpeg')
```

2021-12-19 10:22 UTC, AjobK requested changes

2021-12-19 10:22 UTC, AjobK commented on nest-backend/src/config.schema.ts
> +  DB_HOST: Joi.string().default('localhost'),
Env?

2021-12-19 10:22 UTC, AjobK commented on nest-backend/src/main.ts
> +    `${LOCALHOST}:3000`
Shouldn't this just be whatever is in the env file?

2021-12-19 10:22 UTC, AjobK commented on nest-backend/src/main.ts
> +  if (process.env.NODE_ENV === 'development') {
We might want to document this somewhere. Otherwise the specific string 'development' instead of 'dev' or something might be lost in all the code.

2021-12-19 10:22 UTC, AjobK commented on nest-backend/src/main.ts
> +  if (process.env.NODE_ENV === 'development') {
env example is a good place for it I think

2021-12-19 10:22 UTC, AjobK commented on nest-backend/src/controllers/profile.controller.ts
> +  Res, UnauthorizedException,
Every item on a new line. Here there's multiple items on the same line

2021-12-19 10:22 UTC, AjobK commented on backend/app/controllers/postController.ts
> +  // TODO Move to another file?
TODO still needed?

2021-12-19 10:22 UTC, AjobK commented on backend/app/controllers/commentController.ts
> +        .json({ message: 'Invalid post or profile given. Likely an attempt to comment on "new-post" page' })
```suggestion
        .json({ message: 'Invalid post or profile given. Likely an attempt to comment on \'new-post\' page' })
```

Citations are single-quote

2021-12-19 10:22 UTC, AjobK commented on backend/app/controllers/postController.ts
> +      } catch (err) {
Not of type jsonprocessing error or something?

2021-12-19 10:27 UTC, sribadal requested changes

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/repositories/post_like.repository.ts
> +  async findLikeByPostAndProfile(post: Post, profile: Profile): Promise<PostLike> {
Shouldn't there be an access modifier here?

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/repositories/profile_comment_like.repository.ts
> +  async deleteCommentLike(profile: Profile, comment: Comment): Promise<void> {
Access modifier is missing here too

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/services/post-like.service.ts
> +  async likePost(path: string, profile: Profile): Promise<void> {
Access modifier missing here, it is still public but on other places you are still using public so for consistency use it here too..

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/services/post-like.service.ts
> +  async unlikePost(path: string, profile: Profile): Promise<void> {
Access modifier missing here.

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/services/post-like.service.ts
> +    console.log(likes)
Remove console.log

2021-12-19 10:27 UTC, sribadal commented on nest-backend/src/services/post-like.service.ts
> +    console.log(postLike)
Remove console.log

2021-12-19 10:50 UTC, jerohero commented on nest-backend/.env.example
> +HCAPTCHA_TEST_TOKEN=
DB_PORT should be 5432

2022-01-02 10:49 UTC, danielordaan commented on nest-backend/src/test/userTest.ts
> +    it('Shouln\'t login with invalid username and password', (done) => {
Linter does not permit this

2022-01-02 10:51 UTC, danielordaan commented on nest-backend/src/config.schema.ts
> +  DB_HOST: Joi.string().default('localhost'),
This file validates what is entered in the env file, if variables are missing or incorrect, it will use the defaults or throw a descriptive error

2022-01-02 10:52 UTC, danielordaan commented on backend/app/controllers/postController.ts
> +  // TODO Move to another file?
This is the old backend

2022-01-02 10:52 UTC, danielordaan commented on backend/app/controllers/postController.ts
> +  // TODO Move to another file?
I moved things around in the files to keep it organised, that's why there are additions and deletions in those files

2022-01-02 10:53 UTC, danielordaan commented on backend/app/controllers/commentController.ts
> +        .json({ message: 'Invalid post or profile given. Likely an attempt to comment on "new-post" page' })
Wrong backend

2022-01-02 10:53 UTC, danielordaan commented on backend/app/controllers/postController.ts
> +      } catch (err) {
Wrong backend

2022-01-02 11:14 UTC, danielordaan commented on nest-backend/src/main.ts
> +  if (process.env.NODE_ENV === 'development') {
Done

2022-01-02 11:17 UTC, danielordaan commented
### Frontend testing document

The following features have been tested:
- Logging in
- Registering
- Logging out
- Viewing a post
- Liking a post
- Unliking a post
- Commenting on a post
- Replying to a comment
- Liking a comment
- Unliking a comment
- Deleting a comment
- Changing post banner
- Changing profile avatar
- Changing profile banner
- Changing profile description
- Liked post overview on profile page
- Created post overview on profile page
- Following a user (and seeing this on their and your profile page)

2022-01-02 12:18 UTC, AjobK requested changes

2022-01-02 12:18 UTC, AjobK commented on frontend/src/components/registerPrompt/index.js
> +      }
WET. Why not have an object called errors with the keys username, email and password.

Then loop over Object.keys and check if error includes the object key. If so, push to errors[keyName] the elem. Then continue

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/controllers/auth.controller.ts
> +@Controller('')
Is this supposed to be empty?

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/controllers/post-like.controller.ts
> +  }
Empty constructor. If you want to use it, please make it one line

```suggestion
  constructor(private readonly postLikeService: PostLikeService) { }
```

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/controllers/post.controller.ts
> +  ) {}
one line for constructors if only one arg

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/controllers/profile.controller.ts
> +import { ConfigService } from '@nestjs/config'
order of imports. This should be somewhere above

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/controllers/role.controller.ts
> +  constructor(private readonly roleService: RoleService) {}
```suggestion
  constructor(private readonly roleService: RoleService) { }
```

2022-01-02 12:18 UTC, AjobK commented on nest-backend/src/decorators/host.decorator.ts
> +  const url = req.protocol + '://' + req.get('host')
As discussed previously we use this format of string concats

```suggestion
  const url = `${req.protocol}://${req.get('host')}`
```

2022-01-02 12:47 UTC, AjobK requested changes
Sent all kinds of banners that you yourself uploaded

2022-01-02 12:47 UTC, AjobK commented on frontend/src/components/registerPrompt/index.js
> +        this.handleError(res?.response?.data?.message)
Isn't res always a response?

```suggestion
        this.handleError(res.response?.data?.message)
```

2022-01-02 12:47 UTC, AjobK commented on frontend/src/pages/post/index.js
> +      const url = `${this.props.store.defaultData.backendUrl}/post/view`
```suggestion
      const url = `${ this.props.store.defaultData.backendUrl }/post/view`
```

2022-01-02 12:47 UTC, AjobK commented on nest-backend/src/controllers/comment.controller.ts
> +    if (comments.length === 0) return []
If comments.length = 0, cant you just return comments..? Instead of another empty array

2022-01-02 12:47 UTC, AjobK commented on nest-backend/src/controllers/profile.controller.ts
> +    delete payload.token
Whitelisting > Blacklisting

2022-01-02 12:47 UTC, AjobK commented on nest-backend/src/guards/jwt-auth.guard.ts
> +    throw new UnauthorizedException()
whitelines

2022-01-02 12:47 UTC, AjobK commented on nest-backend/src/guards/roles.guard.ts
> +      }))
break after finding one where permission is set to true? Unnecessary amount of loops otherwise

2022-01-02 12:47 UTC, AjobK commented on nest-backend/src/main.ts
> +  const port = 8000
env

2022-01-02 13:10 UTC, AjobK requested changes

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/account.repository.ts
> +    return account.profile
```suggestion
    return account?.profile
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/ban.repository.ts
> +  }
```suggestion
  public async getBanByUser(account: Account): Promise<Ban> {
    return await this.findOne({ where: { user: account.id } })
  }
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/comment.repository.ts
> +    return comment
```suggestion
    return await this.findOne(id)
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/comment.repository.ts
> +    return comments
```suggestion
    return await this.find({ where: { parent_comment_id } })
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/post.repository.ts
> +    return post
```suggestion
    return await this.findOne({ path: postPath }, { relations: ['profile'] })
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/post_like.repository.ts
> +    return postLike
```suggestion
    return await this.findOne({ where: { post: post.id, profile: profile.id } })
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/profile.repository.ts
> +    return !user ? null : user.title
```suggestion
    return user?.title
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/profile.repository.ts
> +    return newProfile
```suggestion
    return await this.save(profile)
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/profile_comment_like.repository.ts
> +    }
```suggestion
    if (commentLikes.length > 0) return
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/profile_comment_like.repository.ts
> +    }
```suggestion
    if (commentLikes.length < 1) return
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/repositories/title.repository.ts
> +    return title
```suggestion
    return await this.findOne({ id })
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/auth.service.ts
> +  }
```suggestion
  ) { }
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/auth.service.ts
> +    const profile = account.profile
```suggestion
    const account = await this.accountRepository.getAccountProfileAndRoleByUsername(decodedToken.user_name)
    const profile = account.profile

    const attachments = await this.profileRepository.getProfileAttachments(profile.id)
    const title = await this.profileRepository.getTitleByUserId(profile.id)
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/ban.service.ts
> +  }
```suggestion
  ) { }
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/comment.service.ts
> +      parent_comment_id ? await this.commentRespository.getCommentById(parent_comment_id) : undefined
```suggestion
    comment.parent_comment_id = parent_comment_id
        ? await this.commentRespository.getCommentById(parent_comment_id)
        : undefined
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/comment.service.ts
> +    if (!(commentProfile.display_name === profile.display_name)) {
```suggestion
    if (commentProfile.display_name !== profile.display_name) {
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/comment.service.ts
> +    }
If not necessary, since loop won't occur without a child
```suggestion
    for (const child of children) {
      await this.commentRespository.archiveComment(child, archivedDate)
    }
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/post-like.service.ts
> +    return posts
```suggestion
    return likes.map((like) => like.post)
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +
```suggestion
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +    let isOwner = false
```suggestion
    let userLiked = false
    let isOwner = false
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/post.service.ts
> +      // TODO, attachments have the server host url hardcoded prepended
This isn't really a TODO? Like, what do we need to do?

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    const title: Title = (await this.profileRepository.getTitleByUserId(profile.id)) || null
```suggestion
    const title: Title = await this.profileRepository.getTitleByUserId(profile.id) || null
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +      token,
```suggestion
      token
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    return avatar
```suggestion
    return this.updateAttachment(file, user_name, 'avatar')
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    return banner
```suggestion
    return this.updateAttachment(file, user_name, 'banner')
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/profile.service.ts
> +    let typeField
```suggestion
    let typeField
    
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/services/role.service.ts
> +    return role
```suggestion
    return await this.roleRepository.getRoleById(decodedToken.role_id)
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/strategies/jwt.strategy.ts
> +          return request?.cookies?.token
```suggestion
          return request.cookies?.token
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/commentTest.ts
> +  const agent = chai.request.agent('http://localhost:8000/api')
Using hardcoded url

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/likeTest.ts
> +  const agent = chai.request.agent('http://localhost:8000/api')
hardcoded url

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/profileTest.ts
> +  const agentUser = chai.request.agent('http://localhost:8000/api')
hardcoded url

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/userTest.ts
> +  const agent = chai.request.agent('http://localhost:8000/api')
hardcoded

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/userTest.ts
> +          email: `${id}@test.com`,
```suggestion
          email: `${ id }@test.com`,
```

2022-01-02 13:10 UTC, AjobK commented on nest-backend/src/test/userTest.ts
> +          email: `${id}@test.com`,
```suggestion
          email: `${ id }@test.com`,
```

2022-01-02 13:26 UTC, AjobK commented
Merge conflicts btw?

2022-01-09 10:23 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/148678305-a9f5d79e-8d12-431a-8800-c21de8b1bee2.png)

![image](https://user-images.githubusercontent.com/35965716/148678308-4fbc14d0-3b42-4a8e-8093-dd6378d4cbfa.png)


When registering

2022-01-09 10:24 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/148678314-bd720632-0df4-4b20-b689-41fede9fac39.png)

Post pagination code is outdated

2022-01-09 10:24 UTC, jerohero requested changes
"Post owned by" route crashes the backend if no valid username is given

![image](https://user-images.githubusercontent.com/14930277/148678306-a4cfdb6d-d184-418c-8463-079d85dc7f5c.png)

![image](https://user-images.githubusercontent.com/14930277/148678294-6597248b-964b-4c61-8b2c-2951bc6f035d.png)

EDIT: nvm me smooth brain

2022-01-09 10:45 UTC, jerohero commented
Giving a negative page number gives an unhandled error

![image](https://user-images.githubusercontent.com/14930277/148678930-5fdf098e-903d-403c-8100-74245bf98f22.png)
![image](https://user-images.githubusercontent.com/14930277/148678926-43d48eda-cc35-4161-b4b3-ee657e9dc363.png)

2022-01-09 13:14 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/148683598-28e605e9-43ea-4d36-b48e-2e41e18357e7.png)

Liked by doesn't work anymore

Likely because of very cryptic response from back-end

![image](https://user-images.githubusercontent.com/35965716/148683671-00ecb9ef-486d-4386-8eeb-20dcc1c59d91.png)

2022-01-23 12:24 UTC, AjobK approved these changes

2022-01-23 12:24 UTC, jerohero approved these changes

2022-01-23 12:27 UTC, ryankroon00 approved these changes

2022-01-23 12:27 UTC, sribadal approved these changes

2022-01-23 12:31 UTC, merged