350 add a tooltip
AjobK/Athena pull request #372
Opened 2021-12-28 09:47 UTC by sribadal

closes #350

<br />

 **What is it supposed to do**  
Whenever you are creating a post, or editing a post a tooltip needs to appear after selecting some text. With this tooltip you can apply some markdown to your written text. For mobile and tablet devices a mobile bar should appear which needs to be scrollable if there are a lot of buttons. It has the same behaviour as the tooltip, which is applying markdown to text.

The icon component got refactored. If you use a prefix, and an iconname which is found on: https://mui.com/components/material-icons/. If you have a custom svg you can use that too by using the prefix 'custom'. You then give the iconName the image file, which will eventually render it on your screen.

<br />

 **How can we test your branch** 
1. Create a post
2. Write some text
3. Select text

It should look like this: 
![image](https://user-images.githubusercontent.com/55099336/147552301-e9481e12-fcb4-4618-89db-6cd04e02b8bf.png)

And for mobile it should look like this:
![image](https://user-images.githubusercontent.com/55099336/147552495-e98905ac-cf9d-420d-8911-bf08b5cc3b59.png)

If the icons are appearing the icon component using MUI works. Inspect code to further examine the component.

<br />

 **Additional notes**  
- Adding active to the mobile bar was to broad for this feature, because the mobile bar component is a generic component which will be used for mobile/tablet devices.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [ ] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [x] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2022-01-01 16:19 UTC, AjobK requested changes

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/mobileBar/mobileBar.scss
> +			> button {
newline above

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +  }
Why not do this?

Feels a lot less dry atleast... Right now you're writing DraftEditor-align multiple times

```suggestion
  getBlockStyle = (block) => {
      let blockType = block.getType()
      
      return blockType ? `DraftEditor-align${ blockType[0].toUpperCase() }${ blockType.slice(1) }` : null
  }
```

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +                    <>
Is this necessary? open bracket, lambda func and jsx fragment?

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/mobileBar/index.js
> +      </div>
Why all divs? This is a navigation bar

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +    this.plugins = [this.inlineToolbarPlugin]
```suggestion
    this.plugins = [ this.inlineToolbarPlugin ]
```

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
>      const totalLength = this.state.editorState.getCurrentContent().getPlainText().length + text.length
newline

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +    ]
Not the right place to put this code.

Also, is it not possible to change the styling names? So that you get styling 'LeftAlignIcon' and that way you don't need to track what styling corresponds to a certain icon component...

You could just do something like

`<CustomIcon iconName={ styling } />`

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +                            onButtonClick={ (e) => this.onToggleBlockStyling(`${element.styling}`, e) }
Is it necessary to put the element.styling in a string format? Like, is it not always a string anyway?

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +                            onButtonClick={ (e) => this.onToggleBlockStyling(`${element.styling}`, e) }
Meaning, you could just pass `element.styling` instead of `'${element.styling}'`

2022-01-01 16:19 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +              <MobileBar>
Indentation is wrong

2022-01-01 16:19 UTC, AjobK commented on frontend/src/static/icons/inlineToolbar/index.js
> +}
This could all be done within a customIcons component as stated in a different comment

2022-01-02 10:25 UTC, sribadal commented on frontend/src/components/postContent/index.js
> +                    <>
I needed to do this, this is also how draftjs does it in their example code. I tried to do it another way, but it didnt work

2022-01-30 09:02 UTC, sribadal commented on frontend/src/static/icons/inlineToolbar/index.js
> +}
Removed all this

2022-02-06 11:12 UTC, ryankroon00 requested changes

2022-02-06 11:12 UTC, ryankroon00 commented on frontend/src/components/postContent/index.js
> +          {/*{ type != 'title' && this.inlineStyleControls()}*/}
I think you can remove this

2022-02-06 12:51 UTC, AjobK requested changes
1. Pointers on buttons

2. H1, H2, H3 functional with align

3. Check if you can fix separator
![image](https://user-images.githubusercontent.com/35965716/152681605-0ee003b3-5c8d-4e71-bc39-4a0370735aa6.png)

2022-02-06 12:59 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/152681888-b7a5efcf-74ae-453a-b9c5-3eaa38e29e72.png)

Turn off z-index of input field text. No idea why it's there.

Show/hide toolbar based on if anything is selected.

Toolbar should have a higher contrast with background (white on white is very hard to see now)

2022-02-06 12:59 UTC, AjobK commented on frontend/src/components/postContent/postContent.scss
> +}
whitelines between

2022-03-05 15:44 UTC, sribadal commented on frontend/src/components/postContent/index.js
> +    this.plugins = [this.inlineToolbarPlugin]
![image](https://user-images.githubusercontent.com/55099336/156890312-a9b68d01-d840-4b1c-b8dd-edf5bf4ed260.png)
It is not possible..

2022-03-05 16:11 UTC, sribadal commented
Changes proposed:
- [x] Pointers on buttons
- [x] Show/hide toolbar based on text that is selected
- [x] **H1, H2, H3 functional with align (fixed by not using h1 tag, but by making font size bigger)**
- [x] Turning off Z-index did not work, but i resolved the issue by increasing z-index of mobile bar. (maybe look for a fix together?)
- [x] Added more box-shadow to mobile bar

Changes above can be found in commits:
- a40f88dc688486a7c7dc47f3aef4e636fd113497
- a2616afa711e3c35c5ecb9c1cfdafc7faca45c5e

Could not find a way to fix seperator in tooltip, and the h1, h2, h3 fix with align is not optimal for SEO

2022-03-20 10:51 UTC, AjobK commented
Closing for now, needs more research. Is still in sprint @shivam-badal 

Will re-open when it's ready

2022-09-10 08:05 UTC, sribadal commented
After merging the following PR looks like this, after the postContent revamp:
![image](https://user-images.githubusercontent.com/55099336/189474861-1f03bff7-36de-4477-8342-d774fb4b4e00.png)

2022-11-20 10:17 UTC, AjobK approved these changes

2022-11-20 10:17 UTC, merged