364 Toggling password also changes icon now
AjobK/Athena pull request #373
Opened 2022-01-01 11:58 UTC by sribadal

closes #364 

<br />

 **What is it supposed to do**  
Whenever you want to see your password you can click the eye icon. This eye icon needs to toggle to a different icon whenever clicked!

Before clicked:
![image](https://user-images.githubusercontent.com/55099336/147850024-ebf7deff-1af7-4d34-b495-fb10990e0462.png)

After clicked:
![image](https://user-images.githubusercontent.com/55099336/147850030-46331000-37a3-4e18-8868-9dde9b45b892.png)

<br />

 **How can we test your branch**  
1. Visit login page, register page
2. Type in password
3. Click on the eye icon

you should see the icon toggling to a different one.
<br />

 **Additional notes**  
Things to keep in mind regarding the PR that don't fit in the previous two headings. 

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2022-01-01 15:13 UTC, jerohero requested changes

2022-01-01 15:13 UTC, jerohero commented on frontend/src/components/formInput/index.js
> +                className={ `${styles.icon} ${styles.iconPassword}` }
Spacing
```suggestion
                className={ `${ styles.icon } ${ styles.iconPassword }` }
```

2022-01-01 15:13 UTC, jerohero commented on frontend/src/components/formInput/index.js
> +                className={ `${styles.icon} ${styles.iconPassword}` }
Spacing
```suggestion
                className={ `${ styles.icon } ${ styles.iconPassword }` }
```

2022-01-01 15:53 UTC, AjobK requested changes
Why not just toggle the iconName based on passwordVisible? Instead of switching between entire components

2022-01-01 16:14 UTC, sribadal commented on frontend/src/components/formInput/index.js
> +                className={ `${styles.icon} ${styles.iconPassword}` }
Heb dit veranderd!

2022-01-01 16:14 UTC, sribadal commented on frontend/src/components/formInput/index.js
> +                className={ `${styles.icon} ${styles.iconPassword}` }
Is veranderd!

2022-01-01 16:20 UTC, AjobK approved these changes
Muchhhhhh better 😄 

Only 2 lines too haha

2022-01-02 13:23 UTC, danielordaan approved these changes
LGTM

2022-01-02 13:24 UTC, merged