374 Changed images of login and register
AjobK/Athena pull request #374
Opened 2022-01-02 11:50 UTC by sribadal

closes #363

<br />

 **What is it supposed to do**  
The pictures on the login and register screen needed to change. This PR adds two new pictures on the login and register screen.

<br />

 **How can we test your branch**  
1. Visit login screen, register screen
2. Notice changes

<br />

 **Additional notes**  
Things to keep in mind regarding the PR that don't fit in the previous two headings. 

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [ ] a. No unhandled promise rejections.
- [ ] b. Seeders still functional.
- [ ] c. No primary-key violations.
- [ ] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [ ] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2022-01-02 13:27 UTC, AjobK requested changes
Use compressed svgs. They should be one line, not with so much whitespace. Now you have 427 additions for an svg hahaha

2022-01-16 10:47 UTC, AjobK requested changes
**Login**

![image](https://user-images.githubusercontent.com/35965716/149656785-e2bafcb9-bdd9-40ec-861e-04690f876c31.png)

The login splash image is too wide. Remove the underline and the two phones on the sides. This way the image is longer. Make it align with the username field name (as it is now) and bottom of the button.

**Register**

![image](https://user-images.githubusercontent.com/35965716/149656814-f3f1d013-5dc7-4f99-8f41-0e0cea8bb4f7.png)

Alignment is wrong on bottom and top. Also, too much whtiespace at bottom. Either change the image or make it fit (which should work). I do like the concept of the image so if you could make this one work that would be ideal.

2022-02-06 11:16 UTC, ryankroon00 submitted a review, later dismissed

2022-02-06 12:38 UTC, AjobK requested changes
Change spacing on register and login images

2022-02-06 13:31 UTC, AjobK approved these changes

2022-02-06 13:31 UTC, ryankroon00 approved these changes

2022-02-06 13:32 UTC, merged