359 post page revamp v1
AjobK/Athena pull request #385
Opened 2022-02-20 13:03 UTC by AjobK

closes #359 

<br />

 **What is it supposed to do**  
Revamped post edit with cancel functionalities

<br />

 **How can we test your branch**  
Create a post, edit banners, do all kinds of things.

<br />

 **Additional notes**  
 We use an UNSAFE method (willReceiveProps), but this is very thought through.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, back-end checklist**
- [x] a. No unhandled promise rejections.
- [x] b. Seeders still functional.
- [x] c. No primary-key violations.
- [x] d. Normalization, at least [3NF](https://en.wikipedia.org/wiki/Database_normalization).
- [x] e. Used guards (middleware) where necessary and tested if route is guarded.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [x] c. Opera
- [x] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2022-04-17 08:23 UTC, sribadal requested changes

2022-04-17 08:23 UTC, sribadal commented on frontend/src/components/postContent/index.js
> +
Was it supposed to be made safe in this PR, or a different PR?

2022-05-01 09:10 UTC, MrGooss submitted a review, later dismissed
LGTM

2022-05-15 08:38 UTC, AjobK commented on frontend/src/components/postContent/index.js
> +
Different PR, in our context it's safe

2022-05-15 08:38 UTC, merged