382 prototype popup
AjobK/Athena pull request #386
Opened 2022-03-06 13:06 UTC by jerohero

closes #382 

<br />

 **What is it supposed to do**  
Adds a toast component using the [react-hot-toast](https://react-hot-toast.com/) package that can be used from anywhere in the application to display success, error, warning and general messages. The contents can be configured through a _toastData.js_ file, containing all the configurations. You can configure the message's title, description, type (success, error, etc), and duration.

![image](https://user-images.githubusercontent.com/14930277/156921171-20983d10-6dc2-4866-888f-be1666932ce7.png)

![image](https://user-images.githubusercontent.com/14930277/156921224-e046fe40-676b-4623-a7ef-7cb465fd8d37.png)

![image](https://user-images.githubusercontent.com/14930277/156921241-b5d8d8fc-5be7-498c-bab0-85f36c2d81c3.png)

![image](https://user-images.githubusercontent.com/14930277/156921270-f8a4b1d0-8203-4c9d-b352-e6e708eb6700.png)

<br />

 **How can we test your branch**  
Currently there is only one place where a toast is created; in the _AppRouter_ file (pages/index.js). You could try calling this from other places and give other input. For different input take a look at the _toastData_ file (components/toast/toastData.js). Try different combinations. For example, if you want to have a toast that doesn't close without user input, add a duration field to your object and give it the Infinity value (this overrides the default duration value, defined at the top of the file).

<br />

 **Additional notes**  
Since react-hot-toast doesn't seem to support two pieces of text (title and description) for creating a toast, I had to generate an object with data which is then turned into a string, so the toast component can parse it back into an object and use the data. To avoid any hassle I made a _ToastUtil_ file, so this logic doesn't have to be worried about.

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [X] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**3. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

2022-03-20 12:07 UTC, AjobK requested changes
- [x] Add icon to general notification (call it info)
- [x] Remove yucky animation, make it invade
- [x] Center the notification

2022-05-01 09:25 UTC, AjobK submitted a review, later dismissed

2022-07-17 08:58 UTC, sribadal approved these changes
lgtm

2022-07-17 09:07 UTC, ryankroon00 approved these changes

2022-07-17 09:08 UTC, merged