369 refactor icon component
AjobK/Athena pull request #392
Opened 2022-04-30 08:50 UTC by sribadal

closes #369 

<br />

 **What is it supposed to do**  
This PR aims to add the functionality where adding icons by either FA or MUI is possible. Giving it a `prefix={'mui'}` with the corresponding iconName which can be found [here](https://mui.com/material-ui/material-icons/?query=heart),  you can load a MUI icon.

Not giving it a prefix will automatically default to FA

<br />

 **How can we test your branch**  
I added a material icon to the comment section. Whenever you place a comment you can give it a like, reply or even delete it. I replaced the heart icon with a material one.

1. After logging in, go to this [page](http://localhost:8080/new-post).
2. Write a post, and click on create.
3. After that, you can scroll down and add a comment to the post.
4. You can see a heart icon appear, if you hover over it, it will become red too

<br />

 **Additional notes**  
_It should still be possible to use FA, so all the existing icons should still work._

<br />

**1. General checklist**
- [x] a. Tested happy flow.
- [x] b. Tested unhappy flow.
- [x] c. No unexpected exceptions.
- [x] d. No code with high complexity. (Big O)
- [x] e. EOF newline.
- [x] f. No linter warnings or errors.

<br />

**2. If relevant, front-end checklist**
- [x] a. Responsive. (Desktop all the way to mobile 320px)
- [x] b. Using SCSS variables where relevant.
- [x] c. Relevant class names
- [x] d. No modified global SCSS properties, except if necessary and fully tested the impact.
- [x] e. Checked [caniuse](https://caniuse.com) for more modern CSS properties.

<br />

**4. If relevant, test these browsers**
- [x] a. Chrome
- [x] b. Firefox
- [ ] c. Opera
- [ ] d. Edge
- [ ] e. Safari

---

**PR Rules**  
*1. Add relevant labels.*  
*2. Select at least two reviewers.*  
*3. Assign all reviewers allowed to merge the branch, including yourself.*  
*4. If relevant to the sprint, put related issue in 'Awaiting Approval' column on project board.*  
*5. Add to the corresponding [milestone](https://github.com/AjobK/Seaqull/milestones).*

<br />

**Reviewer info**  
*1. You can use aliases to refer to specific PR checklist items. For example 'Hey @JohnDoe, for this line please check 3.a and 1.d.'*  
*2. Where possible, please use the suggestions feature in github so the author has a better idea of the solution you had in mind.*   

<br />

> This form should be filled in by the author of this PR.

2022-05-01 09:31 UTC, AjobK requested changes

2022-05-01 09:31 UTC, AjobK commented on frontend/src/components/icon/index.js
> +    let icon = icons[`${ prefix }${ iconName }`] || brands[`${ prefix }${ iconName }`] || icons['faBan']
```suggestion
    let combinedIconName = `${ prefix }${ iconName }`
    let icon = icons[combinedIconName] || brands[combinedIconName] || icons['faBan']
```

2022-05-01 09:31 UTC, AjobK commented on frontend/src/components/icon/index.js
> +    const renderSwitch = () => {
Change name to something more semantic. This could be anything

2022-05-01 10:15 UTC, AjobK approved these changes

2022-06-12 10:02 UTC, jerohero commented on frontend/package.json
> +    "@emotion/styled": "^11.8.1",
Are you using this? I don't see this being imported.

2022-06-12 10:05 UTC, jerohero approved these changes

2022-06-27 14:36 UTC, merged