Header closes #30
AjobK/Athena pull request #44
Opened 2019-01-04 20:38 UTC by MiguelFieira

## Changes

**Written by Ajob**

- Added mobile navigation with filler to push content on triggers
- Added desktop navigation with filler to push content on triggers
- Changed project name
- Added MobX and FontAwesome
- Made multiple stores for usage
- Added profilebar for users to see their progress regarding level and xp points

**End of writings by Ajob**

- Changed Project name to **SEAQULL**
- Changed **SEAQULL** Primary color from ~~#E5222C~~ to **#ff4040**
- **Fixed all style-linting errors of SEAQULL**
- Added Side Navigation
  - Added **"Profile"** section in side nav
    - Added default user image
    - Added false title "Best Developer"
    - Added User Level
    - Added static xp bar
  - Added Static Empty **"Home"** section
  - Added **"Personal"** section
     - Added Profile button
     - Added Notifications button
     - Added Favorite Posts button
     - Added Create Post button
     - Added Settings button
   - Added **"General"** section
     - Added About button
     - Added Contact button
  - Added side nav open & close animations
  - Added button hover for the Side Navigation
  - Added hamburger menu for Mobile version

### How to Test
- Pull form branch `30-header`
  - Run command `npm ci` so you have the latest dependency 
  - Run command `npm run dev` to startup the Local Development Environment Server 

## **Side Nav**
![image](https://user-images.githubusercontent.com/23557268/50722897-67153680-10d6-11e9-918a-2fdc5be9f807.png)

## **Full Page (Tablet)**
![image](https://user-images.githubusercontent.com/23557268/50722901-84e29b80-10d6-11e9-82e1-f939b19b76b5.png)

## **Mobile Page with Hamburger Menu**
![image](https://user-images.githubusercontent.com/23557268/50722909-a5125a80-10d6-11e9-9af5-415f7feeec3b.png)

2019-01-04 20:56 UTC, MiguelFieira reviewed
I'll fix the linting in a hotfix

2019-01-04 23:06 UTC, AjobK commented
Found bug when logging in and out on desktop. Component tries to render from for logged in content when logged out and vice versa. Gets undefined instead.

2019-01-05 09:38 UTC, MiguelFieira commented on src/layouts/index.js
>  }
endline

2019-01-05 09:40 UTC, MiguelFieira reviewed
endline

2019-01-07 19:42 UTC, MiguelFieira commented on src/components/profileBar/profilebar.scss
> +		background-image: url('../../static/dummyprofile.jpg');
According to his own code, a "DUMMY" profile pic 
![image](https://user-images.githubusercontent.com/23557268/50789508-c2a11900-12bc-11e9-8d38-92d6f2e62ff3.png)

2019-01-07 19:43 UTC, MiguelFieira commented on src/index.html
Remove Whiteline

2019-01-07 19:47 UTC, MiguelFieira commented on src/stores/defaultData.js
> +export default DefaultDataStore
endline

2019-01-07 19:47 UTC, MiguelFieira reviewed
see comment

2019-01-09 18:09 UTC, AjobK commented
@MiguelFieira @vQFire @Samvdg 

This needs to be reviewed ASAP

2019-01-09 23:01 UTC, vQFire requested changes
For now I just took a look at the code on my phone. Because I am laying in bed and was to lazy to dress up and sit behind my laptop. Tomorrow I will check on the laptop but for now fix these small things

2019-01-09 23:01 UTC, vQFire commented on src/components/button/index.js
> +    constructor (props) {
Useless constuctor

2019-01-09 23:01 UTC, vQFire commented on src/stores/user.js
> +export default UserStore
Add white line

2019-01-09 23:01 UTC, vQFire commented on src/components/profileBar/profilebar.scss
> +
2 whitelines instead of one

2019-01-10 18:56 UTC, Samvdg requested changes

2019-01-10 18:56 UTC, Samvdg commented on webpack.config.js
>      rules: [
indenting?

2019-01-10 21:06 UTC, Samvdg commented on src/layouts/main/main.scss
> +	> p {
why is this?

2019-01-10 21:06 UTC, Samvdg commented on src/layouts/main/main.scss
> +	grid-template-columns: repeat(auto-fill, minmax($grid-block-size, 1fr));
this doesn't work in IE.. will there be a different file for it some other time maybe?

2019-01-10 21:06 UTC, Samvdg commented on src/layouts/main/main.scss
> +	margin-left: -4px; // For inline blocks
don't know our situation about comments

2019-01-10 21:06 UTC, Samvdg commented on src/layouts/main/index.js
> +	componentDidMount() {
what does component did mount do actually?

2019-01-10 21:06 UTC, Samvdg commented on src/layouts/header/index.js
> +		return desktop && (
is this supposed to be desktop format? conditional rendering for screen size?

2019-01-10 21:06 UTC, Samvdg commented on src/components/profileBar/profilebar.scss
> +	background: -moz-linear-gradient(left, rgba(255,64,64,1) 0%, rgba(191,49,49,1) 27%, rgba(191,49,49,1) 52%, rgba(227,59,59,1) 73%, rgba(255,64,64,1) 100%);
didnt mozilla support rgba? it says so on caniuse.com

2019-01-10 21:06 UTC, Samvdg commented on src/components/navigationMobile/nav.scss
> +	// disable the header for maximum ensurance
again the comments thing

2019-01-10 21:06 UTC, Samvdg commented on src/components/navigation/nav.scss
> +	// Added everything necessary to hide and
dont forget to bring a towel
i mean..
what about the comments?

2019-01-10 21:06 UTC, Samvdg commented on src/components/navDropdown/dropdown.scss
> +	margin-right: 10px;
easier to read if you put this line above the nested `@include`

2019-01-10 21:06 UTC, Samvdg commented on src/components/navDropdown/dropdown.scss
> +	// Desktop
hmmm comments..
(just in case you didnt figure, purely highlighting all comments in case of they are needed to be removed)

2019-01-10 21:06 UTC, Samvdg commented on src/components/headerNavigation/index.js
> +				) : ( // Logged out content
commentoess

2019-01-10 21:06 UTC, Samvdg commented on src/components/hamburger/hamburger.scss
> +	&.hActive &Line:nth-child(2){
i assume this affects the 2nd/3rd item underneath said item above?
why not give the child element a seperate classname?

2019-01-10 21:27 UTC, vQFire commented
@AjobK are you supposed to be able to click the profile picture because you currently can't. If it just doesn't link to anything you can at least add `cursor: pointer;`

2019-01-10 21:59 UTC, vQFire requested changes
There is only one change and 2 are more optional But really look in to the breackpoint please because it will save a lot of code!

2019-01-10 21:59 UTC, vQFire commented on src/components/profileBar/profilebar.scss
> +
Use variables please! If you want to change this color I won't be doing it when it's like this...

2019-01-10 21:59 UTC, vQFire commented on src/layouts/main/index.js
> +	componentDidMount() {
@Samvdg It makes sure to run the code you put inside when it's mounted. So in other word when it is visible for the user. This makes sure that properties like `window` or `document` are available. When the code is excecuted it runs server sided first and then those properties are not available.

2019-01-10 21:59 UTC, vQFire commented on src/styles/breakpoints.scss
> +}
I don't know for sure but if you don't use `max-width` and only `min-width` you only need to overwrite the code and not duplicate it. 
**Example:**
You are making a painting and it is striped with 80% green and the rest is red.
You can do the following 2 things:
* You can paint green then red, green again ect.
* You can paint the entire canvas green and only paint the pieces you want red, red.

I hope this is clear if not I will explain in person.

2019-01-11 15:39 UTC, AjobK commented on src/layouts/main/main.scss
> +	grid-template-columns: repeat(auto-fill, minmax($grid-block-size, 1fr));
This is temporary. I am aware of the fact that this does not work in IE. I only added this as dummy to see the functionalities of the headerr

2019-01-11 15:39 UTC, AjobK commented on src/layouts/main/main.scss
> +	margin-left: -4px; // For inline blocks
Only use comments when something needs to be explained

2019-01-11 15:40 UTC, AjobK commented on src/layouts/main/index.js
> +	componentDidMount() {
👍

2019-01-11 15:40 UTC, AjobK commented on src/layouts/header/index.js
> +		return desktop && (
Yeah... I should probably make that a little cleaner

2019-01-11 15:41 UTC, AjobK commented on src/components/navigation/nav.scss
> +	// Added everything necessary to hide and
Hahaha, filler is the styling for an invisible component that still keeps the dimensions of it

2019-01-11 15:56 UTC, AjobK commented on src/components/hamburger/hamburger.scss
> +	&.hActive &Line:nth-child(2){
This is only for the hamburger and the common way to do this. That's the reason why I used nth-child. Sharp though

2019-01-11 15:57 UTC, AjobK commented on src/components/profileBar/profilebar.scss
> +		background-image: url('../../static/dummyprofile.jpg');
Haha damn it

2019-01-11 16:03 UTC, AjobK commented on src/styles/breakpoints.scss
> +}
Youp, what do you even mean

2019-01-11 16:08 UTC, AjobK commented
@MiguelFieira @Samvdg @vQFire Approve or request changes

2019-01-11 16:10 UTC, AjobK approved these changes
I think it's a good core build. Feel free to comment though if anything is wrong in your opinion.

2019-01-11 19:55 UTC, MiguelFieira commented
👍 Need to Check the Breakpoints in a later issue (@vQFire has some ideas)

2019-01-14 21:34 UTC, merged