Add Storybook to Seaqull | Closes #43
AjobK/Athena pull request #48
Opened 2019-01-13 20:47 UTC by Samvdg

Closes #43 

implemented storybook into the project

## How to run:
1. first do `npm ci`
2. run `npm run build-storybook` just to be safe
3. call `npm run storybook`
and now you should have the storybook page open

## What changed
- i added storybook to the project
- edited the storybook webpack.config.js so that it can read .sass files
- edited the storybook config.js for it to automaticly load in all .stories.js files

## Notice
- Test component stories will be removed at a later date
- Files in the folder `storybook-static` are automaticly generated

2019-01-14 21:47 UTC, AjobK requested changes
Works fine 👍 , though I'm not sure why but build-storybook doesn't work well?

Also, would be nice if you added a few dummy elements. I have merged develop so you should be able to.

2019-01-15 21:43 UTC, MiguelFieira commented on .storybook/config.js
> +// automatically import all files ending in *.stories.js
Captial letter

2019-01-15 21:44 UTC, MiguelFieira commented on .storybook/webpack.config.js
> +// you can use this file to add your custom webpack plugins, loaders and anything you like.
Unnecessary comments
Use capital letter at a start of a sentence

2019-01-15 21:44 UTC, MiguelFieira commented on .storybook/webpack.config.js
> +// When you add this file, we won't add the default configurations which is similar
Unnecessary comments

2019-01-15 21:45 UTC, MiguelFieira commented on .storybook/webpack.config.js
> +    // your custom plugins
Plugins part can be removed...
You don't have any plugins

2019-01-15 21:46 UTC, MiguelFieira commented on stories/index.js
> +  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
Remove the Example of storybook
Use a Seaqull component instead!

2019-01-15 21:47 UTC, MiguelFieira commented on storybook-static/iframe.html
> +<!doctype html><html><head><meta charset="utf-8"><title>Storybook</title><base target="_parent"><style>:not(.sb-show-main) > .sb-main,
Properly indent code!
It's a .html file

2019-01-15 21:48 UTC, MiguelFieira commented on storybook-static/iframe.html
> +  </pre></div><div id="root"></div><script src="runtime~main.2ce33a6eed47648b4286.bundle.js"></script><script src="vendors~main.2ce33a6eed47648b4286.bundle.js"></script><script src="main.2ce33a6eed47
Endline

2019-01-15 21:49 UTC, MiguelFieira reviewed
See Comments

2019-01-15 21:49 UTC, MiguelFieira commented on storybook-static/index.html
> +<!doctype html><html><head><meta charset="utf-8"><title>Storybook</title><style>html, body {
Properly indent code!
It's a .html file

2019-01-15 21:49 UTC, MiguelFieira commented on storybook-static/main.73f8654c8e52f28a85de.bundle.js
> +(window.webpackJsonp=window.webpackJsonp||[]).push([[0],{288:function(n,o,p){n.exports=p(289)}},[[288,1,2]]]);
Endline

2019-01-15 21:49 UTC, MiguelFieira requested changes
See comments

2019-01-21 18:24 UTC, Samvdg reviewed
@MiguelFieira The storybook-static/ files are automaticly generated. further more i fixed the rest of your comments that were of my own use

2019-01-21 18:24 UTC, Samvdg commented on storybook-static/iframe.html
> +<!doctype html><html><head><meta charset="utf-8"><title>Storybook</title><base target="_parent"><style>:not(.sb-show-main) > .sb-main,
this file is from storybook itself. it's static

2019-01-21 18:50 UTC, AjobK requested changes
![image](https://user-images.githubusercontent.com/35965716/51493503-d1f08e00-1db5-11e9-8ac9-22d0ce0b1268.png)

Hamburger looks messed up.

Also, did you check `npm run dev`?

2019-01-25 18:19 UTC, AjobK requested changes
Could you put everything storybook related in one folder?

For example .storybook and stories

2019-01-25 18:20 UTC, AjobK requested changes
If you fix these changes I'll approve 👍

2019-01-25 18:20 UTC, AjobK commented on stories/hamburger.stories.js
> +// import { action } from '@storybook/addon-actions';
Remove these comments please

2019-01-25 18:20 UTC, AjobK commented on stories/index.js
> +  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
Agree

2019-01-25 18:20 UTC, AjobK commented on stories/hamburger.stories.js
> +    .add('Clicked', () => <Hamburger active='true' /> )
Linting is terrible

2019-01-25 18:20 UTC, AjobK commented on stories/hamburger.stories.js
> +
Because of linting it's requesting a new line

2019-01-25 19:56 UTC, Samvdg commented on stories/index.js
> +  .add('with text', () => <Button onClick={action('clicked')}>Hello Button</Button>)
will be removed later

2019-01-25 19:57 UTC, MiguelFieira approved these changes
If you remove the Example in the future then the rest is fine by me.

2019-01-28 14:19 UTC, AjobK approved these changes

2019-01-28 14:19 UTC, merged