Back-End Folder Structure | Closes #55
AjobK/Athena pull request #51
Opened 2019-01-18 18:57 UTC by Samvdg

Closes #55 

## What changed
- Added DB ERD 
- Added DB SQL dump

## How to test
1. Switch to branch and pull
2. Run XAMPP
3. Navigate to your PHPMyAdmin
4. Press import
5. Import the SQL DUMP file
6. Check for errors 
7. Check the ERD if you agree with the tables and columns, if not please suggest changes, if you'd like to see things added please suggest ideas etc.

2019-01-18 19:21 UTC, AjobK commented on src/database/seaqull_SQL_DUMP.sql
> +-- Database: `athena`
Athena?

2019-01-18 19:34 UTC, AjobK requested changes
Changes mentioned in call

2019-01-21 17:39 UTC, MiguelFieira approved these changes
Comments on the top could be removed like PHP MYADMIN SQL DUMP
But fine for the rest

2019-01-23 10:45 UTC, vQFire requested changes
More comments then I hoped. But they are all easy resolved.

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `thumbnail` int(11) NOT NULL,
This can be null, if someone chooses not to have a thumbnail you will get a default image or colour. So far as my knowledge you cant store a image in number... We will probably giving it a random name or something. But we need to discuss this later on.

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `created_at` int(11) NOT NULL,
This can be `DATETIME` value....

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `updatet_at` int(11) NOT NULL
This can also be `DATETIME` value....

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `role` text NOT NULL,
Use `ENUM`here. This wil make sure the roles are specified in the DB and it can't be different.
[MORE INFO ABOUT ENUM](https://dev.mysql.com/doc/refman/8.0/en/enum.html)

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `role` int(11) NOT NULL,
Use `ENUM` here

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `passtoken` int(11) NOT NULL,
What is `passtoken` for??

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `deleted_at` datetime DEFAULT NULL
Change this to `archived_at`

2019-01-23 10:45 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `id` int(11) NOT NULL,
Is an `id` really needed? Because the token should be unique as well?

2019-01-23 16:34 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `role` int(11) NOT NULL,
Don't use enum

2019-01-23 16:34 UTC, vQFire commented on src/database/seaqull_SQL_DUMP.sql
> +  `role` text NOT NULL,
DOn't use enum

2019-01-24 18:11 UTC, vQFire requested changes
Please put the sql file in the following location
```
* /scr
* /system
  *  /database
    * PUT THE FILES HERE!!!
```

2019-01-25 17:53 UTC, AjobK commented
Could you add a single like attribute to posts?
Just a simple integer for now

2019-01-25 17:53 UTC, AjobK requested changes
Should token not be a varchar..?

2019-01-25 18:12 UTC, AjobK requested changes
Where are the views for posts?

2019-01-25 18:13 UTC, AjobK requested changes
Where is the thumbnail path? 

The normal path is for custom URL I assume?

2019-01-25 18:13 UTC, AjobK commented
Also, please do what Youp has recommended

2019-01-25 19:51 UTC, MiguelFieira approved these changes

2019-02-01 17:52 UTC, AjobK requested changes

2019-02-01 17:52 UTC, AjobK commented on src/database/seaqull_SQL_DUMP.sql
> +  `role` int(11) NOT NULL,
There will never be 10000000000+ roles

2019-02-01 17:52 UTC, AjobK commented on src/database/seaqull_SQL_DUMP.sql
> +  `user_name` text NOT NULL,
username instead of user_name

2019-02-08 18:46 UTC, AjobK approved these changes

2019-02-08 18:48 UTC, merged