Implement a Infinite Scroll on the home page with AJAX | Closes #49
AjobK/Athena pull request #58
Opened 2019-01-25 19:29 UTC by AjobK

Closes #49 

**Updates**
Me and Miguel made the infinite scroll on the homepage

**Things to do for next sprint**
- Make sure that posts don't load constantly when stuck at the bottom of page
- When you scroll, log in and log out, and go to 'My Profile' you get an error

2019-01-25 19:59 UTC, Samvdg approved these changes

2019-02-14 23:00 UTC, Samvdg commented on src/components/loader/loader.scss
> +		box-shadow: 0 0 0 10px rgba(255,64,64, 0);
can't you just do `box-shadow-left` ?
edit: (this ofcourse applies to all instances within the css)

2019-02-14 23:02 UTC, Samvdg commented on src/components/posts/index.js
> +  isAtEndOfPage() {
just questioning if the function name isn't already explained enough? unnecessary comment?

2019-04-05 18:37 UTC, MiguelFieira requested changes
Linting

2019-04-05 18:37 UTC, MiguelFieira commented on src/components/registerPrompt/index.js
> -export default RegisterPrompt
endline

2019-04-08 16:00 UTC, closed without merging