Created the templates #52
AjobK/Athena pull request #62
Opened 2019-01-28 22:06 UTC by vQFire

closes #52 

**What is it supposed to do**
It makes sure we all get some structure in our issues en pull requests

**How can we test your branch**
It is hard to test what you can do is look at the template and check for mistakes in grammar. If you really want to test the templates you need to test it in your own repo. I did test it in my own repo to make sure it works.

**What browser have been checked**
It can't be checked in a browser because it is not in Seaqull.

2019-01-28 22:14 UTC, AjobK requested changes
👍

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +Describe when your feature would be complete!
will be

2019-01-28 22:14 UTC, AjobK commented on .github/PULL_REQUEST_TEMPLATE.md
> +Explain how can test your branch Ex. width, height etc...
Explain how can?
Ex.?
This is very unclear...
Please do it in the following way

'Preperation before testing (Eg. width, height)'

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +labels: ''
Add label improvement? Maybe? If Possible?

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +**Describe the solution you'd like**
you would

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +**Describe alternatives you've considered**
you have

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +**Is your feature request related to a problem? Please describe.**
Unnecessary 'Please describe'

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +title: ''
Add 'Issue name | Closes #XXX'

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +**D.O.D.**
Definition of done, fully

2019-01-28 22:14 UTC, AjobK commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What is it supposed to do**
What it is supposed to do

2019-01-28 22:14 UTC, AjobK commented on .github/PULL_REQUEST_TEMPLATE.md
> +closes #XXX
Closes #XXX

2019-01-28 22:14 UTC, AjobK commented on .github/ISSUE_TEMPLATE/feature.md
> +Add any other context or designs about the feature request here.
'about the feature request here' is unnecessary

2019-01-28 22:14 UTC, AjobK commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What browser have been checked**
Instead of this use

'What browser(s) has/have been checked'
or
'Tested browsers'

2019-01-28 22:24 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +title: ''
It is hard to close an issue in an issue is it not?

2019-01-28 22:26 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +labels: ''
This has been updated

2019-01-28 22:26 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +**Is your feature request related to a problem? Please describe.**
This has been updated

2019-01-28 22:26 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +**Describe the solution you'd like**
This has been updated

2019-01-28 22:26 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +**Describe alternatives you've considered**
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +Add any other context or designs about the feature request here.
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +**D.O.D.**
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/ISSUE_TEMPLATE/feature.md
> +Describe when your feature would be complete!
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/PULL_REQUEST_TEMPLATE.md
> +closes #XXX
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What is it supposed to do**
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/PULL_REQUEST_TEMPLATE.md
> +Explain how can test your branch Ex. width, height etc...
This has been updated

2019-01-28 22:27 UTC, vQFire commented on .github/PULL_REQUEST_TEMPLATE.md
> +**What browser have been checked**
This has been updated

2019-01-29 20:01 UTC, MiguelFieira requested changes
Small suggestions...
Dismiss my Review if others agree on the current version

2019-01-29 20:01 UTC, MiguelFieira commented on .github/PULL_REQUEST_TEMPLATE.md
> +Explain in short what your component is supposed to do
Not all issue's are "component" related, I would rather see a Description of what the problem was & what is should do.

2019-01-29 20:01 UTC, MiguelFieira commented on .github/PULL_REQUEST_TEMPLATE.md
> +
Maybe add a checklist of tasks in the original issue & put the same one here so we can all see in order what changed

2019-02-08 18:48 UTC, MiguelFieira approved these changes

2019-02-08 19:05 UTC, Samvdg approved these changes

2019-02-08 19:05 UTC, merged