Linting Update | Closes #53
AjobK/Athena pull request #63
Opened 2019-01-29 19:51 UTC by MiguelFieira

closes #53 

## Description
In today's Pull Request we have made some progress on the JS Linter!
We have expanded the old linter to include way more options and fixed most linting errors.

**D.O.D Tasks**
- [X] 2 spaces in stead of 1 tab
- [X] Made sure the error log works
- [X] Fix experimentalDecorators error
- [X] Expanded the options for linter usage
- [X] Fix most linting errors
  - (Left 1 because @AjobK  has to take a look)

### Dependencies Changes
- Added **npm-check** for a future issue for fixing all outdated dependencies.
  - To use it make sure to install it globally! **``npm i npm-check -g``**

2019-01-29 21:06 UTC, Samvdg commented
How do we feel about new lines before a variable declaration as well?

2019-01-29 22:10 UTC, AjobK requested changes

2019-01-29 22:10 UTC, AjobK commented on stories/hamburger.stories.js
> +  .add('Clicked', () => <Hamburger active="true" />)
double quotes

2019-02-01 18:38 UTC, vQFire approved these changes
I have many comments!

2019-02-01 19:00 UTC, Samvdg approved these changes

2019-02-04 21:11 UTC, merged