60 profile page
AjobK/Athena pull request #67
Opened 2019-02-10 16:30 UTC by AjobK

closes #60 

 **What is it supposed to do**
- Made entire profile page
- Changed menu to be fully responsive
- Added logo
- Added error component, which is not yet used

 **How can we test your branch**
Go to branch `60-profile-page`
Go to browser
Open developer console
Press device view button
Test all devices

 **What broweser have been checked**
- [X] Chrome
- [X] Firefox
- [X] Opera
- [X] Internet Explorer
- [X] Edge
- [ ] Safari

2019-02-10 16:42 UTC, MiguelFieira requested changes
See Comments

2019-02-10 16:42 UTC, MiguelFieira commented on .babelrc
> +        "@babel/plugin-proposal-class-properties",
Change this & line 6 back to only "@babel/plugin-proposal-class-properties"

2019-02-10 16:42 UTC, MiguelFieira commented on package.json
> +    "@babel/polyfill": "^7.2.5",
Remove this Polyfill line

2019-02-10 16:42 UTC, MiguelFieira commented on src/components/index.js
> +// Import Navigation from './navigation'
Uncomment or remove this

2019-02-10 16:42 UTC, MiguelFieira commented on src/components/index.js
> +  // The Navigation,
Uncomment or Remove

2019-02-10 16:42 UTC, MiguelFieira commented on src/components/navigation/index.js
> +// 		const { nav } = this.props.store
Uncomment or Remove

2019-02-10 16:42 UTC, MiguelFieira commented on src/components/navigation/index.js
> +// 									return (
Uncomment or Remove

2019-02-10 16:52 UTC, vQFire reviewed
Look at the comments.

2019-02-10 16:52 UTC, vQFire commented on src/components/index.js
> +// Import Navigation from './navigation'
Remove comment

2019-02-10 16:52 UTC, vQFire commented on src/components/index.js
> +  // The Navigation,
Remove comment

2019-02-10 16:52 UTC, vQFire commented on src/components/navigation/index.js
> +// import React, { Component } from 'react'
Why is this whole file commented?

2019-02-10 16:52 UTC, vQFire commented on src/components/navigationMobile/nav.scss
> +	margin-left: -1px;
margin-right: 1px; ?

2019-02-10 16:52 UTC, vQFire commented on src/components/postsPreview/postsPreview.scss
> +	background-color: transparent !important;
important?

2019-02-10 16:52 UTC, vQFire commented on src/components/postsPreview/postsPreview.scss
> +		background-color: rgba(0,0,0,0.1) !important;
important?

2019-02-10 16:52 UTC, vQFire commented on src/components/statistic/index.js
> +  numberFormat(input) { // Give input in integers
```
/** 
* @param {number} input
*/
```

2019-02-10 16:52 UTC, vQFire commented on src/components/statistic/index.js
> +  numberFormat(input) { // Give input in integers
instead of comment

2019-02-10 16:52 UTC, vQFire commented on src/components/statistic/index.js
> +  timeFormat(input) { // Give input in minutes
Do the same here use JSDoc

2019-02-10 16:52 UTC, vQFire commented on src/stores/user.js
> +    percentage: types.optional(types.number, 10) // Percentage
Remove comment

2019-02-10 17:16 UTC, AjobK commented on src/components/navigationMobile/nav.scss
> +	margin-left: -1px;
Does not do the same. This pushes the content back, while margin-right: 1px; pushes the other content to the right

Please resolve or update your comment @vQFire

2019-02-10 17:20 UTC, AjobK commented on .babelrc
> +        "@babel/plugin-proposal-class-properties",
This comment should be invalid.

Please resolve or update comment @MiguelFieira

2019-02-10 17:26 UTC, MiguelFieira requested changes
See Comment

2019-02-10 17:26 UTC, MiguelFieira commented on src/styles/variables.scss
>  	font-family: 'RockwellBold';
Rockwell should be Poppins

2019-02-10 17:26 UTC, MiguelFieira commented on src/styles/variables.scss
> +@import url('https://fonts.googleapis.com/css?family=Arvo:300,300i,400,400i,600,600i,700,700i,800,800i');
Arvo should be Poppins

2019-02-10 17:26 UTC, MiguelFieira commented on package.json
> +    "babel-polyfill": "^6.26.0",
Remove Polyfill, it's not being used!

2019-02-10 17:34 UTC, MiguelFieira requested changes
Small Change Request

2019-02-10 17:34 UTC, MiguelFieira commented on package.json
> -    "random-words": "^1.1.0",
This dependency should be removed, it's not being used anymore

2019-02-11 09:04 UTC, vQFire commented on src/components/navigationMobile/nav.scss
> +	margin-left: -1px;
Ok

2019-02-11 09:11 UTC, MiguelFieira requested changes
See comments

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/logo/logo.scss
> +		font-weight: bold;
**Suggestion not a request!**
I would use "700" instead so you have more options in the future if you want to make a minor teak to the font-weight!
![image](https://user-images.githubusercontent.com/23557268/52552565-0b2e8380-2de1-11e9-9f7a-249546968648.png)

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/statistic/index.js
> +        color: '#66c1ff',
**A Suggestion not a Request!**
You use variables in your .scss files for color but you don't use it here?

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/userBanner/userBanner.scss
> +		font-size: 32px;
Please use **rem** sin's its more responsive then **px** for a font-size!

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/userBanner/userBanner.scss
> +		font-size: 1vw;
Please use **rem** instead of **1vw** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/userBanner/userBanner.scss
> +			font-size: 22px;
Please use **rem** instead of **px** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/userBanner/userBanner.scss
> +			font-size: 20px;
Please use **rem** instead of **px** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/userBanner/userBanner.scss
> +			font-size: 18px;
Please use **rem** instead of **px** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/styles/variables.scss
> +$logo-font-size: 44px;
Please use **rem** instead of **px** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/styles/variables.scss
>  $logo-font-size-sm: 44px;
Please use **rem** instead of **px** for font-size to stay consistent with the other .scss files!

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/navigationMobile/nav.scss
>  	z-index: -1;
**Suggestion not a Request!**
We should prob write down witch z-index is being used for most components to stay consistent throughout the project.

2019-02-11 09:11 UTC, MiguelFieira commented on src/components/navigationMobile/nav.scss
>  		width: 325px;
**Suggestion not Request!**
You use vw en px inconsistently, make up your mind and stick to one!

Side-note:
A interesting post for using **EM/REM/PX**
https://engageinteractive.co.uk/blog/em-vs-rem-vs-px

2019-02-11 09:13 UTC, vQFire commented on src/components/index.js
> +  // The Navigation,
Has been resolved

2019-02-11 16:43 UTC, AjobK commented on src/components/logo/logo.scss
> +		font-weight: bold;
Adding more options (Font types for a single font) increases loading time for the page. I wanted to avoid this, hence I used only two types, which will represent normal and bold.

We might implement more in the future, but momentarily this is not the case.

2019-02-11 16:44 UTC, AjobK commented on src/components/statistic/index.js
> +        color: '#66c1ff',
I can't use scss variables in javascript haha. This would be a singular and unique case. Good feedback though!

Still, no reason to change this.

2019-02-11 17:02 UTC, AjobK commented on src/components/navigationMobile/nav.scss
>  	z-index: -1;
Yes, we should. -1 Is not really relevant though, since the purpose is to go underneath objects.

2019-02-11 17:02 UTC, AjobK commented on src/components/navigationMobile/nav.scss
>  		width: 325px;
Haha, savage

2019-02-11 17:03 UTC, AjobK commented on src/components/navigationMobile/nav.scss
>  		width: 325px;
Just a notice though. PX can be used without issues for blocks, just not font sizes etc.

2019-02-11 17:04 UTC, AjobK commented
@MiguelFieira Please check again

2019-02-11 17:10 UTC, MiguelFieira approved these changes
Well Done!

2019-02-12 19:52 UTC, AjobK commented
@vQFire @Samvdg Guys, this is insane. I've been waiting for multiple days for a single review.

I can NOT work without the items in this PR. Seriously, get your stuff together.

2019-02-12 20:17 UTC, vQFire reviewed
Approve

2019-02-12 20:18 UTC, vQFire approved these changes

2019-02-12 20:24 UTC, merged