Post Banner closes #68
AjobK/Athena pull request #71
Opened 2019-02-15 12:14 UTC by MiguelFieira

closes #68 

 **What is it supposed to do**
If click on a post it should open a post view page with a banner according to design.

 **How can we test your branch**
- Go into branch ``68-post-view`` make sure to ``npm ci`` and click on a post on the homepage.
- Check of the banner is according to design

 **What browser have been checked**
- [X] Chrome
- [x] Firefox
- [x] Opera
- [ ] Internet Explorer
- [x] Edge
- [ ] Safari

2019-02-15 12:16 UTC, MiguelFieira commented
**NOTES TO FIX:**
Edge is not correct!
![image](https://user-images.githubusercontent.com/23557268/52856196-07259d00-3124-11e9-8ad7-6dac10bad164.png)

Update: Changed the rgba so it looks better on edge!
![image](https://user-images.githubusercontent.com/23557268/52857033-4228d000-3126-11e9-8dec-8a24ce1fcfd8.png)

2019-02-15 12:21 UTC, MiguelFieira commented on src/components/postBanner/postBanner.scss
> +	&Edit {
Add Z-index!

2019-02-15 12:21 UTC, MiguelFieira commented on src/stores/user.js
> +    picture: types.optional(types.string, '../src/static/dummy/user/profile.jpg'),
@AjobK can you take a look at this if it's okay to stay like this!

2019-02-15 12:21 UTC, MiguelFieira commented on src/components/postBanner/index.js
> +            <div className={styles.picture} style={{ backgroundImage: `url(${user.picture})` }}>
Make sure to change the store when the back-end is ready!

2019-02-15 12:32 UTC, MiguelFieira commented on src/components/postBanner/postBanner.scss
> +	&Edit {
Fixed!

2019-02-15 12:41 UTC, vQFire reviewed
Is is more of a question that a comment. If it is answered I will approve!

2019-02-15 12:41 UTC, vQFire commented on src/components/posts/index.js
> +      let contactText = document.createElement('div')
Can be constant since it does not change.

2019-02-15 12:46 UTC, MiguelFieira commented
Checked Chrome,Firefox,Opera,Edge!
IE11 was broken again
I don't own a Mac for Safari check!

2019-02-15 13:05 UTC, MiguelFieira commented on src/components/posts/index.js
> +      let contactText = document.createElement('div')
I'm instructed not to change anything further only linting sins it's not part of the issue i'm currently working on.
Please check again if you have any further comments @vQFire

2019-02-15 13:32 UTC, vQFire approved these changes
Looks Good!

2019-02-15 18:19 UTC, AjobK requested changes
Not responsive

2019-02-18 18:01 UTC, Samvdg approved these changes

2019-02-19 20:21 UTC, AjobK requested changes
Also, the postBanner is not aligning with the header. The wrapper should have a maximum width of 1000px (wrapper-width). If smaller then it should go to 100% with a padding of $header-padding or something like this. This is 20px.

Do not use media queries, look at reference

2019-02-19 20:21 UTC, AjobK commented on src/stores/user.js
> +    picture: types.optional(types.string, '../src/static/dummy/user/profile.jpg'),
No. This isn't working for me.

2019-02-19 20:21 UTC, AjobK commented on src/stores/user.js
> +    banner: types.optional(types.string, '../src/static/dummy/user/banner.jpg'),
This isn't working either. Do not change this. This is simply dummy data

2019-02-19 20:22 UTC, AjobK commented
Also, don't use my letter size check. The font size is way too small compared to the role

2019-02-19 20:42 UTC, closed without merging