PostBanner
AjobK/Athena pull request #79
Opened 2019-02-19 22:03 UTC by MiguelFieira

closes #68 

 **What is it supposed to do**
If click on a post it should open a post view page with a banner according to design.

 **How can we test your branch**
- Go into branch ``68-post-view`` make sure to ``npm ci`` and click on a post on the homepage.
- Check of the banner is according to design

 **What browser have been checked**
- [X] Chrome
- [x] Firefox
- [x] Opera
- [ ] Internet Explorer
- [x] Edge
- [ ] Safari

2019-02-22 19:05 UTC, Samvdg approved these changes

2019-02-22 19:22 UTC, vQFire requested changes
Just this one thing

2019-02-22 19:22 UTC, vQFire commented on src/pages/post/index.js
>        <>
You can just return `<Strandard />` no need to use `<>`

2019-02-22 19:23 UTC, MiguelFieira commented on src/pages/post/index.js
>        <>
Fixed! Please recheck @vQFire

2019-02-22 19:25 UTC, vQFire commented on src/pages/post/index.js
>        <>
Fixed

2019-02-22 19:25 UTC, vQFire approved these changes
👍

2019-02-22 19:30 UTC, Samvdg approved these changes

2019-02-24 22:09 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/53306082-12e23380-3889-11e9-8850-10bf293f6841.png)

Very strange look for mobile. The name and role are not in the middle.

Maybe center the photo and info on mobile. (mobile-all-portrait media query)

2019-02-24 22:09 UTC, AjobK commented
Also. the level is cut off by profile picture...

2019-02-24 22:10 UTC, AjobK commented
When name or role is longer, the info goes underneath in a really strange way

2019-02-24 22:11 UTC, AjobK requested changes
Check comments

2019-02-24 22:11 UTC, AjobK commented
Cursor pointer when I hover over the black box?

2019-03-04 20:32 UTC, AjobK requested changes
**1. Not centered.**
**2. The role should not be that wide.**
**3. The level is awkwardly inside profile picture**
![image](https://user-images.githubusercontent.com/35965716/53760913-7b05ca80-3ec4-11e9-93e7-1ad6ae2f7820.png)

**Why does this entire box have cursor pointer? Only profile picture and name**
![image](https://user-images.githubusercontent.com/35965716/53761054-dd5ecb00-3ec4-11e9-8bfe-7c01df1db072.png)

2019-03-04 20:34 UTC, AjobK commented
The role width is as wide as the users name. So if the users name is only 1 letter, we have a major problem.

2019-03-04 20:41 UTC, AjobK commented
![image](https://user-images.githubusercontent.com/35965716/53761616-46930e00-3ec6-11e9-8b3c-f7a9ea0a1979.png)
When screen is too small and name is longer..? Should be ellipsis

Example:
Emily washi...

2019-03-08 17:43 UTC, MiguelFieira commented
@AjobK All issues mentioned have been fixed. Could you do a review again please?
Mention me if i missed something.

Thanks in advance!

Kind Regards,

[Miguel Fieira](http://www.linkedin.com/in/miguel-fieira/)
Developer [Seaqull](http://www.seaqull.com/)

2019-03-08 19:34 UTC, AjobK requested changes
Told u in discord. Ask again if needed.

2019-03-22 20:30 UTC, closed without merging