97 migrations
AjobK/Athena pull request #99
Opened 2019-05-30 10:20 UTC by Samvdg

closes #97 

 **What is it supposed to do**
This is a database branch where DB files were added such like more migrations in order to update the database itself or ERD files

## PLEASE READ AGAIN

 **How can we test your branch**
for the migration

First we have to delete the current database to make everything easier for ourselves
1. First navigate to XAMPP
2. Select the DB 'seaqull'
3. Go to 'Actions' or 'Handelingen' up top 
![image](https://user-images.githubusercontent.com/42764788/59068553-b8f3ff80-88b4-11e9-8d52-2c1c4fd32aa5.png)
4. Then press the 'delete database' text, it can't be missed. It's highlighted in red
![image](https://user-images.githubusercontent.com/42764788/59068633-f062ac00-88b4-11e9-8507-02545743bdc2.png)
5. Confirm
6. Create a new DB within XAMPP called 'seaqull'
7. Done :D

Now let's fill it up
1. Navigate to seaqull/passport (`cd passport`)
2. Do `php artisan migrate`
3. Go to phpMyAdmin and view the DB changes
4. Run `php artisan migrate:rollback` (in the case that this did not roll back all migrations, run `migrate:reset instead`
5. Run step 2 again
6. Let me know if anything fails

**How can we view the ERD**
Just take a look at the ERD files in `seaqull/src/database`

2019-05-30 10:58 UTC, ghost commented
Attachment and post should have a many-to-many relationship in my opinion. I think users should not be limited to one attached file per post.

2019-05-31 21:00 UTC, AjobK commented
1. I don't see any relationships between the tables?
2. The table names are entirely lowercase and connected. Maybe use snake_case instead

2019-05-31 21:00 UTC, AjobK requested changes
See comments

2019-05-31 21:03 UTC, AjobK requested changes
See comments

2019-05-31 21:03 UTC, AjobK commented on passport/database/migrations/2019_05_28_181934_creating_title.php
> +}
Newline

2019-05-31 21:03 UTC, AjobK commented on passport/database/migrations/2019_05_28_210801_updating_attachment.php
> +            //
Why are some down() functions empty and some not?

2019-05-31 22:00 UTC, AjobK requested changes
Only use int(11) for foreign keys, since bgint foreign keys don't show relations in phpmyadmin designer.

2019-06-01 13:17 UTC, Samvdg commented on passport/database/migrations/2019_05_28_210801_updating_attachment.php
> +            //
because some are 'create table' migrations. If these are reverted, the down function wil be called... i believe atleast. Now that i realized this i think more needs to be added to the migrations. Tho it wouldn't really matter because we could litteraly simply delete all these migrations and keep the good ones since we aren't live at all

2019-06-01 13:31 UTC, AjobK commented on passport/database/migrations/2019_05_28_210801_updating_attachment.php
> +            //
I understand, but I think you should fill the down functions not only for readability, but also consistency. Deleting migrations is simply not an option because when we merge with a deployed version, the changes will merge incorrectly. We have not deployed anything yet, but it is better to start the right way instead of switching our manners later on.

Another reason why we want to fill the down function is that sometimes we simply want to rename columns. If we run the down function, we only want the column to be renamed back, not deleted.

2019-06-01 15:33 UTC, Samvdg commented on passport/database/migrations/2019_05_28_210801_updating_attachment.php
> +            //
if you want a rename for a column, that requires a new migration. Unless you DID a rename and you revert that migration (considered it has the correct down() function)

2019-06-01 17:56 UTC, AjobK requested changes
Down function

2019-06-01 17:56 UTC, AjobK commented on passport/database/migrations/2019_06_01_132842_renaming_tables_to_snake_case.php
> +            //
You don't rename the tables back with the down function... Update this migration please

2019-06-02 07:18 UTC, ghost commented on passport/database/migrations/2019_05_24_173912_creating_comments.php
> +        Schema::dropIfExists('comment');
Don't know if it matters here, but you wrote 'comment' without a capital C

2019-06-02 07:22 UTC, ghost commented on passport/database/migrations/2019_05_28_175847_renaming_tables.php
> +            //
Missing reverse function

2019-06-02 07:28 UTC, ghost commented on passport/database/migrations/2019_05_28_182612_seperating_user_data.php
> +        Schema::dropIfExists('User');
'down' method doesn't leave you with the previous 'state' of the schema. I don't know if it will be a problem in the future, but please don't 'drop' the table in the 'up' method

2019-06-02 07:35 UTC, ghost commented on passport/database/migrations/2019_05_28_193936_creating__user_post_actions.php
> +            $table->integer('like_weight')->nullable();
I think 'like_weight' is redundant. You can determine the 'weight' of a like by looking at the user's role. Unless we want other factors to influence the weight, you can probably remove this.

2019-06-02 07:38 UTC, ghost commented on passport/database/migrations/2019_05_28_193936_creating__user_post_actions.php
> +            $table->primary(['id', 'user_id', 'post_id']);
Assuming this creates a composite primary key, you don't need the 'id' field.

2019-06-02 07:38 UTC, ghost commented on passport/database/migrations/2019_05_28_201612_creating__user_comment_like.php
> +            $table->primary(['id', 'user_id', 'comment_id']);
Assuming this creates a composite primary key, you don't need the 'id' field.

2019-06-02 07:45 UTC, ghost commented on passport/database/migrations/2019_05_29_201010_creating_reset_and_verify.php
> +            $table->timestamp('verified_at')->nullable();
'verified_at' should be moved to the account table, or replaced with a simple flag in the account table.
After a user verifies their email I don't see a point in keeping the verification code.

2019-06-02 07:52 UTC, ghost requested changes
The relationship between Attachment and Post should be many-to-many. Currently, the user can only 'attach' one file or photo with their post. In my opinion, we shouldn't limit users to a single file and instead limit the file size of the attached file or photo.

2019-06-02 11:31 UTC, AjobK commented on passport/database/migrations/2019_05_24_173912_creating_comments.php
> +        Schema::dropIfExists('comment');
Should not matter since the database tables are named using snake_case and it starts with a lower case

2019-06-02 11:33 UTC, AjobK commented on passport/database/migrations/2019_05_28_193936_creating__user_post_actions.php
> +            $table->integer('like_weight')->nullable();
Let's just remove it. The idea was that the user would be able to possibly like multiple times in the future, kind of like Medium. However, this is way out of scope and if we really wanted to implement this we could do so easily somewhere in the future.

2019-06-02 11:37 UTC, AjobK commented on passport/database/migrations/2019_05_28_210801_updating_attachment.php
> +            //
I used the rename functionality as an example. What I meant is that the down function should do exactly the opposite of the up function. A create migration should have a down function that removes. An upgrade migration should have a down function that downgrades. Down functions should **NEVER** be empty. If we were to rollback to an older state of the database, this would be very hard to achieve since you decided not to fill out the down functions for a create. By your argument you could say that there would never be a down functionality.

2019-06-03 06:06 UTC, Samvdg commented on passport/database/migrations/2019_06_01_132842_renaming_tables_to_snake_case.php
> +            //
oops my bad! XD

2019-06-03 15:17 UTC, Samvdg commented on passport/database/migrations/2019_05_28_193936_creating__user_post_actions.php
> +            $table->primary(['id', 'user_id', 'post_id']);
not sure it doesn't, i mean please tell me if you know for sure because i don't but i don't know if when you don't add the standard PK it creates a second PK, makes it seperate, doesn't add it at all or if it adds them automaticly

2019-06-03 15:36 UTC, ghost commented on passport/database/migrations/2019_05_28_193936_creating__user_post_actions.php
> +            $table->primary(['id', 'user_id', 'post_id']);
I don't really understand what you're telling me here but:
If you pass an array to the primary method it creates a composite primary key. when you make the combination of 'user_id' and 'post_id' primary key, you really don't need the id field. Or you can keep the id field but remove the other two of course.

2019-06-05 19:24 UTC, Samvdg commented
> The relationship between Attachment and Post should be many-to-many. Currently, the user can only 'attach' one file or photo with their post. In my opinion, we shouldn't limit users to a single file and instead limit the file size of the attached file or photo.

This has happened btw, i just didn't push it yet

2019-06-11 18:12 UTC, AjobK approved these changes
Fine to me

2019-06-11 21:04 UTC, merged